### ISSUE TITLE
Are there any plans to integrate with StackExchange.Redis library?

### ISSUE THREAD

**Issue by aensidhe** [MiniProfiler/dotnet#100]
Hello.

I see a lot of storage supported, but not StackExchange.Redis. Do you plan to implement it?

Thank you.

**Comment by yellis** [comment]
I dont think that we are going to do that as part of the main project as it would add an additional dependency that most people dont need. If you need this you should implement `IStorage` as you see fit (could easily be made into its own nuget).

**Comment by aensidhe** [comment]
I'm sorry, I talked about profiling calls to Redis like you already profile calls to Sql Server, Mongo, EF, etc and not about storing results in Redis.

**Comment by yellis** [comment]
I guess I misunderstood your question then.

If you want to profile timings for anything other than the built-in timings, use `MiniProfiler.Current.CustomTiming()` to track this. You can see this [in the demo project](https://github.com/MiniProfiler/dotnet/blob/master/Sample.Mvc/Controllers/HomeController.cs#L116).
