### ISSUE TITLE
MongoDB Driver needs more exact documentation, or the interface needs to be filled in

### ISSUE THREAD

**Issue by digitalpacman** [MiniProfiler/dotnet#101]
The current implementation of the MongoDB driver only supports one method of querying and only one method for getting a collection.  It also does not support the full LINQ interface on the MongoCursor.  It would be a great help if there was actual documentation saying "this is the only way this class works".      I had to dig around to make sure all the methods were actually implemented. This is the only format for querying mongo that's supported:

```c#
 var collection = db.GetCollection<MongoItem>("MongoItemCollection", new MongoCollectionSettings());
 foreach (var item in collection.FindAs<MongoItem>(queryById))
 {                
 }
```

This is extremely frustrating to have to find out digging through code because the only example on the documentation is to wrap the server and then it talks as if it's just going to work. It's not.

This also does not profile:

```c#
 var x = collection.FindAs<MongoItem>(queryById).First();
```

And I get this is because there is no LINQ provider. But how is someone supposed to know that?

Even the sample application does not profile correctly. This is the command that it runs to fetch a record:

```c#
 var oneRecord = Repository.FooCollection.FindOneAs<BsonDocument>(Query.GT("r", Random.NextDouble()));
```

This does not profile.  Comment the whole controller out except for that one line, run it, and you'll see no profiling. This is becaue you are not using the code format explained above. So even the code samples aren't correctly showing how to write mongo data access using miniprofiler.  The only code that will work with that statement is:

```c#
 BsonDocument oneRecord;
 foreach (var record in Repository.FooCollection.FindAs<BsonDocument>(Query.GT("r", Random.NextDouble()))) 
 {
      oneRecord = record;
 }
```

That, will profile, and only that.

I can't say this is an issue for miniprofiler, because I don't know if you care about profiling GET data queries against mongo. But it sure looks like it should work.

**Comment by NickCraver** [comment]
I agree. I'm closing this out not out of disagreeing, but to point all traffic at #125 where we're working on a vNext of that library on the latest driver.
