### ISSUE TITLE
MaxJsonResponseSize when profiling ASMX web services calls

### ISSUE THREAD

**Issue by mhallin79** [MiniProfiler/dotnet#103]
Hi guys,

I have an issue when I'm profiling asmx webservice calls. I have set the MiniProfiler.Settings.MaxJsonResponseSize to int.MaxValue.

I believe that the MaxJsonResponseSize  value is not honored during a asmx call for some reason as I can Serialize the profiler myself before calling MiniProfiler.Stop()

In below screen dump I write out the MaxJsonLength for different serializesers to the debug windows (line 198-203) and then I use my own JavaScriptSerializer to serialize MiniProfiler after and that do a quick byte count and as you can see in the debug window the count is less then MiniProfiler.Settings.MaxJsonResponseSize. 

However I still get the _Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property._. 

I only have this problem with asmx services.
![image](https://cloud.githubusercontent.com/assets/5432014/6934596/f5f64384-d882-11e4-85e3-e47bc9bbe40a.png)

I have also set the jsonSerialization maxJsonLength="2147483647" in the web.config without detecting a difference.

Any assistance troubleshooting this issue is greatly appreciated.

Kind regards,

Mikael

**Comment by NickCraver** [comment]
Thanks for the report! This is due to the `.ToJson()` helper underneath when saving. I've fixed it for the v4 release.

Note: same issue as #138
