### ISSUE TITLE
\IpAddressProvider.cs:27  ,InvalidProgramException ,  JIT error

### ISSUE THREAD

**Issue by lovemory** [MiniProfiler/dotnet#106]
StackExchange.Profiling.IpAddressIdentity.GetUser(HttpRequest request) in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\IpAddressProvider.cs:27
StackExchange.Profiling.WebRequestProfilerProvider.Start(ProfileLevel level, String sessionName) in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\WebRequestProfilerProvider.cs:90
StackExchange.Profiling.MiniProfiler.Start(String sessionName) in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\MiniProfiler.cs:280
StackExchange.Profiling.MiniProfiler.Start() in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\MiniProfiler.cs:266
Magicodes.MiniProfilter.PlusStarter.EventsManager_BeginRequest(Object sender, EventArgs e) +373
System.EventHandler.Invoke(Object sender, EventArgs e) +0

**Comment by yellis** [comment]
From the stack trace I am guessing that there is some issue with getting the IP address of the user, most likely related to your specific setup. What have you tried? Can you repro it on a different network? What are the specifics of your setup?

**Comment by NickCraver** [comment]
Closing this due to no information to go on & inactive.
