### ISSUE TITLE
Update RavenDB to 3.0

### ISSUE THREAD

**Issue by kamranayub** [MiniProfiler/dotnet#107]
Need to update RavenDB support for 3.0. Maybe just as separate project (MiniProfiler.RavenDb30) since it was a major upgrade.

**Comment by carlosagsmendes** [comment]
@kamranayub do you confirm that the current version doesn't support RavenDB 3?

**Comment by kamranayub** [comment]
Yes, I have it running with 3.0 and I get no output.

**Comment by carlosagsmendes** [comment]
Thank you for the heads up. +1

**Comment by yellis** [comment]
Closing this issue as it seems that the question was answered. If you want to provide a PR for Raven 3, I would be happy to include it.

**Comment by kamranayub** [comment]
So the main issue is in 3.0 something changed where the `LogRequest` event doesn't appear to have any `HttpContext.Current` (possibly due to some async context), so `MiniProfiler.Current` is always null. Otherwise this would work if I can access the current HttpContext from the event handler. I'm not sure how yet.

**Comment by kamranayub** [comment]
I've fixed it for 3.0 and it's backwards compatible with 2.5. I am issuing a PR.
