### ISSUE TITLE
Support MongoDB dotnet client 2.0

### ISSUE THREAD

**Issue by lxalln** [MiniProfiler/dotnet#110]
On the 1st April 2015, the MongoDB client library was updated to [version 2.0](https://github.com/mongodb/mongo-csharp-driver/releases/tag/v2.0.0), this brought quite a few breaking changes, including breaking MiniProfiler support.

Are there any plans for supporting the new MongoDB client library?

**Comment by CasperTDK** [comment]
+1

**Comment by yellis** [comment]
We have no plans to add support for the new MongoDB library. The MongoDB package has up to this point been 100% user-supported. We don't use MongoDB at Stack Exchange and are just publishing the package as a courtesy for users. So if anyone would like to send a PR to support the new version, I would be happy to accept and publish the new package.

**Comment by YJingLee** [comment]
+1

**Comment by aramacciotti** [comment]
+1
