### ISSUE TITLE
SQL Server storage growth...

### ISSUE THREAD

**Issue by dazbradbury** [MiniProfiler/dotnet#112]
Hi Guys,

I use MiniProfiler over at OpenRent quite a bit (it's great!) - however I've noticed the table growth is quite substantial. Looks like about 3 months of timings are being kept in the DB.

Generally, I'm just using it on the fly, so anything over 24 hours is probably not needed. I can clear the DB manually, but before I start doing that programatically, is there a setting to define data retention settings? 

I've had a look through the code, but can't see anything glaringly obvious. Also checked what was settable here:

```casharp
StackExchange.Profiling.MiniProfiler.Settings
```

But no luck. Is there a setting somewhere?

Reason for the concern is that:

a) it slows down queries to lookup results (1m rows+)
b) puts unneccessery pressure on our DB (although I could put it in a different DB I guess!)

Thanks!

**Comment by yellis** [comment]
No, there is no setting in the `SqlServerStorage` implementation to delete old records. All it does is set the records to be `HasUserViewed = 1` after it is displayed. I agree that it would be a good thing to cull the records from time to time, but this is something that you would have to implement on your own.

**Comment by dazbradbury** [comment]
OK - With my db table having over 2m records, and taking up 500mb+, can't imagine I'm the only one with this concern. Will set up a background job to clean it up on a regular basis - but do think it makes more sense for miniprofiler to handle directly, perhaps on initiation. Thanks!

**Comment by yellis** [comment]
I agree that it would be good. However, `IStorage` has no hook in to app init - it is just called when saving/retrieving MP records. So I don't think that adding in an interface-level method for doing something like this is going to happen (especially considering that in some storage implementations it may be totally irrelevant). 

If you would like to send in a PR that just adds a method to do this into `SqlServerStorage`, that you can then call on application init (and others can reuse), I can see including that. (Such a method should also include a property on `SqlServerStorage` to set the age at which to delete records, and whether or not unviewed records should be deleted).
