### ISSUE TITLE
`IsTrivial` impl in `Timing`

### ISSUE THREAD

**Issue by wqweto** [MiniProfiler/dotnet#114]
Currently it checks if `DurationWithoutChildrenMilliseconds` is below a certain threshold. Can this be altered to use the whole `DurationMilliseconds` instead?

Here is the use-case I'm facing. Notice this collapsed view on profiling

![Confusion w/o trivials](https://dl.unicontsoft.com/upload/pix/ss_mini_1.png)

It seems that the partial view tool 3.2 ms _including_ children but then each of the children took longer! WTF?!

Mystery explained when trivials shown

![Expanded](https://dl.unicontsoft.com/upload/pix/ss_mini_2.png)

There is a hidden parent `Controller: HomeController._HeaderFunctionali...` that's been marked trivial as being timed below 2 ms _without_ children. 

Is there some kind of special purpose for using `DurationWithoutChildrenMilliseconds` that I'm missing here?

**Comment by NickCraver** [comment]
I'll look at this in the port. It seems like a legit change, and this has bugged me before too.

Sorry we haven't given MP a lot of love, it's one of many projects in play right now.

**Comment by wqweto** [comment]
np.

I would have fixed it myself in a PR if I was brave enough :-))

**Comment by NickCraver** [comment]
I've made this change in the v4 branch, it'll be in 4.0 :)

**Comment by NickCraver** [comment]
Closing this out so I can track everything - this will land in a 4.0 alpha in the next few weeks.
