### ISSUE TITLE
Add configuration option to include class names in stack trace snippet

### ISSUE THREAD

**Issue by guillaume86** [MiniProfiler/dotnet#115]
When logging methods belonging to a common base class or interface, the class name can help a lot (ex: If you have a rule engine with interface `IRule { void Execute() }`, you currently only know you are in a Execute method, but can't know on which rule implementation from the stack info).

I took a look at the source and it looks like it could use a `Func<MethodInfo, bool> IncludeClassName` option and use it in here:

https://github.com/MiniProfiler/dotnet/blob/master/StackExchange.Profiling/Helpers/StackTraceSnippet.cs#L46

Does it seems reasonable?

**Comment by NickCraver** [comment]
This seems *really* specific, so a `MethodInfo` taking version seems very brittle. Can you please give some example layouts where you'd find this handy? That will help us figure out what works a bit better.

**Comment by guillaume86** [comment]
Hi, I'm going to close this, I havn't though about it in a long time, which probably means I don't really need it, thanks.
