### ISSUE TITLE
MiniProfiler includes.js resources does not load entirely

### ISSUE THREAD

**Issue by junalmeida** [MiniProfiler/dotnet#119]
I have updated from version 2 to latest version 3 and now includes.js seems not to be loading the entire script. The script is cut in the middle of prettify.js, at line 1089, col 468:

```
... else if(/[a-z]/i.test(t.source.replace(/
```

This causes javascript error and nothing is shown on the ui.

**Comment by TomWij** [comment]
Reproduced in at least 3.2.0.157 and 3.1.1.140 and 3.0.12.

**Comment by NickCraver** [comment]
I haven't been able to reproduce this - do you have an exact file size of the chunk that does get through? I bet a buffer somewhere is truncating the file on the way out, e.g. at 8K, 16K, something like that.
