### ISSUE TITLE
Support MongoDB.Driver 2.0

### ISSUE THREAD

**Issue by blyry** [MiniProfiler/dotnet#125]
The current mongo package is  based on 1.8, 2.0 was a breaking rewrite.

I have this mostly done at https://github.com/blyry/dotnet/tree/Mongo2

My commits need a bunch of cleanup for a clean merge request, but I have mostly everything implemented -- linq queries with AsQueryable() are profiled with customtimings, we can get basic `step` profiling for the native mongo query methods, and there's a compatible storage provider.

**Comment by paolobriones** [comment]
any updates on when this will be released?

**Comment by NickCraver** [comment]
I'm working hard on a 2.x release now on the new tooling - the MongoDB stuff is crazy though. I'd absolutely *love* a PR against the `csprojfun` branch is blyry is willing. I have no idea what I'm doing profiling MongoDB and it's a huge unknown, but you'll need VS 2017 RC to even compile and build right now...and that's a big ask of the community.

@blyry if you're willing, holy crap I'd appreciate it. I took a look at the MongoDB profiler with the new driver yesterday and closed it. I'm *almost* there on all the other bits - then aiming at `netstandard`/ASP.NET Core support overall. Someone who knows Mongo much better taking that piece would be oh so incredibly welcome.

**Comment by blyry** [comment]
Yeah absolutely, I could get back to it this weekend. We've been running it in production for almost 10 months now and it's stable, but with some warts. There's 3 major components, `Storage`,  `ProfiledMongoCollection` and `MongoProfiledQueryable`

The major problem with my branch right now is that `MongoDB.Driver` had all of it's internals set to `internal sealed` with no hooks for an actual profiler. I need to check the latest driver and see if anything has changed there. So my bits just wrapped IQueryable and IMongoCollection. Not ideal but it's worked so far!

We need to
* investigate current mongo driver version and see what's changed in the last year
* rewrite the storage driver so it's more idiomatic and document-store-ey
* add test coverage for `MongoProfiledQueryable`, and implement more features (well, the features that the mongo driver implements!)
* make the saved query match between the two profiled providers.

@NickCraver what's with the vs.code commit on the `csprojfun` branch? Are we developing in that AND 2017?

**Comment by blyry** [comment]
I gotta take a look at claude-uceda:moncsharpdriver2.2 too

**Comment by NickCraver** [comment]
@blyry I'm working on the `csprojfun`/VS 2017 RC branch yes, but if that's too crazy (not everything runs well yet, I'm only ~16 hours in) I'd happily merge from another branch over. It definitely wasn't my intent to drag along any other victims into the new `.csproj` world while I tested it on real-world scenarios to provide feedback and improvement ideas to Microsoft.

I'm very close to having things compile with a `net45` chain (and a `netstandard1.5` .Shared library) already, but firing up test and sample apps is next. I may be close to running...or close to a minefield. I should know more tonight or tomorrow.

**Comment by blyry** [comment]
Alrighty. I'll focus on cleaning up the code, getting nuget packages out for the current version and then start upgrading to match the csprojfun branch and looking at netstandard. My link up top isn't quite accurate anymore, I ended up pushing a lot of changes to https://github.com/Spreetail/dotnet.

**Comment by NickCraver** [comment]
@blyry heads up: I moved the branch to v4 and final library/path will be `MiniProfiler.Providers.MongoDB` (new packages all around). I didn't move the files in an effort to not cause you any pain. If that'd be better to do ASAP let me know and I'll shuffle. My read is the profile provider at least is so far off the mark we might as well delete it. Or 2.x isn't as big of a breaking change as I'm perceiving it to be based on compile errors :)

Let me know how I can help - I've put up #144 to track v4 progress, and I appreciate your help!

**Comment by blyry** [comment]
Hokay -- I have some time to work on this! 

- [ ] rewrite my branch so that mongo storage is more idiomatic, tidy up for a MR.
- [ ] Merge into v3 branch as a final release w/ nuget package for `MiniProfiler.MongoDb.Driver` that targets 3.2.0.157 and `mongodb.drive.core` 2.4.0
- [ ] migrate to netstandard, nuget and netcore magic
- [ ] ??? profit??

**Comment by NickCraver** [comment]
@blyry The v3 branch is the old code that may never get updated - work against master which is v4 :)

**Comment by NickCraver** [comment]
Closing this out since there appears to be no interest in it. If it arises one day, we can add it in.
