### ISSUE TITLE
MiniProfiler EF6 and batch queries

### ISSUE THREAD

**Issue by StuffOfInterest** [MiniProfiler/dotnet#130]
I've been trying to get MiniProfiler to play nicely with two different query batching tool's "future" query support.  Both EntityFramework.Extended and EntityFramework-Plus have methods for adding "Future()" to a query and then executing several queries together when the first one is enumerated.  This is a feature which has native support in NHibernate.  Both products work but neither is showing the batched queries in MiniProfiler's output.  With NHibernate the matched queries are displayed in MiniProfiler's output.

Best I've been able to figure out, it appears that EF is being served a non-profiled SQL connection for batch operations.  Is there a way to make EF use profiled connections for these other operations?

**Comment by NickCraver** [comment]
Can you link me to how NHibernate does this? I'm not tremendously familiar with this, but their approach may show some insight.

**Comment by StuffOfInterest** [comment]
I'm afraid I don't have much insight into how NHibernate did it.  Being that the setup of NHibernate is quite a bit different than Entity Framework, I'm not sure there is too much common process you can draw on.

When I was playing around with this myself I did run into something regarding MiniProfiler and Entity Framework that may be of use.  The function used to spin up a connection and a command for the batch queries in EF utilize a connection factory.  MiniProfiler injects wrapped connections into the DbContext, but it does not use the factory facility.  Because of this the connections used for the batch commands never get wrapped for profiling.  If you could implement a connection factory for EF which hands out wrapped connection, this may take care of the issue.

It was several months ago when I looked into this so my details may be a bit off.  Hopefully, this give you  or someone else a place to look.

Thanks.

**Comment by NickCraver** [comment]
This should be in the next release via #189.
