### ISSUE TITLE
stack trace snippets are not html-escaped

### ISSUE THREAD

**Issue by fsateler** [MiniProfiler/dotnet#136]
On a project of mine I frequently run into stack trace snippets that end up like this:

```
<.ctor>b__45_0 <Select>b__0 HandleImpl Query
```

The problem is that this is then rendered in the ui as follows:

![image](https://cloud.githubusercontent.com/assets/1322013/16592884/bfc3054c-42b0-11e6-8906-4637b1938b0f.png)

That includes the sql (ie, it is eaten by the select tag). Not sure if this is a bug in the ui or here, but requesting the results url via the browser results in the same problem so I'm filing here.

**Comment by yellis** [comment]
this was fixed in [this commit](https://github.com/MiniProfiler/ui/commit/35d690c54954dc6cebefeef898b7684e41949cfb) to the UI project
