### ISSUE TITLE
Integration with swashbuckle/swagger

### ISSUE THREAD

**Issue by laskoviymishka** [MiniProfiler/dotnet#137]
It would be nice to have an ability for review API performance from swagger sandbox.

**Comment by NickCraver** [comment]
This would be a plugin model, if someone wants to contribute such a thing. Unfortunately, in-the-box integration would, AFAIK, require a dependency we wouldn't want for the vast majority of users.

**Comment by laskoviymishka** [comment]
Fair enough.
