### ISSUE TITLE
MaxJsonLength when serialising custom timings to SqlStorage

### ISSUE THREAD

**Issue by SYoungPB** [MiniProfiler/dotnet#138]
When custom timings are being saved using `SqlServerStorage` a new `JavaScriptSerializer` object is created by `StackExchange.Profiling.Helpers.ExtensionMethods.ToJson()` which has the default `MaxJsonLength`. This can cause an unhandled exception when the CustomTimings exceeds this value, with no way to change MaxJsonLength.

**Comment by NickCraver** [comment]
Fixed for v4, expect an alpha in the next few weeks. I may get a `net45` alpha up sooner.
