### ISSUE TITLE
/mini-profiler-resources/results returns 404 on server

### ISSUE THREAD

**Issue by kmc059000** [MiniProfiler/dotnet#139]
Miniprofiler works correctly when running locally. However when running on a server, it does not render at all. Looking at the network requests, it is  attempting to render miniprofiler, but the GET to /mini-profiler-resources/results returns a 404. 

I have attempted to add the following to the web.config with no luck, even though I have `runAllManagedModulesForAllRequests=true`

```xml
<add name="MiniProfiler" path="mini-profiler-resources/*" verb="*" type="System.Web.Routing.UrlRoutingModule" resourceType="Unspecified" preCondition="integratedMode" />
```

If I open the site on the server it is hosted from using its IP address, miniprofiler does appear. We have multiple domains for the same site. So I know that miniprofiler CAN work from on this server.

If I make a request to /mini-profiler-resources/results myself through the browser (not through ajax, but by typing the address into my address bar), using any of the domains that the site uses, I get a 200 result. However it is the most recent profiling result from the request that was last made from the server itself. It never changes if I access the site from any other domain. It appears that it is only profiling local requests. In fact, the URL that the page displays is the URL using the IP address, and not any of the domains we use.

In `Application_BeginRequest()`, we have custom logic for determining whether to start miniprofiler for the request:

```c#
if((Request.IsLocal || someConditionThatIsTrue1) && someConditionThatIsTrue2))
{
    MiniProfiler.Start();
}
```

`someConditionThatIsTrue1` and `someConditionThatIsTrue2` are both true in my case.

I have tested, and I know that MiniProfiler.Start() is being called because the statement in the if statement is evaluating to true. Plus I've seen it work when using the IP address.

What can we do to get miniprofiler to display in this environment?

**Comment by NickCraver** [comment]
Is your site behind a load balancer? What request host is IIS actually seeing on these requests?

**Comment by NickCraver** [comment]
Any more info here? Need some more to go on - see comment above.

**Comment by kmc059000** [comment]
I am not using a load balancer. IIS should be getting the host that the client is requesting (our .com). We have a vanilla IIS setup. I can dig further in to determine the host that MVC/IIS is receiving for these requests if you think that might be the source (it takes a bit of work to make that happen).

I've turned off custom errors, and the the AJAX request gets a 404 when requested using the domain name or public IP. When using the internal IP, I get a 200. When using the internal IP address, there 8 successful requests into miniprofiler. When using the public domain or public IP, there is only one request which results in a 404

![image](https://cloud.githubusercontent.com/assets/660670/23096472/a6be988c-f5e2-11e6-9593-55c02bf02af6.png)

The Form Data of the request that uses the domain name or external IP address is the following:
![image](https://cloud.githubusercontent.com/assets/660670/23096581/23c228b0-f5e5-11e6-8782-d0fea9b40a86.png)

And this is a request which uses the server's internal IP address. However, in both cases, the `id` parameter is being sent. The difference in data does not appear to be a problem though because one of the eight requests using the internal IP has the same form data as the external request (different values but same fields).

![image](https://cloud.githubusercontent.com/assets/660670/23096621/d3e70e9a-f5e5-11e6-8d4c-caf5f7046591.png)

In IIS, the site has a single binding using the internal IP address and does not have any bindings that use the external IP or the host names. This is the only thing that makes the internal IP unique. We have another server that has bindings which use the host name, and it behaves the same. I cannot think of anything else that makes the internal IP address special, unless miniprofiler takes it into consideration.

It might be helpful to change `MiniProfileHandler.Results` to return the error message when `isPopup` is true. I might try that in the next few days to try to determine where exactly it is returning the 404.

Let me know what else I can provide. I'm going to dig a bit more into this in the next few days now that I understand it a bit more than I did before.

**Comment by NickCraver** [comment]
What type of storage are you using? It seems like it's trying to fetch a MiniProfiler result that's already been thrown away.

**Comment by kmc059000** [comment]
I don't think that is the case because the fetches successfully when
connecting using the IP address.

It is using the default storage, we haven't specifically configured
storage. I'm guessing this means it is using in-memory storage.

**Comment by NickCraver** [comment]
Do you have a proxy involved? This would happen (with defaults) if all users had the same UserId (IP, by default) which would be the proxy if it wasn't sending Forwarded-For headers appropriately. Is there a proxy? If so, can you provide details?

**Comment by NickCraver** [comment]
Any update here?

**Comment by NickCraver** [comment]
Given this has changed drastically and I'm hoping to get v4 in RTM in the next week or two, closing this out.
