### ISSUE TITLE
Hide MiniProfiler if the page is quick

### ISSUE THREAD

**Issue by Myster** [MiniProfiler/dotnet#142]
I would like miniprofiler to conditionally show based on a certain threshold, so if the page is quick it does not show.

**Comment by NickCraver** [comment]
Can you give some examples here? I have trouble picturing this as useful for a *global* setting, e.g. a static page taking 30ms is still indicative of a problem. It seems like you'd need routes or other differentiating deterministic characteristics to trigger specific thresholds off of...which means a mighty unwieldy config scenario.

Some use cases may help though, can you please elaborate?

**Comment by Myster** [comment]
Good points. 😃 
In my scenario I am working with a CMS, and most pages have similar load times. I want it to show all the time, but I am trying to appease co-workers who don't want to see it... But probably need to if they just introduced a perf issue.
All this is just thinking out loud, so take it with a grain of salt 😉

**Comment by AkosLukacs** [comment]
@Myster set `MiniProfiler.Settings.PopupStartHidden = true;` for your coworkers :) Maybe add some config / profile setting in your app to show or hide it by default.

**Comment by NickCraver** [comment]
I'm going to close this out because I don't think it's a feature many would use. However, it's still totally possible to do it yourself in the render call. Here's a short example:

```
@MiniProfiler.Current.RenderIncludes(startHidden: MiniProfiler.Current.DurationMilliseconds > myMinValue)
```
