### ISSUE TITLE
Profiler shows old data from previous requests

### ISSUE THREAD

**Issue by AlexPhilippov** [MiniProfiler/dotnet#145]
After working with profiler on production-like environment we sometimes get following problems:
1. Lots of 404 from /mini-profiler-resources/results
2. Profiler entries appears for requests, that is loaded from browser cache (async loading for scripts, stylesheets, etc.)

After some digging, I discovered that the reason for that - header X-MiniProfiler-Id in cached responses. Since ids are saved in HttpRuntime.Cache, they can be lost after app pool restart, but some responses can still be cached in browser - they provide old ids, MiniProfilerHandler returns 404.
2nd problem is more troubling, you just reload page with client cache enabled and all cached responses load all ids from X-MiniProfiler-Id header to the current page. It really confuses when you work on performance and see profile entries that shouldn't be there.

I think you can fix behavior without workarounds if for isPopup requests in mini-profiler-resources/results MiniProfilerHandler will return empty result for already viewed enteries.

Seems like there is already discussion about the same problem in [Ruby](https://github.com/MiniProfiler/rack-mini-profiler/issues/127), and there is already some fixes for that.
If there it's already fixed it would be great to have the same for MiniProfiler.MVC

**Comment by NickCraver** [comment]
@AlexPhilippov this is already the case - IDs are marked as viewed as you view them and they don't re-render. It seems like you'd got the header jammed in OutputCache somewhere, but I'm not sure how. As for the RuntimeCache...that's configurable. The default does behave correctly, but you've very likely got some cache in play *after* that piece of the pipe. You can override any bits of the caching (or provide an entirely new provider) if you wish though.

Some bits have been tweaked in v4 around the pipeline, do you want to give the alpha a try? They're up on NuGet now, I'd appreciate knowing if this changes your symptoms at all.

**Comment by AlexPhilippov** [comment]
Probably I need to explain our situation a bit.
We're using mini-profiler for requests that provide resources: js, css. And yes, there is some cache involved there, but it's browser's cache, so we can't do anything about it. Each cached request contain mini-profiler header with unviewed ids. And mini-profiler client-code is requesting each of them and generates all this unnecessary 404.
As far as I can see this can be solved in MiniProfilerHandler. Also something like that was done in Ruby, so I was interested in similar fix here.
I will check out alpha, but it's not an option until it would be stable.

**Comment by NickCraver** [comment]
@AlexPhilippov You control browser cache with the `Cache-Control` headers, if you're instructing it to cache the state, then that's what it'll do. The Request IDs are in the `<script>` tag of the page for initial fetch, so if you're re-rendering, then you're again seeing the data that went into that page. That's correct behavior on many fronts, it's *what it took to render that page*. 

It's not a header that's cached (the JavaScript is incapable of reading a header from the current page, only AJAX things it loads). It's literally the `<script>` tag in the page that renders MiniProfiler, they're in a data attribute. If you're caching the page, that'll be in it.

**Comment by NickCraver** [comment]
Happy to revisit this in v4 if there's an issue, but if we're hard-caching on the client it's really outside the MiniProfiler realm, and enforcing clears in the data store isn't desirable behavior for most (e.g. team sharing). This is simply application behavior that's opt-in. An option here is of course to wrap any `IAsyncStorage` and force the clearing, if that's *really* the behavior desired. As a last resort, that's what I'd recommend here.
