### ISSUE TITLE
Integrations: Entity Framework Core

### ISSUE THREAD

**Issue by NickCraver** [MiniProfiler/dotnet#161]
Originating in #130, need to see how Entity Framework Core works, likely create `MiniProfiler.EntityFrameworkCore` (or `MiniProfiler.Providers.EntityFrameworkCore`, depending on the integration) and get a sample in.

- [x] Investigate Entity Framework Core
   - [x] ProfiledDbConnection
   - [x] Events (possible they have profiling hooks already)
- [x] (If needed) Create `MiniProfiler.Providers.EntityFrameworkCore` package
- [x] Add Entity Framework Core to the ASP.NET Core MVC sample

**Comment by NickCraver** [comment]
I'm working with the EF team on best approaches here: https://github.com/aspnet/EntityFramework/issues/7939

**Comment by NickCraver** [comment]
Closing this out, a new package is available for testing: [MiniProfiler.EntityFrameworkCore](https://www.nuget.org/packages/MiniProfiler.EntityFrameworkCore). I welcome issues anyone hits and it'll continue to progress as `System.Diagnostics` does.

**Comment by chadwackerman** [comment]
Works great. And "just works" with ASP.NET Identity (specifically Microsoft.AspNetCore.Identity.EntityFrameworkCore) which was always problematic with MVC in the past.

Inside Startup.Configure I had some database access. Initialization isn't fully complete yet (I believe MiniProfiler.Current isn't set) and it throws an exception in RelationalDiagnosticListener.cs/OnBeforeExecuteCommand.

Moving the database calls above app.UseMiniProfiler(...) is a workaround.

**Comment by NickCraver** [comment]
@chadwackerman Doh, I'm stupid...not sure why I made that throw. Next build will include adbdca296788002f023d1154e7dc61af95649c2a to fix that bad behavior.

**Comment by chadwackerman** [comment]
I believe I'm seeing a variation of this on alpha8-165.

Program.cs:

```
public static async Task Main(string[] args)
{
    var host = BuildWebHost(args);

    using (var scope = host.Services.CreateScope())
    {
        var services = scope.ServiceProvider;
        var db = services.GetRequiredService<ApplicationDbContext>();
        var foo = db.Whatever.FirstOrDefault(); // throws
    }

    host.Run();
}

public static IWebHost BuildWebHost(string[] args)
{
    return WebHost.CreateDefaultBuilder(args)
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();
}
```

If I remove .AddEntityFramework() from the services.AddMiniProfiler() call in Startup.cs, it works.

**Comment by NickCraver** [comment]
What error does it throw?

**Comment by chadwackerman** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at StackExchange.Profiling.Data.RelationalDiagnosticListener.OnNext(KeyValuePair 2 kv) in C:\projects\dotnet\src\MiniProfiler.EntityFrameworkCore\RelationalDiagnosticListener.cs:line 114
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.ConnectionOpened(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DateTimeOffset startTime, TimeSpan duration, Boolean async)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__34.MoveNext()

**Comment by chadwackerman** [comment]
Fixed on alpha9-202

**Comment by NickCraver** [comment]
Closing this out to clean up :)
