### ISSUE TITLE
/mini-profiler-resources/results step descriptions are not html encoded

### ISSUE THREAD

**Issue by phillijw** [MiniProfiler/dotnet#163]
`
MiniProfiler.Current.Step("A<Something>")
`

This step will be displayed as "A" in the table and the greater than and less than characters are converted directly to html rather than encoded on the results page.

**Comment by NickCraver** [comment]
Is this in v3 or v4? In the v4 alpha I changed the templating reason exactly for reasons like this one - also slims down and simplifies the JavaScript a bit.

**Comment by phillijw** [comment]
This is for current (3.2.0.157)

**Comment by NickCraver** [comment]
@phillijw If you get a chance, you'll want to try the v4 release which has a lot of changes there (it's alpha on NuGet but I'll be deploying it to our production this week for heavy testing)...that's a pretty severe change to backport but I'll take a look when time allows.

**Comment by phillijw** [comment]
I will probably switch to v4 but wanted to make an issue because I didn't
see one when I searched. :)

**Comment by NickCraver** [comment]
This is fixed in V4, no plans to do another v3 release due to significant tooling burden, focusing on making the upgrade both very appealing and as painless as we reasonably can.
