### ISSUE TITLE
EF6 Profiling Broken (v4)

### ISSUE THREAD

**Issue by jdaigle** [MiniProfiler/dotnet#169]
SQL commands are not correctly profiled after the first instance of the command is executed.

I believe 2cc5e7eed5fbdc12fb1adf7ff40c introduced the breaking change. It seems that EF6 never creates a `ProfiledDbConnection`. So the `Connection` property on `ProfiledDbCommand` is always passed a "real" `DbConnection`.

I guess EF6 caches `DbCommand` instances and relies on `Clone()` (removed, then added back 5bb51c7d5187da31da0478c9ebd1c8128ca5c73b). So the `_profiler` reference is always whatever it was the first time the command was created (may or may not be null). EF6 then sets the `Connection` property on the cloned instance.

The fix _might_ be as simple as changing `Clone()` so that it passes `MiniProfiler.Current` instead of `_profiler`. That seems to the be the earliest/only other place to inject the current `MiniProfiler` instance (see call stacks).

I'll offer to work on a pull request if you think the fix is okay.

![image](https://cloud.githubusercontent.com/assets/104650/24592377/51f47baa-17e3-11e7-827a-c7cba866b839.png)
![image](https://cloud.githubusercontent.com/assets/104650/24592389/7aa1e9fc-17e3-11e7-97b8-9c97b1fc3777.png)

**Comment by NickCraver** [comment]
Thanks for the issue and assessment! I agree it's the `_profiler` reference - I just updated `.Clone()` to pass it in, since EF6 is its only purpose in life. I'll try and get a few more fixes in, versioning updated, and a new release on NuGet. MyGet should have the fixes shortly.

Leaving open until you can confirm the fix - sample apps are looking better here.

**Comment by jdaigle** [comment]
@NickCraver related but slightly off-topic question: do you do anything special to get `Samples.Mvc5` to run in IIS Express from Visual Studio? Anytime I try to launch it (with debugger or not), I always get an error message: "Unable to run your project. The "RunCommand" property is not defined.". Probably has something to do with it being the new "Microsoft.NET.Sdk.Web" style csproj.

**Comment by NickCraver** [comment]
@jdaigle I'm running it on IIS locally at `local.mp.com` - I've reached out to the MS folks to see if there's any workaround for inside VS at the moment.

**Comment by jdaigle** [comment]
Confirmed that it's fixed in 4.0.0-alpha6-52
