### ISSUE TITLE
Cannot ignore paths that must match path info after a "file extension"

### ISSUE THREAD

**Issue by jdaigle** [MiniProfiler/dotnet#171]
ASP.NET Web Services can expose JavaScript resources through paths such as `/MyWebService.asmx/js`. I want to be able to profile requests for operations on that web service (e.g. `/MyWebService.asmx/Foo`) but I want to ignore the dynamic JavaScript resources.

I want to be able to include `".asmx/js"` in `MiniProfilerWebSettings.IgnoredPaths`, but this doesn't work. `WebRequestProfilerProvider` only compares ignored paths against `HttpRequest. AppRelativeCurrentExecutionFilePath`, which only contains the path up through the "file extension".

It should work to change the logic to compare against `HttpRequest.Path`, but this is a breaking change (particularly for anyone that hosts from a virtual directory). Thoughts?

**Comment by NickCraver** [comment]
I think there are workarounds for this, e.g. getting the relative ~/ path and trimming off from the actual, though that's a string allocation each time. I think we can do this without breaking people. And 4.0 is also legit for reasonable breaking changes...but we should aim for expected behavior overall here.

Would need a lot of tests (or one with a lot of inputs)...unsure of the best way to simulate the requests, though.

**Comment by jdaigle** [comment]
It seems like you could pass `HttpRequest.Path` into `VirtualPathUtility.ToAppRelative()` and get back the app relative path that includes stuff after the "file path".

Though, poking around the reference source code, `ToAppRelative()` ends up creating a new `VirtualPath` object (an internal class). That internal class ends up calling into `UrlPath.MakeVirtualPathAppRelative()` (another internal class) which does the magic string substitution. So that's probably expensive. Annoying `HttpRequest` already the `VirtualPath` cached, you just can't get to it or anything that calls `MakeVirtualPathAppRelative()` on the _whole_ virtual path.

But it turns out that `AppRelativeCurrentExecutionFilePath` _always calls_ `UrlPath.MakeVirtualPathAppRelative()`. So we could probably implement our own version of `UrlPath.MakeVirtualPathAppRelative()` that's not really any worse than calling `AppRelativeCurrentExecutionFilePath`. And _that_ method could be unit tested.
