### ISSUE TITLE
MiniProfiler.EF6 incompatible with custom DbProviderServices implementation

### ISSUE THREAD

**Issue by nphmuller** [MiniProfiler/dotnet#175]
I'm currently trying out MiniProfiler.AspNetCore.Mvc with MiniProfiler.EF6. Both on v4.0.0-alpha6-52.

When configuring MiniProfiler.EF6 I run into an issue. We use a custom DbProviderServices implementation (CachingProviderServices from the EFCache project), which makes the constructor of EFProfiledDbProviderServices throw.

It seems the constructor looks for the Instance property through reflection, which doesn't exist in the DbProviderServices class, but does exist in the default implementation used by EF (SqlProviderServices).

The following snippet throws the exception:
`Unable to define EFProfiledDbProviderServices class of type 'CachingProviderServices'. Please check that your web.config defines a <DbProviderFactories> section underneath <system.data>.`
``` c#
        public static void Main(string[] args)
        {
            // Setup EFCache  
            DbConfiguration.Loaded +=
                (sender, args) => args.ReplaceService<DbProviderServices>(
                    (dbServices, _) => new CachingProviderServices(dbServices, transactionHandler, cachingPolicy));
            DbInterception.Add(transactionHandler);

            // Setup MiniProfiler.EF6
            MiniProfilerEF6.Initialize();

            // This line throws the exception.
            new DbContext(GetConnectionString())
                .Initialize(false);
        }
```

A workaround could be implemented by creating an overload for MiniProfilerEF6.Initialize() which accepts the SqlProviderServices instance. The user can call this overload from the DbConfiguration.Loaded event, just like CachingProviderServices in the sample above.

Of course this makes it harder to use than the current call to Initialize (which is probably sufficient for 90% of the users?), but those users can of course just use the no parameters variant, which already exists.

**Comment by NickCraver** [comment]
Hmm, I wonder if it's the `readonly` optimization there that makes it angry - looking.

**Comment by NickCraver** [comment]
@nphmuller GitHub auto-closed this, but can you please test the latest? 4.0.0-alpha6-79 libraries are up on NuGet and hopefully resolve the issue you were hitting with the old Entity Framework 6 code.

**Comment by nphmuller** [comment]
@NickCraver Issue seems fixed.  Thanks!

I now run into the next blocker though, which I'll try to understand a bit better before creating a new issue. Not even sure yet if the issue would belong here, or at the EFCache repo.
Short summary: ProfiledDbCommand implements ICloneable while CachingCommand (the DbCommand implementation of the caching lib) does not. So ProfiledDbCommand throws on Clone()

**Comment by NickCraver** [comment]
@nphmuller I looked into this and I'm honestly baffled how their version works without clone since it's something EF expects. Can you open an issue there for the author's thoughts? It's entirely possible this is something MP can fix...but I don't understand how they *aren't* hitting a problem. Maybe it's just a matter of it being cached in the first place so the clone never happens. It's just fundamentally an issue they can't hit and may not even be aware of (it's an odd behavior by EF, IMO).

**Comment by nphmuller** [comment]
Everything's working fine now. EFCache implemented ICloneable.
