### ISSUE TITLE
Ability to reuse timing step

### ISSUE THREAD

**Issue by rlenders** [MiniProfiler/dotnet#178]
I have something like the following:

    for (var i = 0; i < 1000; i++) {
        using (profiler.Step("Part A")) {
            // ~10 ms
        }
        using (profiler.Step("Part B")) {
            // ~40 ms
        }
        using (profiler.Step("Part C")) {
            // ~15 ms
        }
    }

This will result in 3000 timings. I'm looking for a way to rewrite this so MiniProfiler ends up with only 3 timings, one that contains the total ms of Part A, one that contains the total ms of Part B, and one that contains the total ms of Part C.

Thanks!

**Comment by rlenders** [comment]
[This](http://stackoverflow.com/questions/9757591/mvc-mini-profiler-manually-adding-step) helped me out.

**Comment by johnrom** [comment]
Can we reopen this? I have the same question, but I don't think the answer is to re-implement internal code.
