### ISSUE TITLE
includes.js not found (404) with MiniProfiler v4

### ISSUE THREAD

**Issue by rlenders** [MiniProfiler/dotnet#179]
After switching to MiniProfiler v4 I no longer can get it to correctly render the js includes. I had to change `MiniProfiler.RenderIncludes()` to `MiniProfiler.Current.RenderIncludes()`, maybe that's a clue that will help figuring out my problem. Thanks!

**Comment by rlenders** [comment]
This handler in my web.config is probably relevant to this issue:

    <add name="MiniProfiler" path="mini-profiler-resources/*"
         verb="*" type="System.Web.Routing.UrlRoutingModule"
         resourceType="Unspecified" preCondition="integratedMode" />

**Comment by rlenders** [comment]
I was missing `MiniProfilerHandler.RegisterRoutes();`. Is this documented anywhere? I still haven't gotten v4 working correctly, I'll open another issue.

**Comment by rlenders** [comment]
Instead of `MiniProfilerHandler.RegisterRoutes();` I am now using `MiniProfiler.Settings.ProfilerProvider = new WebRequestProfilerProvider();`, which seems to be the recommended way of solving this (the MVC 5 sample does this).

**Comment by tomascassidy** [comment]
In addition to using the new `WebRequestProfilerProvider.Setup()` method, I had to add this to `Web.config`.  It's not documented anywhere and is not added automatically by the NuGet package.

```xml 
<add name="MiniProfiler"
     path="profiler/*"
     verb="*"
     type="System.Web.Routing.UrlRoutingModule"
     resourceType="Unspecified"
     preCondition="integratedMode" />
```

**Comment by rlenders** [comment]
That actually **is** documented on MiniProfiler's site

**Comment by lorenpaulsen** [comment]
Alternatively, you can include the following, which is how the sample does it:

```xml
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
  </system.webServer>
```

Otherwise I think that you would also have to keep `path="profiler/*"` in `web.config` in sync with `RouteBasePath = "~/profiler"` in `global.asax`.
