### ISSUE TITLE
v4: Missing documentation on MiniProfiler v4

### ISSUE THREAD

**Issue by rlenders** [MiniProfiler/dotnet#180]
MiniProfiler v4 introduces some breaking changes. For example, MVC applications now require `MiniProfiler.Settings.ProfilerProvider = new WebRequestProfilerProvider();`. So far there is almost no information on upgrading from v3 to v4.

**Comment by rlenders** [comment]
The samples help a bit but the MVC5 sample is a class library, without any documentation I'm having a hard time finding out how to run it.

**Comment by NickCraver** [comment]
It's by no means done, but I've got a start on documentation here: http://miniprofiler.com/dotnet/, specifically including an upgrading from V3 section here: http://miniprofiler.com/dotnet/HowTo/UpgradeFromV3

Once I go through a few conversions I'll update this to include more things users will hit.

**Comment by NickCraver** [comment]
Closing this out - I'll keep docs updated with breaks as we go from here out.
