### ISSUE TITLE
v4: MemoryCacheStorage is no longer the default storage provider

### ISSUE THREAD

**Issue by rlenders** [MiniProfiler/dotnet#183]
While doing some testing for #181 I came to the conclusion that setting `MiniProfiler.Settings.Storage` is now required. If you don't set it, you'll end up having an invalid configuration that leads to client-side errors.

It should default to `MemoryCacheStorage` like older versions of MiniProfiler. That, or documentation should be provided that this option is required.

**Comment by NickCraver** [comment]
This will happen in the next build - defaulting to 30 minutes of storage. Thanks!
