### ISSUE TITLE
Can't run Samples.Mvc5 because it's a class library

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#184]
Title says it all, Samples.Mvc5 is a class library, it does not have a Program.cs with a static Main entry point. How do I run this sample?

**Comment by jdaigle** [comment]
Technically it's an ASP.NET application (i.e. ASP.NET 4.x, which requires IIS). But the project is using the new .NET SDK project schema which doesn't correctly support launching IIS or IISExpress for ASP.NET 4.x applications from within Visual Studio.

The workaround is to manually create an IIS site and point it at the source directory.

**Comment by NickCraver** [comment]
Yep - nothing we can do here, unfortunately. I hope the .NET guys will add support back in VS 2017 soon.

cc @davkean - any idea if there's a timeline for MVC5 support in new `.csproj`, or if it's been cut?

**Comment by NickCraver** [comment]
I have opened up https://github.com/dotnet/project-system/issues/2670 in hopes they'll add the functionality to handle all cases like this.

**Comment by Daniel15** [comment]
The way I handle this in one of my projects (ReactJS.NET) is that the MVC 5 sample uses the "old style" .csproj, while every other project uses the new-style ones. It works fine.

**Comment by NickCraver** [comment]
While not a long-term solution (they need to just add support) a fix for the starting specifically can be found here: https://github.com/aspnet/Home/issues/1978#issuecomment-330894604
