### ISSUE TITLE
v4: Setting RouteBasePath leads to 404 not found

### ISSUE THREAD

**Issue by rlenders** [MiniProfiler/dotnet#185]
In the samples I found `MiniProfiler.Settings.RouteBasePath = "~/profiler";`, but when I try using this, `RenderIncludes` still tries to load from "~/mini-profiler-resources".

**Comment by NickCraver** [comment]
This is due to the ordering - it needs to be called before register routes. I'm going to look at drastically simplifying the setup in V4 given all of the very valid issues filed here. Will factor this in.

**Comment by NickCraver** [comment]
The new method will simply be `WebRequestProfilerProvider.Setup("~/profiler")`, so that the ordering isn't an issue. Documentation is still incoming, I need to carve out a few nights to setup GitHub pages proper and get some decent structure up...then docs.
