### ISSUE TITLE
`Connection Open()`/`Connection OpenAsync()` Marked as Duplicate

### ISSUE THREAD

**Issue by jdaigle** [MiniProfiler/dotnet#194]
I don't necessarily think it's a problem when a single HTTP request happens to make multiple calls to  Open, and so this creates a lot of false-positives in the UI.

Since this is new behavior in v4, I think there are two ways to handle this:

1. Always ignore ExecuteType === "Open"/OpenAsync" when detecting duplicates in the UI.
2. A new setting (`IgnoreDuplicateOpenConnection`?) to conditionally control 1.

Whichever approach we like, I'll throw together a pull request.

**Comment by NickCraver** [comment]
Ah good point! Thinking here: *should* we create it as a dupe *when it's on the same connection*? I could go either way on this. I agree not alerting on dupe for now is best though.

My current thinking is a `HashSet<string>` of ignored ExecuteTypes and we `nameof()` add those (probably change the code to `nameof()` for last arg as well). Thoughts?

**Comment by jdaigle** [comment]
> Thinking here: should we create it as a dupe when it's on the same connection?

On the surface I tend to agree. But I think making it configurable will be best for all. Some libraries/ORMs open/close a connection *per command* by default - but with connection pooling I guess that's not necessary terrible.

> My current thinking is a HashSet<string> of ignored ExecuteTypes

I like it. And that could be passed to the UI as simple JSON string array via a new data attribute?
