### ISSUE TITLE
MiniProfiler.Shared netstandard2.0 Build Issue 

### ISSUE THREAD

**Issue by cspiess** [MiniProfiler/dotnet#195]
I forked the repository and am seeing build errors for MiniProfiler.Shared for netstandard2.0.

**Comment by NickCraver** [comment]
...what are they?

**Comment by cspiess** [comment]
Yeah, sorry, I should know better. doing too many things at once.
I get the same errors in VS2017 RTM (15.2 - 26430.15), Preview 3 and Preview 4 (15.3.0 Preview 4); framework version is 4.6.1586.

Data\ProfiledDbProviderFactory.cs(5,23,5,34): error CS0234: The type or namespace name 'Permissions' does not exist in the namespace 'System.Security' (are you missing an assembly reference?)
Data\ProfiledDbCommand.ICloneable.cs(8,46,8,56): error CS0246: The type or namespace name 'ICloneable' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbCommand.ICloneable.cs(14,16,14,26): error CS0246: The type or namespace name 'ICloneable' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbCommand.ICloneable.cs(14,16,14,26): error CS0538: 'ICloneable' in explicit interface declaration is not an interface
Data\ProfiledDbConnection.cs(187,55,187,67): error CS0234: The type or namespace name 'Transactions' does not exist in the namespace 'System' (are you missing an assembly reference?)
Data\ProfiledDbConnection.cs(181,33,181,47): error CS0115: 'ProfiledDbConnection.CanRaiseEvents': no suitable method found to override
Data\ProfiledDbConnection.cs(187,30,187,47): error CS0115: 'ProfiledDbConnection.EnlistTransaction(Transactions.Transaction)': no suitable method found to override
Data\ProfiledDbConnection.cs(193,35,193,44): error CS0115: 'ProfiledDbConnection.GetSchema()': no suitable method found to override
Data\ProfiledDbConnection.cs(200,35,200,44): error CS0115: 'ProfiledDbConnection.GetSchema(string)': no suitable method found to override
Data\ProfiledDbConnection.cs(208,35,208,44): error CS0115: 'ProfiledDbConnection.GetSchema(string, string[])': no suitable method found to override
Data\ProfiledDbDataAdapter.cs(12,42,12,55): error CS0246: The type or namespace name 'DbDataAdapter' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(25,16,25,30): error CS0246: The type or namespace name 'IDbDataAdapter' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(41,35,41,49): error CS0246: The type or namespace name 'IDbDataAdapter' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(69,43,69,50): error CS0246: The type or namespace name 'DataSet' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(69,60,69,70): error CS0246: The type or namespace name 'SchemaType' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(78,29,78,36): error CS0246: The type or namespace name 'DataSet' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(172,20,172,40): error CS0246: The type or namespace name 'MissingMappingAction' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(183,20,183,39): error CS0246: The type or namespace name 'MissingSchemaAction' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(193,20,193,43): error CS0246: The type or namespace name 'ITableMappingCollection' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataAdapter.cs(33,38,33,52): error CS0246: The type or namespace name 'IDbDataAdapter' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbDataReader.cs(223,30,223,35): error CS0115: 'ProfiledDbDataReader.Close()': no suitable method found to override
Data\ProfiledDbDataReader.cs(233,35,233,49): error CS0115: 'ProfiledDbDataReader.GetSchemaTable()': no suitable method found to override
Data\ProfiledDbProviderFactory.cs(102,25,102,41): error CS0246: The type or namespace name 'DbCommandBuilder' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbProviderFactory.cs(106,25,106,38): error CS0246: The type or namespace name 'DbDataAdapter' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbProviderFactory.cs(119,25,119,47): error CS0246: The type or namespace name 'DbDataSourceEnumerator' could not be found (are you missing a using directive or an assembly reference?)
Data\ProfiledDbProviderFactory.cs(98,30,98,59): error CS0115: 'ProfiledDbProviderFactory.CanCreateDataSourceEnumerator': no suitable method found to override
Data\ProfiledDbProviderFactory.cs(102,42,102,62): error CS0115: 'ProfiledDbProviderFactory.CreateCommandBuilder()': no suitable method found to override
Data\ProfiledDbProviderFactory.cs(106,39,106,56): error CS0115: 'ProfiledDbProviderFactory.CreateDataAdapter()': no suitable method found to override
Data\ProfiledDbProviderFactory.cs(119,48,119,74): error CS0115: 'ProfiledDbProviderFactory.CreateDataSourceEnumerator()': no suitable method found to override

**Comment by cspiess** [comment]
Updating the platform conditional directives resolves the build issues. Tests pass except for Redis and Tests.Async.AsyncTests.Step_WithParallelThreads_RealTime.

**Comment by NickCraver** [comment]
@cspiess can you elaborate a bit on "Updating the platform conditional directives"?

**Comment by NickCraver** [comment]
@cspiess Any update? I'm not sure what issue you're having here if you're on the latest VS 15.3 Preview.

**Comment by NickCraver** [comment]
Closing this out as all of this tooling is out of preview.
