### ISSUE TITLE
404 for static assets when deployed to a virtual directory

### ISSUE THREAD

**Issue by kshyju** [MiniProfiler/dotnet#197]
Trying to add miniprofiler to an aspet core(1.1) app. Everything works fine when in (debug) run from VS (with random port number). When i deploy to an virtual directory under an IIS app, the css/js resources are getting a 404.
![mini-profiler-404](https://user-images.githubusercontent.com/144469/28422317-a58edb28-6d35-11e7-8600-3b7b064b96fa.png)

It is trying to include `http://localhost/profiler/includes.js?v=4.0.0.0` (excluding the app name).So i copied the url and tried in a new tab after manually adding the app name  and it(http://localhost/s4help/profiler/includes.js?v=4.0.0.0) works.

In the `Configure` method, my MiniProfilerOptions has `RouteBasePath = "~/profiler"`. I tried to change this to  `RouteBasePath = "~/s4help/profiler",`. But now the working url is `http://localhost/s4help/s4help/profiler/includes.js?v=4.0.0.0`

**Comment by NickCraver** [comment]
This should be fixed in the commit above for the next alpha, leaving this open until that's on NuGet (large refactor, so I'm moving *all* the options around before pushing another alpha).
