### ISSUE TITLE
async="async" attribute in script tag for XHTML validation

### ISSUE THREAD

**Issue by mad4hit** [MiniProfiler/dotnet#203]
Hi,
i've noticed than the script attached to body is not complaint with XHMTL standard because the async attribute laks of attribute valorization.

`<script async type="text/javascript" id="mini-profiler" src="/mini-profiler-resources/includes.js?v=ySF6M98CBehTtL86BbiEmys9yxR1HKazhe2sznfdUWQ=" data-version="ySF6M98CBehTtL86BbiEmys9yxR1HKazhe2sznfdUWQ=" data-path="/mini-profiler-resources/" data-current-id="827e69a7-6dc4-418f-843a-04dff6a31863" data-ids="2c3d63b2-c9f6-4129-9c3c-f2cca29c54bd,a6cc865a-bd8c-4fc8-a91e-1be425a9ff7c,e58b6193-996d-4dd1-876d-e76d904bd284,cc7edf49-201e-42b8-a84a-4ec792883121,827e69a7-6dc4-418f-843a-04dff6a31863" data-position="left" data-trivial="false" data-children="false" data-max-traces="15" data-controls="false" data-authorized="true" data-toggle-shortcut="Alt+P" data-start-hidden="false" data-trivial-milliseconds="2"></script>`

what i need:

`<script async="async" type="text/javascript" id="mini-profiler" src="/mini-profiler-resources/includes.js?v=ySF6M98CBehTtL86BbiEmys9yxR1HKazhe2sznfdUWQ=" data-version="ySF6M98CBehTtL86BbiEmys9yxR1HKazhe2sznfdUWQ=" data-path="/mini-profiler-resources/" data-current-id="827e69a7-6dc4-418f-843a-04dff6a31863" data-ids="2c3d63b2-c9f6-4129-9c3c-f2cca29c54bd,a6cc865a-bd8c-4fc8-a91e-1be425a9ff7c,e58b6193-996d-4dd1-876d-e76d904bd284,cc7edf49-201e-42b8-a84a-4ec792883121,827e69a7-6dc4-418f-843a-04dff6a31863" data-position="left" data-trivial="false" data-children="false" data-max-traces="15" data-controls="false" data-authorized="true" data-toggle-shortcut="Alt+P" data-start-hidden="false" data-trivial-milliseconds="2"></script>`

Is it possible to achieve this?

thanks 
regards
Alex

**Comment by NickCraver** [comment]
@mad4hit Sure! It'll be in the next alpha, I need some time to fix a few more issues and will update NuGet again. It'll be available on MyGet in a few minutes.
