### ISSUE TITLE
Services has no AddMiniProfiler() method and cannot get "mini-profiler-resources/results"

### ISSUE THREAD

**Issue by Saibamen** [MiniProfiler/dotnet#204]
Visual Studio 2017, Windows 10, .Net Core 1.1

Trying to install MiniProfiler. I have downloaded `MiniProfiler.AspNetCore.Mvc` from NuGet and start to implement it in my project, following these steps: http://miniprofiler.com/dotnet/AspDotNetCore

1. My services (`IServiceCollection`) hasn't `AddMiniProfiler()` method in `startup.cs`
2. I get 404 errors when web starting up and looking for http://localhost:52284/mini-profiler-resources/results. I used default `app.UseMiniProfiler(new MiniProfilerOptions());` and tried modify `RouteBasePath` but nothing works.

**Comment by gjsduarte** [comment]
Try adding `Storage = new MemoryCacheStorage(TimeSpan.FromMinutes(60)),` to your MiniProfilerOptions.

**Comment by NickCraver** [comment]
Which framework is your application targeting specifically?

**Comment by Saibamen** [comment]
@NickCraver: .NetCoreApp 1.1

**Comment by Saibamen** [comment]
Now MiniProfiler works, but I don't get any SQL queries from MiniProfiler.

```
services.AddEntityFramework().AddDbContext<TrollChatDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("Database")));

// MiniProfiler
services.AddMiniProfiler();
services.AddEntityFramework();
services.AddMemoryCache();
```

```
app.UseMiniProfiler(new MiniProfilerOptions
{
// Path to use for profiler URLs
RouteBasePath = "~/profiler",

// (Optional) Control which SQL formatter to use
// (default is no formatter)
SqlFormatter = new StackExchange.Profiling.SqlFormatters.InlineFormatter(),

// (Optional) Control storage
// (default is 30 minutes in MemoryCacheStorage)
Storage = new MemoryCacheStorage(cache, TimeSpan.FromMinutes(60))
});
```

**Comment by NickCraver** [comment]
@Saibamen If you're using EntityFamework for everything, you'll want to call `.AddEntityFramework()` afterwards, like this:
```c#
app.UseMiniProfiler(...).AddEntityFramework();
```
...this sets up Entity Framework profiling.

**Comment by NickCraver** [comment]
@Saibamen also: what was the cause of not seeing the methods? Is it a case we should add some documentation for?

**Comment by Saibamen** [comment]
I've updated to latest Alpha 7 version.
@NickCraver: `app.UseMiniProfiler(...).AddEntityFramework();` doesn't work!
Also `services.AddMiniProfiler().AddEntityFramework();` doesn't build (like in example project: https://github.com/MiniProfiler/dotnet/blob/master/samples/Samples.AspNetCore/Startup.cs#L42)
Project only builds with `services.AddMiniProfiler()` and `services.AddEntityFramework()` in separate lines, but I didn't get my MsSQL Queries...

Documentation need to be updated at http://miniprofiler.com/dotnet/AspDotNetCore

**Comment by NickCraver** [comment]
@Saibamen are you referencing the `MiniProfiler.EntityFrameworkCore` package?

**Comment by Saibamen** [comment]
`<PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.0.0-alpha7-142" />`

**Comment by zqxin45** [comment]
i have the same question,use the newest version,how to solve it

**Comment by Saibamen** [comment]
@zqxin45: Please show your configuration
