### ISSUE TITLE
404 on /profiler/includes.js

### ISSUE THREAD

**Issue by john-luke-laue** [MiniProfiler/dotnet#207]
Hello,

I'm building an ASP.NET Core web app. I installed version 4.0.0-alpha6-79 of MiniProfiler.AspNetCore.Mvc and MiniProfiler.EntityFrameworkCore through the Nuget package manager. 

I followed the installation and setup instructions from [here](http://miniprofiler.com/dotnet/AspDotNetCore). The app builds and runs, and I can see the MiniProfiler script in my html, but the /profiler/includes.js is nowhere to be found, 404. 

`<script async id="mini-profiler" src="/profiler/includes.js?v=4.0.0.0"`

I tried uninstalling and reinstalling, but that did not fix the issue. 
Any ideas? Thanks!

**Comment by NickCraver** [comment]
Can you show me your config, the entire setup class? I have a hunch this is based on the order of the static file handler ordering.

**Comment by Saibamen** [comment]
Try update to Alpha 7 and add `services.AddMemoryCache();` to `startup.cs`

**Comment by NickCraver** [comment]
Just a heads up: I'm working on simplifying everywhere here, there's just a lot to figure out. The next alpha should work more easily but *most* options are moving around. It should be much easier to "do the right thing" with minimal config here.

**Comment by john-luke-laue** [comment]
Actually it was a problem with my web.config. nothing  to do with mini profiler. Sorry! And thanks!
