### ISSUE TITLE
Can miniprofiler run on ASP.NET Core with Ef6 ?

### ISSUE THREAD

**Issue by TimRowe** [MiniProfiler/dotnet#209]
Can miniprofiler run on ASP.NET Core with Ef6 ?
The version is different

**Comment by jdaigle** [comment]
@TimRowe the 4.0.0 version (still alpha) of `MiniProfiler.EF6` _should_ work with ASP.NET Core running on the full .NET framework. I've not tested it personally, but I don't see any reason why it wouldn't work.

**Comment by TimRowe** [comment]
@jdaigle Thanks for your help. I just install the version 3.0.11 of `MiniProfiler.EF6` . I will try the 4.0.0 version .

**Comment by TimRowe** [comment]
@jdaigle Have you test  `MiniProfiler.EntityFrameworkCore` in EFCore 2.0 ? I found it can't show ef profile info(only asp.net info) and without error !!!
The evironment is ASP.NET Core 2.0 + EntityFrameworkCore 2.0
`services.AddMiniProfiler().AddEntityFramework();`

**Comment by jdaigle** [comment]
@TimRowe  I'm sorry, I have not tested with Entity Framework Core.

**Comment by TimRowe** [comment]
@jdaigle I found the diffrent, when I use the EntityFrameworkCore on .net framework 4.6.1 , It can't work.  But when i use the EntityFrameworkCore on .net core2.0 it's ok. and the 
`new MemoryCacheStorage(....)`

params amout is diffrent between the platform. Can offer help?

**Comment by NickCraver** [comment]
@TimRowe The latest alpha should clear things up, can you try alpha8 on NuGet? I removed the split of `MemoryCacheProvider` and split the `IMemoryCache` implementation between the platforms (Where the split really lies, not on the TFM) which should clean up quite a bit. Unless you want to change the default duration, you don't even need to touch it anymore.

The sample application includes Entity Framework Core as well: https://github.com/MiniProfiler/dotnet/tree/master/samples/Samples.AspNetCore

**Comment by TimRowe** [comment]
@NickCraver I upgrade the package to 4.0.0-alpha8-165，the problem is still there.  Finally, I copy the dll of `miniprofiler.aspnetcore` ,`miniprofiler.aspnetcore.mvc`,`miniprofiler.shared`,`miniprofiler.entityframeworkcore`, from the xxx/nuget/packages/xxx/4.0.0-alpha7-142/lib/netstandard2.0/xxx.dll to xxx/nuget/packages/xxx/4.0.0-alpha7-142/lib/net46/xxx.dll, **It works well.** As I know .net framework 4.6.1 is compatible with netstandard2.0.
 But why the xxx/nuget/packages/xxx/4.0.0-alpha7-142/lib/net46/xxx.dll can't work? I can't find the reason.

**Comment by NickCraver** [comment]
@TimRowe Just so I'm clear: you're running your ASP.NET Core 2 implementation on a `net461` framework build and EFCore isn't working in that case? It just doesn't display anything? But building under `netstandard2.0` or copying those DLLs directly does work and display appropriately?

**Comment by NickCraver** [comment]
@TimRowe I fixed what you're hitting with the version split in the commit linked above. It'll be available [on MyGet](https://www.myget.org/gallery/miniprofiler) shortly. If you can try that latest alpha I think all will be resolved. Can you please let me know if that takes care of your setup?

**Comment by TimRowe** [comment]
@NickCraver 
1、you're running your ASP.NET Core 2 implementation on a net461 framework build and EFCore isn't working in that case?
**Answer: Yes**

 2、It just doesn't display anything
**Answer: No, it can display the web part, sql part is miss.**

3、But building under netstandard2.0 or copying those DLLs directly does work and display appropriately?
**Answer：  Yes, ASP.NET Core 2 implementation on .netcoreapp 2.0 is ok. ASP.NET Core 2 implementation on a net461 only work with the netstandard dll instead.**

**Comment by TimRowe** [comment]
I install ` 4.0.0-alpha8-171`  from myget. It can't display sql also.
![qq 20170917230933](https://user-images.githubusercontent.com/5651857/30522131-e1cf17c8-9bfd-11e7-8476-ce873d9e479b.png)
![qq 20170917231243](https://user-images.githubusercontent.com/5651857/30522144-0417f4d0-9bfe-11e7-90ae-2053f16f51bb.png)

I used the .net strandard dll is ok. like below
![qq 20170917231837](https://user-images.githubusercontent.com/5651857/30522207-f21f682a-9bfe-11e7-9e56-055e459dfbbc.png)
![qq 20170917231800](https://user-images.githubusercontent.com/5651857/30522209-f372a19c-9bfe-11e7-89cd-b538786d44a9.png)
![qq 20170917231621](https://user-images.githubusercontent.com/5651857/30522210-f7923e2c-9bfe-11e7-9d10-22762596d284.png)

**Comment by NickCraver** [comment]
@TimRowe I'm confused - the only build in the EF Core package *is* the `netstandard2.0` DLL now. Can you please do a full clean and rebuild to ensure no old DLLs are being dropped in?

**Comment by TimRowe** [comment]
@NickCraver , Yes,  `MiniProfiler.EntityFrameworkCore` is only the `netstandard2.0`. And I rebuilt every time. At last I found that it works with `MiniProfiler.AspNetCore`  on  `netstandard2.0`.  like beblow
`MiniProfiler.AspNetCore.Mvc.dll`   **net46**
`MiniProfiler.EntityFrameworkCore.dll` **netstandard2.0**
`MiniProfiler.Shared.dll` **net46**
`MiniProfiler.AspNetCore.dll` **netstandard2.0** , I think it would also to modify too.

**Comment by NickCraver** [comment]
@TimRowe ah I see the problem, hang on I'll get a new MyGet for you up there with a fix. Thanks a TON for helping test this out, it's a tremendous help since all this diagnostic stuff changed in .NET Core 2.x

**Comment by NickCraver** [comment]
@TimRowe new build going up to MyGet in a few (commit auto-closed this, woops). `4.0.0-alpha8-174` is now [up on MyGet](https://www.myget.org/gallery/miniprofiler) and hopefully resolves you issues :)

**Comment by TimRowe** [comment]
@NickCraver  Well done. It 's ok  with `4.0.0-alpha8-174`. Thanks for your help !!!

**Comment by NickCraver** [comment]
Woohoo! Thanks a bunch Tim!
