### ISSUE TITLE
use sqlite can display sql query，mysql can't display

### ISSUE THREAD

**Issue by zqxin45** [MiniProfiler/dotnet#212]
as title

**Comment by NickCraver** [comment]
Can you elaborate? Which version are you on? Where aren't they displaying?

**Comment by zqxin45** [comment]
.netcore version 1.1
```
<PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.0.0-alpha8-165" />
<PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.0.0-alpha8-165" />
<PackageReference Include="MySql.Data.EntityFrameworkCore" Version="6.10.3-rc" />
```

**Comment by NickCraver** [comment]
How are you spinning up a connection? The DbConnection for profiling (if not using EntityFramework for everything) isn't automatic.

**Comment by zqxin45** [comment]
i use the sample code, change the table column,where i change the connection to sqlite,it's work,the different as follow
![1504663515 1](https://user-images.githubusercontent.com/9971320/30091204-ee32a2da-92ea-11e7-89be-e1aec6b0cae6.png)

**Comment by NickCraver** [comment]
There's a new version of `MySql.Data.EntityFrameworkCore` ([8.0.9-dmr](https://www.nuget.org/packages/MySql.Data.EntityFrameworkCore/)) released yesterday, would you mind giving this a shot and let me know if profiling still doesn't register? This would help greatly when looking at their current code.

**Comment by zqxin45** [comment]
it's still doesn't register
![1508829021 1](https://user-images.githubusercontent.com/9971320/31929181-8495c308-b8cd-11e7-91aa-aff2e7078eda.png)

**Comment by NickCraver** [comment]
Can you please give me your current package versions and your startup config so I can see what's happening?

**Comment by NickCraver** [comment]
@zqxin45 I'd need a repro here because I can't get the MySQL provider to work *at all* due to https://stackoverflow.com/questions/45439723/mysql-entityframeworkcore-system-typeloadexception. You can however use https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/ as a viable alternative. I've spent today tracking down other issues and their provider works.

**Comment by NickCraver** [comment]
Closing out due to no info to go on here.
