### ISSUE TITLE
MiniProfiler reporting connection opening/closing

### ISSUE THREAD

**Issue by lxalln** [MiniProfiler/dotnet#213]
I'm currently using version `4.0.0-alpha8-165` of `MiniProfiler.AspNetCore.Mvc` and `MiniProfiler.EntityFrameworkCore` and am seeing `Connection Close()` and `Connection Open()` calls being reported.

These are of course then showing up as duplicates too.

Is this a bug? A configuration issue in MiniProfiler/EntityFramework? Or am I just doing something stupid?

![image](https://user-images.githubusercontent.com/2781908/30055792-6f168060-9228-11e7-88a1-a6d4e927cfed.png)

![image](https://user-images.githubusercontent.com/2781908/30055802-7677b162-9228-11e7-8ab4-557736250192.png)

**Comment by NickCraver** [comment]
The reporting of them is correct, the duplicate warning is not. Let me take a look at the exclusion on those. The reason we report them in v4 is you may spend a lot of time waiting on a connection pool for example.

**Comment by NickCraver** [comment]
Fixed in 3c685dd15f90ce69f1d123dab1d6ba2f4c7f491f, we forgot the obvious, doh.

cc @jdaigle who'll find this funny =P

**Comment by jdaigle** [comment]
@NickCraver I suppose I missed that because I'm not yet using EF Core. And `ProfiledDbConnection` doesn't add a timing for `Close()`.

**Comment by NickCraver** [comment]
@jdaigle oh I missed this in code review many times, just funny looking back at it
