### ISSUE TITLE
RelationalDiagnosticListener is throwing NullReferenceException with EntityFramework

### ISSUE THREAD

**Issue by lxalln** [MiniProfiler/dotnet#214]
I'm using `4.0.0-alpha8-165` of both `MiniProfiler.AspNetCore.Mvc` and `MiniProfiler.EntityFrameworkCore`.

When `RelationalDiagnosticListener` is attempting to call `.Stop()` on the profiler, it's hitting a null reference:

Currently [line 114 of `RelationalDiagnosticListener`](https://github.com/MiniProfiler/dotnet/blob/648ad59a46921fd30301ae82adcc6e70344cf8e1/src/MiniProfiler.EntityFrameworkCore/RelationalDiagnosticListener.cs#L114)
Relevant code:
``` csharp
if (_opening.TryRemove(data.ConnectionId, out var openingTiming))
{
    openingTiming.Stop();
}
```

Following this through, the `ConcurrentDictionary` is having a null profiler added to it by the [`MiniProfilerExtensions.CustomTiming()`](https://github.com/MiniProfiler/dotnet/blob/648ad59a46921fd30301ae82adcc6e70344cf8e1/src/MiniProfiler.Shared/MiniProfilerExtensions.cs#L66) extension method, which is falling through to `CustomTimingIf()`.

`CustomTimingIf()` is doing the following check:
```csharp
if (profiler == null || profiler.Head == null || !profiler.IsActive) return null;
```

My miniprofiler setup is:
```csharp
services.AddMiniProfiler(options =>
            {
                options.RouteBasePath = "/profiler";
                options.ResultsAuthorize = request => request.HttpContext.User.IsInRole(Roles.SystemAdministrator);
                options.ShouldProfile = request => request.HttpContext.User.Identity.IsAuthenticated;
                options.SqlFormatter = new VerboseSqlServerFormatter();
            }).AddEntityFramework();
```

I'm not entirely sure why this happening, but the way I can reproduce it is to:
1. remove the `.AddEntityFramework()` call.
2. Run application & login
3. add the `.AddEntityFramework()` call back (still logged in)
4. sign out, and attempt to login again
5. see error:
```
NullReferenceException: Object reference not set to an instance of an object.
StackExchange.Profiling.Data.RelationalDiagnosticListener.OnNext(KeyValuePair<string, object> kv) in RelationalDiagnosticListener.cs, line 114
```

My assumption is that this being caused by some state being retained, after hitting the profiler and `options.ShouldProfile` being set to false. But I'm not sure beyond guessing, or really digging through the source.

As you're still working on this alpha, I hoped it would be easier to dump a load of information here and you'll be able to spot it much quicker than I can. If not, then I'll debug further with this repro.

**Comment by NickCraver** [comment]
Can you explain the 1-5 steps above? Are you doing that dynamically, and not in `ConfigureServices`? I'd like to understand what's happening there so maybe the race is more apparent.

I've pushed a fix above for the next release, after another issue round-up I'll do another build.

**Comment by lxalln** [comment]
No, those steps are literally me editting the code in VS and letting dotnet detect the code changes and restart.

The code is in `ConfigureServices`.

Don't think I mentioned before, but this is aspnet core 2, on dotnet core 2.

**Comment by NickCraver** [comment]
@lxalln Gotcha, thanks! Fixed in the next alpha (already on MyGet), so closing this out to keep track of what's left.

**Comment by phil-debbs** [comment]
> @lxalln Gotcha, thanks! Fixed in the next alpha (already on MyGet), so closing this out to keep track of what's left.

Thanks for the update. It saved me.
