### ISSUE TITLE
Request is not profiled due to having content in the path

### ISSUE THREAD

**Issue by Romanx** [MiniProfiler/dotnet#215]
We've just started using Miniprofiler 4 in our MVC5 app and I got very confused that one of our pages which contains `/content/` in the path wasn't being profiled due to the exclusions [here.](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/MiniProfilerBaseOptions.cs#L75-L78) This wouldn't be so much of a problem but we also have our scripts, styles and images in a content folder which isn't the most useful thing.

The options I have is to override the `IgnoredPaths` adding in the folders in the Content folder however this means that contents in the root will still be profiled. Since IgnoredPaths is using string.Contains any path with content inside it may cause issues even `https://www.myawesomewebsite.com/user/content/stuffhere`

I'm loathe to suggest some kind of whitelist but i can't think of a simple solution that would be fast. Any advice or solution you can help me come to would be great.

**Comment by NickCraver** [comment]
When you call` .Start()` underneath, we're just applying the ignores in the provider and seeing if we should start or return nothing. I'd suggest simply moving that check out and making it more specific by:

1. Removing it from the `IgnoredPaths` collection
2. Wrapping your `.StartProfiler()` in a check that excludes your content folder based on the current request path.

Let me know if you hit any kinks there :)

**Comment by Romanx** [comment]
That makes perfect sense, sometimes hard to see a simple solution staring at you. Thanks Nick!
