### ISSUE TITLE
WebUI loaded too early in angular 1.x app

### ISSUE THREAD

**Issue by SeriousM** [MiniProfiler/dotnet#217]
I noticed that I don't get any results in my web ui and I found out that the check for `window.angular` results in `null` because the app is still loading but `XMLHttpRequest` is already available.
https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/ui/includes.js#L598

Is there a good reason why the script checks for angular even though it's not used at all?

**Comment by NickCraver** [comment]
Yep! Since `XMLHttpRequest` is ultimately used by *all*, we only want to replace it the `angular` case, because in every *other* case, we'd be double registering handlers (and not so efficiently at that).

**Comment by NickCraver** [comment]
Closing out to cleanup, let me know if questions linger!
