### ISSUE TITLE
Angular removes WebUI

### ISSUE THREAD

**Issue by SeriousM** [MiniProfiler/dotnet#218]
After the web ui has loaded and injected all the necessary container (eg `.profiler-queries-bg`, `<div class="profiler-queries-bg"/>`, `.profiler-result-full`), angular finish loading the app and replaces unfortunately parts of the body elements.

Only the following elements survive the app startup:
![image](https://user-images.githubusercontent.com/462013/30844671-57a10d38-a290-11e7-9e7c-c2f22be98511.png)

Is there a way to either defer the loading of the web ui or help it so survive?

**Comment by NickCraver** [comment]
I'm unclear on the issue here (I'm no Angular expert), is it possible to give me a before and after HTML of what it's doing?

**Comment by NickCraver** [comment]
Closing this out - unsolvable without much more information.
