### ISSUE TITLE
[Question] How to include MiniProfiler when rendering response as string?

### ISSUE THREAD

**Issue by matthewrk** [MiniProfiler/dotnet#219]
I have a dotnet core project using DotLiquid templates, so essentially the response is rendered as a string through return Content(response, "text/html");

How do I include MiniProfiler UI components while doing this?

**Comment by NickCraver** [comment]
Are you looking to render the MiniProfiler in a text format, or looking at how to output the HTML tag? I'm a little unclear on the goals here, but can help with either!

**Comment by matthewrk** [comment]
I'm trying to render the HTML components for MiniProfiler to get the little widget that sits in the corner. Simplifying a bit I'm basically returning html directly from my controller, like this:

return Content("<html>...</html>", "text/html")

(reason being that I'm rendering Liquid templates).

So what I need to know is what I need to include on the page manually to get the MiniProfiler widget showing. Reading the source I saw something like <mini-profiler /> but wasn't able to find the JS/CSS to make that work. I am assuming MiniProfiler adds something in to serve that so I just need the paths, or to inject the whole scripts in from somewhere?

I appreciate the help!

**Comment by NickCraver** [comment]
@matthewrk What you probably want is `MiniProfiler.Current.RenderIncludes()` ([code here](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.AspNetCore/MiniProfilerExtensions.cs#L23), which uses [code here](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/Internal/MiniProfilerExtensions.cs#L26)) to get the `<script>` tag it renders. Hope that helps!

**Comment by matthewrk** [comment]
@NickCraver got it, thanks for the help! 👍
