### ISSUE TITLE
Non prefixed @keyframes used

### ISSUE THREAD

**Issue by SSiertsema** [MiniProfiler/dotnet#222]
![image](https://user-images.githubusercontent.com/9604824/31175562-f66f79a6-a90f-11e7-8747-971224f28dfe.png)

Hey there,

Prefixing is CSS is nicely done except for the fadeIn keyframe. This could easily result in changes on base application.

Best regards Sven

**Comment by NickCraver** [comment]
Certainly a valid complaint - I'll get that fixed up.

**Comment by NickCraver** [comment]
Fixed in latest on MyGet and will be in the next package, thanks!
