### ISSUE TITLE
POST to /api/profiler/results returns 404

### ISSUE THREAD

**Issue by anderslyman** [MiniProfiler/dotnet#223]
Getting a bunch of these on a dotnet core (angular) project:
![image](https://user-images.githubusercontent.com/1380857/31250932-8bb0098a-a9d9-11e7-9933-2d5ddaa61d9f.png)

Here's one of the requests:
![image](https://user-images.githubusercontent.com/1380857/31251104-1b8b6932-a9da-11e7-91cb-a4072b1f7ff7.png)

I have a pretty minimal configuration: 
`app.UseMiniProfiler();`
and
`services.AddMiniProfiler(options =>
{
	options.RouteBasePath = "/profiler";
});`

I've exposed the ui files (include.js/css/tmpl) and those are coming down fine, and I've intercepted the http calls to grab the `X-MiniProfiler-Ids` header and request results.

Is there a `.Init()` somewhere I need to call to register the routes?

**Comment by NickCraver** [comment]
It looks like you're hitting `/api/profiler` and not `/profiler`, are you configured for a virtual directory or intercepting AJAX call in some way?

**Comment by anderslyman** [comment]
let me try it without `/api`. 
Since getting things to work in Angular is not documented, I've been scouring the internet to find examples/suggestions, and that was the route that others used...

**Comment by anderslyman** [comment]
That was it, thanks for the rapid response!
