### ISSUE TITLE
Unable to get Entity Framework Core profiling to work

### ISSUE THREAD

**Issue by Daniel15** [MiniProfiler/dotnet#224]
I'm trying to use the Entity Framework Core profiling as [documented on the site](https://miniprofiler.com/dotnet/HowTo/ProfileEFCore), but it's not working for me. I don't see any of the EF data in the Mini Profiler:

![](http://ss.dan.cx/2017/10/chrome_09-10.34.45.png)

I confirmed that I am calling `AddEntityFramework` in `ConfigureServices`, and that it is called after registering my database context:
```
			services.AddMiniProfiler(options =>
			{
				options.ResultsAuthorize = options.ResultsListAuthorize = 
					request => request.HttpContext.User.Identity.IsAuthenticated;
			}).AddEntityFramework();
```

Here's all the changes I made to my app to add Mini Profiler: https://github.com/Daniel15/Website/commit/450a34d3d2050f221eb67bb77d9c59c9a6a7871b

**Comment by NickCraver** [comment]
The EF 2.0 profiling changed *completely* in 2.x, so the provider model there only works on 2.0 of above (I bet you're getting a package conflict in your build), but it looks like you're mostly on 1.x. Have you considered migrating to ASP.NET Core 2? For most things it's a pretty straight-forward upgrade.

**Comment by Daniel15** [comment]
Thanks, I'll try that soon.  

I didn't see any conflicts during my build. I'm targeting .NET Framework 4.6.2, for which `MiniProfiler.EntityFrameworkCore` depends on `Microsoft.EntityFrameworkCore.Relational (>= 1.1.2)`. The dependency on `>=2.0.0` is only present for .NET Standard 2.0 (see https://www.nuget.org/packages/MiniProfiler.EntityFrameworkCore). Should it actually be updated to `>=2.0.0` for all runtimes? Currently it sounds like it'd always be broken on .NET Framework 4.6.2 + Entity Framework 1.1, without throwing any build errors.

**Comment by NickCraver** [comment]
@Daniel15 Ah I see the problem here! It's me being an idiot.

There's a nasty problem there with how they did 1.x -> 2.0. The MyGet feed has this fixed (and only references EF 2.0+) but not NuGet. You can either use the MyGet feed *right now*, or I'll update NuGet in the next day or two. I'm making a few enhancements as I try to upgrade some of our projects to v4 and find what's missing along the way.

**Comment by Daniel15** [comment]
Hmm, I tried upgrading to ASP.NET Core 2.0 + Entity Framework Core 2.0, and the version of MiniProfiler on NuGet is still not correctly profiling Entity Framework queries 😕 

Here's my full set of changes... Am I missing something important? https://github.com/Daniel15/Website/compare/master...miniprofiler

**Comment by NickCraver** [comment]
@Daniel15 can you try updating to the latest NuGet packages? I've since published the fixed versions of EF to NuGet :)

**Comment by Daniel15** [comment]
OK, I think I'm getting closer. With MiniProfiler 4.0.0-alpha9-00202, I see the "sql (ms)" column, but clicking it just shows connection Open and Close calls. It doesn't show the actual SQL queries:
![](http://ss.dan.cx/2017/10/chrome_16-15.49.02.png)

I'm using the Pomelo MySQL provider... Is only SQL Server supported, or something like that?

**Comment by NickCraver** [comment]
@Daniel15 It could be their provider, if somehow going far outside the lines somehow. I'll try and take a look soon, but I'm unsure without going through their source and see what's not being called here.

**Comment by NickCraver** [comment]
@Daniel15 I can repro your behavior...after a bit of a rough setup, that schema.sql needs updating :)

I'll poke the provider when time allows, but just a shot in the dark: @bgrainger any idea of shenanigans going on here off the top of your head that you've already come across?

**Comment by bgrainger** [comment]
I'm not very familiar with the EF.Core side; that's implemented by https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql.

Is it just a matter of the provider creating a `ProfiledDbConnection` (guessing not, that seems to be happening in MiniProfiler), or emitting events that [`RelationalDiagnosticListener`](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.EntityFrameworkCore/RelationalDiagnosticListener.cs) can listen to?

CC @kagamine @caleblloyd for your input.

**Comment by NickCraver** [comment]
Okay after spending a very unreasonable amount of time looking at source code that *looks* like it should work...well, it does.

@Daniel15 just update your `Pomelo.EntityFrameworkCore.MySql` from 2.0.0 to 2.0.0.1 where they've fixed the issue and logging will work.

**Comment by Daniel15** [comment]
> after a bit of a rough setup, that schema.sql needs updating :)

Haha, I never expected anyone to actually use my site's code other than me, so I haven't done such a good job at keeping things like that up-to-date :( sorry about that

> @Daniel15 just update your Pomelo.EntityFrameworkCore.MySql from 2.0.0 to 2.0.0.1 where they've fixed the issue and logging will work.

Oh interesting... Do you know which commit fixed the issue?

**Comment by NickCraver** [comment]
Likely https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/352 due to the drastic relational logging changes to diagnostic events. I prodded them to make some big changes which they did a good job of delivering in https://github.com/aspnet/EntityFrameworkCore/pull/8288

**Comment by NickCraver** [comment]
Closing this out to cleanup since it's not a MiniProfiler issue, let me know if you run into any more trouble!

**Comment by Daniel15** [comment]
It works!! Thanks! ❤️

**Comment by KiarashS** [comment]
I have same issue with EF Core 2.1.0 preview1 !

**Comment by KiarashS** [comment]
I have same issue with EF Core 2.1.0 preview1 !

**Comment by XunWind** [comment]
Update Pomelo.EntityFrameworkCore.MySql from 2.0.0 to 2.0.1. It Works Thanks!

**Comment by KiarashS** [comment]
@NickCraver I have same issue with EF Core 2.1.1!
