### ISSUE TITLE
Mini profiler does not work with hangfire

### ISSUE THREAD

**Issue by dalibor983** [MiniProfiler/dotnet#228]
I cannot use mini profiler with dotnet core when hangfire is registered in service collection with services.AddHangfire.

If my controller try to use some service that reference IBackgroundJobClient or IRecurringJobManager I always get this error `JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.`.

When I remove mini profiler everything works.

**Comment by NickCraver** [comment]
Do you have a stack trace for this error? I have *no* idea how these two interact but let's find out!

**Comment by rlenders** [comment]
For the record, I'm using MiniProfiler and Hangfire together and I have no errors. I am using MiniProfiler 4 alpha version though.

**Comment by dalibor983** [comment]
My problem with hangfire is that I cannot use this:
```
services.AddHangfire(config => 
        config.UseSqlServerStorage(Configuration.GetConnectionString("HangfireConnection")));
```
in configuration service section because this code tries to create database tables for hangfire but my database does not exist when this code is executed.

I have a separate database initialization code that use a service provider. So I can not call `services.AddHangire()` after database initialization because I already build service provider from service collection for database initialization code.

To solve this I call `services.AddHangire()` without `config.UseSqlServerStorage()` in configure services section and then in configuration section I resolve `IGlobalConfiguration` from service provider and call `UseSqlServerStorage()` on resolved instance.

When I use this approach with mini profiler I got this error.

I resolve this problem using
```
GlobalConfiguration.Configuration.UseSqlServerStorage()
```
after my database initialization code. So here I do not resolve IGlobalConfiguration instance from service provider, instead I em using static property `GlobalConfiguration.Configuration`. And now application works with mini profiler.

**Comment by NickCraver** [comment]
@dalibor983 I'm glad you're sorted out, and thank you so much for writing up what you encountered and the solution so that anyone else finding this knows how to resolve. It's much appreciated!

**Comment by dalibor983** [comment]
I also notice that mini pofiler (alpha version for net core) + hangfire causes same memory leaks and my application start eating memory till I completely remove miniprofiler from my application.
