### ISSUE TITLE
Update documentation for ASP.NET Core

### ISSUE THREAD

**Issue by michaelvannevel** [MiniProfiler/dotnet#229]
In the documentation for how to get started with ASP.NET Core at https://miniprofiler.com/dotnet/AspDotNetCore the section that contains:
@addTagHelper *, MiniProfiler.AspNetCore.Mvc

I think it would be beneficial to note the using statement for the taghelper.  I have never used mini profiler before, and unless i looked at the sample i wouldn't have figured that out as missing the using statement didn't throw an exception.

**Comment by NickCraver** [comment]
Fixed via 6c0c34f6c403cab1c8fd3035cd2303564c3f1004 above, thank you for the suggestion!
