### ISSUE TITLE
MiniProfiler ASP.NET Core Not Rendering with Microsoft.AspNetCore.Mvc.Versioning?

### ISSUE THREAD

**Issue by michaelvannevel** [MiniProfiler/dotnet#230]
So i have versioning set up with Microsoft.AspNetCore.Mvc.Versioning from NuGet.  For example:
```
[ApiVersion("1.0")]
    [Route("api/books/v{version:apiVersion}/[controller]")]
    public class IndexController : Controller
```

To set it up you have to install the nuget package, add:

```
services.AddApiVersioning(c =>
            {
                c.ReportApiVersions = true;
            });
```
into your Startup.cs file in the ConfigureServices method, and add the attributes on the controller as shown above.

When I debug my app the urls look something like http://localhost:55555/v1/api/books/index  .
I tried to use the mini-profiler options for RouteBasePath, but no matter what I try, it doesn't seem to work.
The pages will render, but mini-profiler does not.  There are no requests to any mini-profiler resources, and no javascript errors.

Any ideas?

**Comment by NickCraver** [comment]
Can you please share your config? I haven't used versioning so seeing your order of services and config usages would help be debug how versioning interacts with routing.

**Comment by michaelvannevel** [comment]
I'm not sure how much i'm allowed to share, but i can tell you the order in which some things happen.  

**Inside of ConfigureServices in the Startup.cs**
services.AddMvc();
services.AddMemoryCache();
services.AddApiVersioning(c =>
            {
                c.ReportApiVersions = true;
            });
services.AddCors(); //more stuff in here
Then i add some classes to dependency injection via an extension method for IServiceCollection
After that I call AddMiniProfiler(services);

`private void AddMiniProfiler(IServiceCollection services)
        {
            services.AddMiniProfiler(options =>
            {
                options.SqlFormatter = new StackExchange.Profiling.SqlFormatters.VerboseSqlServerFormatter();
                options.RouteBasePath = "/v1/default";
            });

        }`

**Inside of Configure(IApplicationBuilder app, IHostingEnvironment env) in Startup.cs**
app.UseCors("SomePolicy");
app.UseMvc();
AddMiniProfiler(app);
`private void AddMiniProfiler(IApplicationBuilder app)
        {
            app.UseMiniProfiler();
            app.UseStaticFiles();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
            
        }`

Hopefully that is enough information.

**Comment by NickCraver** [comment]
Just for completeness: are you calling `MiniProfiler.Current.RenderIncludes()` in your view? That's what renders the actual `<script>` tag which initiates all the UI.

**Comment by NickCraver** [comment]
This should be fixed in v4 current with the pathing changes long ago. I haven't heard of anyone else hitting this or news here, so going to close this out. If someone can still repro, I'll happily reopen and we'll dig into it :)
