### ISSUE TITLE
NullReferenceException on index view once cache duration expires

### ISSUE THREAD

**Issue by xt0rted** [MiniProfiler/dotnet#231]
I'm running v3.2.0 and I'm seeing a `NullReferenceException` being silently thrown at https://github.com/MiniProfiler/dotnet/blob/c6300c7215f48e340891551d698e831a6bf6f824/StackExchange.Profiling/MiniProfilerHandler.cs#L262

There's no visible errors, but I'm seeing them being logged to Raygun. The ajax request to `/mini-profiler-resources/results-list` also returns a 500 response and then polling stops.

**Full stacktrace that's being logged**

```
StackExchange.Profiling.MiniProfilerHandler.<GetListJson>b__4(Guid g) in c:\TeamCity\buildAgent\work\a743336045964cbc\StackExchange.Profiling\MiniProfilerHandler.cs:262 
System.Linq.Enumerable+WhereSelectEnumerableIterator`2.MoveNext():77 
System.Web.Script.Serialization.JavaScriptSerializer.SerializeEnumerable(IEnumerable enumerable, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat):55 
System.Web.Script.Serialization.JavaScriptSerializer.SerializeValueInternal(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat, MemberInfo currentMember):648 
System.Web.Script.Serialization.JavaScriptSerializer.SerializeValue(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat, MemberInfo currentMember):113 
System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, StringBuilder output, SerializationFormat serializationFormat):0 
System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, SerializationFormat serializationFormat):6 
StackExchange.Profiling.Helpers.ExtensionMethods.ToJson(Object o) in c:\TeamCity\buildAgent\work\a743336045964cbc\StackExchange.Profiling\Helpers\ExtensionMethods.cs:73 
StackExchange.Profiling.MiniProfilerHandler.GetListJson(HttpContext context) in c:\TeamCity\buildAgent\work\a743336045964cbc\StackExchange.Profiling\MiniProfilerHandler.cs:259 
StackExchange.Profiling.MiniProfilerHandler.ProcessRequest(HttpContext context) in c:\TeamCity\buildAgent\work\a743336045964cbc\StackExchange.Profiling\MiniProfilerHandler.cs:89 
System.Web.HttpApplication+CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute():397 
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously):21 
```

**Steps to repro**
1. Use `HttpRuntimeCacheStorage` and set the time span to a couple minutes
1. Load up any page on the site
1. Load up `/mini-profiler-resources/results-index`
1. Wait for the cache duration to expire
1. Reload `/mini-profiler-resources/results-index`

If you load the index view right away there's no error thrown and polling goes as expected. Once the cache duration expires the ajax request continues to poll with the `last-id` query string value set, but if a request without that is made then the exception is thrown and continues to be until a request to a page other than `/mini-profiler-resources/*` is made.

**Comment by NickCraver** [comment]
Hey there! Unfortunately I do not think this will be fixed *in 3.2*. The 4.0 release (currently in alpha) in imminent, so it's *very* unlikely we'll release anything else in the 3.x line (simply due to lack of time). Any chance you are in a position to upgrade? Docs including upgrades for v4 are here: https://miniprofiler.com/dotnet/

**Comment by xt0rted** [comment]
I've got a deploy queued up that finally turns this on in production so the preview release will have to wait. Once a stable release is out I'll update for sure.

**Comment by xt0rted** [comment]
I was looking through my errors in Application Insights and there was a debug snapshot from when this error last occurred. So being curious I looked through it. It looks like the error was actually triggered one line down from what was first reported. The `.Load(g)` call is returning `null` so when the response tries to be built it's crashing there. And by the looks of it this bug is fixed in v4, so good work 🎉 

https://github.com/MiniProfiler/dotnet/blob/3611224226f0d1ec1ee35aafb701c401b32eaae0/src/MiniProfiler/MiniProfilerHandler.cs#L207

**Comment by NickCraver** [comment]
@xt0rted A few minor fixes coming to NuGet soon (I'll wait one more day for issues coming in), but v4 stable is out and on NuGet :)

**Comment by xt0rted** [comment]
The new version works great so far. In v3 I'd sometimes get requests being split into 2 results with a couple queries in one and the rest in the other. I've yet to see that in v4 so that's really exciting.

**Comment by xt0rted** [comment]
@NickCraver I just realized that my sql timing count is doubled in v4 compared to v3. This seems to be due to 2 items being counted per query. There's an `OpenAsync` and then a `Reader` timing for each query that EF executes. Is this change intentional? It feels weird needing to half the number to get the amount of queries run on the page.

**Comment by NickCraver** [comment]
@xt0rted next build won't count them :)
