### ISSUE TITLE
EF Core profiling - compilation issue

### ISSUE THREAD

**Issue by lol768** [MiniProfiler/dotnet#234]
I'm following the steps described [here](https://miniprofiler.com/dotnet/HowTo/ProfileEFCore).

Relevant package versions:

```xml
<PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.0.0-alpha9-00202" />
<PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.0.0-alpha9-00206" />
```

Relevant section of `Startup#ConfigureServices`:

```cs
services.AddMiniProfiler().AddEntityFramework();
```

Build error:

```
Startup.cs(53,13): error CS1929: 'IMiniProfilerBuilder' does not contain a definition for 'AddEntityFramework' and the best extension method overload 'MiniProfilerServiceCollectionExtensions.AddEntityFramework(IMiniProfilerBuilder)' requires a receiver of type 'IMiniProfilerBuilder' 
```

Am I doing something stupid here?

**Comment by NickCraver** [comment]
We had to move the shared bits lower for multiple packages like EF Core to work across platforms, but the fix is easy, just upgrade the `MiniProfiler.AspNetCore.Mvc` package to latest as well.

**Comment by lol768** [comment]
Cheers for that, I missed that the final digits of the versions were different - all working now.
