### ISSUE TITLE
MiniProfiler <script> rendered even when user cannot view profiler data

### ISSUE THREAD

**Issue by Daniel15** [MiniProfiler/dotnet#239]
I'm using ASP.NET Core 2.0. I have MiniProfiler configured such that the results are only viewable when logged in:
```
			services.AddMiniProfiler(options =>
			{
				options.ResultsAuthorize = options.ResultsListAuthorize = 
					request => request.HttpContext.User.Identity.IsAuthenticated;
			}).AddEntityFramework();
```

However, I'm still seeing the MiniProfiler `<script>` tag being rendered:
```
<script async="async" id="mini-profiler" src="/mini-profiler-resources/includes.js?v=4.0.0.0" data-version="4.0.0.0" data-path="/mini-profiler-resources/" data-current-id="5ce2bb02-4bda-45d5-8e03-f3c4c0b621f8" data-ids="5ce2bb02-4bda-45d5-8e03-f3c4c0b621f8" data-position="left" data-max-traces="15" data-toggle-shortcut="Alt+P" data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync"></script>
```

This doesn't really make sense as the user can't actually open MiniProfiler. I don't want people to load the giant `includes.js` file if they can't even see the profiler 😄

**Comment by NickCraver** [comment]
@Daniel15 I agree and have changed up how this works in alpha 10, there's a 4.0.0-alpha9-00215 release [up on MyGet](https://www.myget.org/gallery/miniprofiler) if you want to give it a go.

**Comment by Daniel15** [comment]
Awesome, thanks! 😃
