### ISSUE TITLE
Alpha releases inconsistencies between nuget and myget

### ISSUE THREAD

**Issue by finkinfridom** [MiniProfiler/dotnet#240]
In our project we moved from version 3.x to 4.x-alpha because the current stable is using jQuery 1.10 while we use jQuery 3.2.1 as a requireJS module.
The latest nuget package is 15 days old while the latest includes.js update (with jQuery 3.2.1 is 14 days old).
We just noticed in nuget the latest releases are missing.
Any ETA for the next releases?
Thanks

**Comment by NickCraver** [comment]
I'm hoping to get a beta up on NuGet this week, a few more issues I'm resolving before pushing up.  You can also go ahead and grab latest with jQuery 3 from MyGet here: https://www.myget.org/gallery/miniprofiler

Closing just to get a handle on overall issues but happy to answer any further questions!
