### ISSUE TITLE
Unable to detect underlying DB provider since alpha 7

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#248]
[EntityFramework.Utilities](https://github.com/MikaelEliasson/EntityFramework.Utilities) provides batch operations for EntityFramework. It attempts to detect what DB provider is being used, but because MiniProfiler.EF6 wraps the connection, EFUtilities can't detect I'm using SQL Server. This results in an error and cancels the DB operation.

Initially I opened an issue about this at their repository, but I just realized using both MiniProfiler and EFUtilities works fine when using MiniProfiler alpha 6 or earlier. Commit 85095a5e223495482bbdd4ec13d0cb6ac8e1bf80 seems to be what broke the DB provider detection.

I'm not sure what was changed in this commit, and I'm also not sure how EFUtilities attempts to detect the provider. Maybe the commit's author @jdaigle can shed some light on this?

I would love to see this fixed... I'm heavily relying on EFUtilities, and I'd hate to be stuck on MiniProfiler alpha 6.

**Comment by NickCraver** [comment]
cc @jdaigle as this is an overall behavior shift.

The basic issue here is we properly implement `DbConnection`, but they're not using that agnostic version - they're looking specifically for `SqlConnection` and things it has that aren't shared across providers. This is directly at odds with how we do timing in general (by intercepting commands and wrapping them in timings).

The only alternative I see here is a whole other `ProfiledSqlConnection` which adds tons of duplicate code, user confusion, and a lot of maintenance. I really don't want to go down that route unless we absolutely have to. The real kicker here is it'd be *only* to solve this case (as far as I know), with no enhancements at all.

Let's see if @jdaigle has ideas on how to better integrate here.

**Comment by RudeySH** [comment]
Thanks for the response. In the meanwhile I'm thinking of forking EntityFramework.Utilities to see if I can fix the provider detection on their end.

**Comment by jdaigle** [comment]
@NickCraver you couldn't subclass `SqlConnection` even if you wanted to since it's sealed.

I think we're stuck with the "wrapping" concept, which is probably always going to break code that relies on a specific implementation, like `SqlBulkCopy`.

I don't know if this is a problem that can be solved without backing away from wrapping the connection - but then we lose out of profiling any command that's created directly from the `DbConnection` rather than through `DbProviderServices`.

**Comment by RudeySH** [comment]
While forking EntityFramework.Utilities, I realized I can detect the underlying DB provider without modifying the source code of EntityFramework.Utilities OR MiniProfiler.

See https://github.com/MikaelEliasson/EntityFramework.Utilities/issues/118.

**Comment by NickCraver** [comment]
Nice! Thanks for writing it up in case anyone else hits this, it's much appreciated :)
