### ISSUE TITLE
[Question] Implementing MiniProfiler in ASP.Net site (WebForms)

### ISSUE THREAD

**Issue by ironicnet** [MiniProfiler/dotnet#249]
I have to mantain a Monolithic project made in ASP.Net (WebForms).

Is there a package that I can use to profile to profile the page requests / direct methods / direct events?

How can I add that kind of profiling to the page if I have to create custom code?

**Comment by NickCraver** [comment]
Are you asking how to profile .aspx pages, or something else? I'm not sure I follow the exact ask here - which file type/area are you trying to profile? (answers would vary)
