### ISSUE TITLE
MyGet feed showing incorrect build as "latest"

### ISSUE THREAD

**Issue by jdaigle** [MiniProfiler/dotnet#251]
https://myget.org/feed/miniprofiler/package/nuget/MiniProfiler

Currently shows "4.0.0-alpha9-00215". But the latest is actually supposed to be "4.0.0-alpha10-00219", which doesn't appear until very far down.

**Comment by NickCraver** [comment]
Well this is because someone sucks at semver, and you're looking at him.

**Comment by NickCraver** [comment]
This was resolved last night - I've moved the versioning scheme and automated it a bit more to ensure it doesn't repeat. Thanks! Working on a few quirks then we'll get a beta out on NuGet, I appreciate all the effort you've pitched in here :)
