### ISSUE TITLE
StackExchange.Profiling.Wcf outdated

### ISSUE THREAD

**Issue by Danielku15** [MiniProfiler/dotnet#252]
I'd like to ask what happened to the StackExchange.Profiling.Wcf package. It appears to be quite outdated compared to the other packages. 
  
Also it appears that a new version of MiniProfiler is in active development, are there plans to still support WCF? I couldn't find any source on WCF on the master branch. I would have a small addition/fix to WCF on v3: Support of duplex channels and proper action names in the profiler name. I was wondering if there is a change for an official nuget package if I contribute those changes.

**Comment by NickCraver** [comment]
I don't (currently) have any plans to support WCF (or familiarity with it...that's the reason). But, if someone wanted to PR an update to 4.0 that adds WCF support in the new version I'd be more than happy to take a look and add it in :)

**Comment by Danielku15** [comment]
Is there already a plan when 4.0 will be released? I'd be happy to add the functionality so we can use then also 4.0 in our product. I think 90% of the code can anyhow be reused :smile:

**Comment by NickCraver** [comment]
@Danielku15 I'm back to working on 4.0 now (had to take a break to build a basement), hopefully going out over the next few weeks as RTM. I'm looking into open issues now. WCF will follow the 4.0 release if contributed afterwards, but happy to take a look at a PR w/ sample project additions at any point - it'd be much appreciated.

**Comment by NickCraver** [comment]
@Danielku15 The beta for 4.0 is now on NuGet if this is still appealing to port!

**Comment by NickCraver** [comment]
Going to close this out since there's been no other activity or interest here. My current assumption is people on WCF are using MiniProfiler v3.2, or are capable of sticking to that version.
