### ISSUE TITLE
InlineFormatter throws when parameter contains parameter-like string

### ISSUE THREAD

**Issue by andersjonsson** [MiniProfiler/dotnet#256]
EDIT: v4

Repro:
```
var formatter = new StackExchange.Profiling.SqlFormatters.InlineFormatter();

var parameters = new List<SqlTimingParameter>();
	
parameters.Add(new SqlTimingParameter() { DbType = "string", Name = "url", Value = "http://www.example.com?myid=1" });
parameters.Add(new SqlTimingParameter() { DbType = "string", Name = "myid", Value = "1" });

var command = @"SELECT * FROM urls WHERE url = @url OR myid = @myid";

formatter.FormatSql(command, parameters);
```

If I change the ordering of the parameter it works.

The problem is that the ParamPrefix-regex matches "?myid" from the url (that has already been inserted into commandText).

That, in turn, causes an exception on line 47 because of an invalid grouping.
A Regex.Escape around "name" on line 47 fixes the exception,
but the output will then be: 
"SELECT * FROM urls WHERE url = 'http://www.example.com1=1' OR myid = @myid"

Adding the Regex.Escape and keeping a copy of the original commandtext (for finding the parameter prefix) solves the issue.

```
var originalCommandText = commandText;

foreach (var p in parameters)
            {
                // If the parameter doesn't have a prefix (@,:,etc), append one
                var name = ParamPrefixes.IsMatch(p.Name)
                    ? p.Name
                    : Regex.Match(originalCommandText, "([@:?])" + p.Name, RegexOptions.IgnoreCase).Value;
                if (name.HasValue())
                {
                    var value = GetParameterValue(p);
                    commandText = Regex.Replace(commandText, "(" + Regex.Escape(name) + ")([^0-9A-z]|$)", m => value + m.Groups[2], RegexOptions.IgnoreCase);
                }
            }
```

Don't you just love a weird regex edge case? ;)

I'll see if I can make a PR tomorrow

**Comment by NickCraver** [comment]
Fixed in #257 changes - I'm hoping to update NuGet this week but MyGet will have the fix shortly.
