### ISSUE TITLE
Suppressing MiniProfiler per-request?

### ISSUE THREAD

**Issue by jeradrose** [MiniProfiler/dotnet#258]
We're looking for a way to store a sample number of requests (eg. 1%) to `SqlServerStorage`, so I extended `ProfilingActionFilter`, thinking that I could conditionally call `base.OnActionExecuting(filterContext)` when we actually want to log the results, something like:

    GlobalFilters.Filters.Add(new MyProfilingActionFilter());

    public class MyProfilingActionFilter : ProfilingActionFilter {
        private static readonly Random _Random = new Random();
        private const double _SampleSize = 0.1;

        public override void OnActionExecuting(ActionExecutingContext filterContext) {
            var kaggleController = filterContext.Controller as KaggleController;
            var currentUser = kaggleController.CurrentUser;

            if (_Random.NextDouble() < _SampleSize) {
                base.OnActionExecuting(filterContext);
            }
        }
    }

But I'm still seeing every request get logged. Should this work, meaning we have something else in our request lifecycle that is kicking off MiniProfiler, or is what I'm doing not the way to go?

**Comment by jeradrose** [comment]
I found a `MiniProfiler.Start()` in another area of the request lifecycle that I think was the cause. Removing this, plus adding `MiniProfiler.Start()` inside the condition got me what I needed.

Not sure if this is the best approach, and might be nice if this was an OOTB feature. Actually a bit surprised this isn't more requested, if people are using MiniProfiler storage options in production on a highly trafficked site, as it seems to cause several writes per request.

**Comment by NickCraver** [comment]
You can do this as you have (wrapping `.Start()`) or there's a built-in setting you can override: `MiniProfilerOptions.ShouldProfile` which is a `Func<HttpRequest, bool>`. For example if you're on ASP.NET Core, it'd look something like this:
```c#
services.AddMiniProfiler(options =>
{
    options.ShouldProfile = request => _Random.NextDouble() < _SampleSize;
});
```
...and pretty much the same thing for ASP.NET non-Core.

**Comment by jeradrose** [comment]
Doesn't look like non-Core supports `.ShouldProfile()` that I can see. Is there a similar/equivalent approach?

**Comment by NickCraver** [comment]
@jeradrose for non-Core you're indeed using the best way. Since ASP.NET non-Core isn't pipeline based so strictly as it is with middleware, a central hook point isn't something reasonable there (so hence no option exists).

**Comment by NickCraver** [comment]
Closing this out as you're already on the right path :)
