### ISSUE TITLE
Proper way to make it work with axios

### ISSUE THREAD

**Issue by kennethchoe** [MiniProfiler/dotnet#260]
This is related to [issue 247](https://github.com/MiniProfiler/dotnet/issues/247).

We are using Vue.js. So far we were using jQuery for ajax calls, and we want to change it into axios. 

This is how we hooked up Vuejs side with jQuery.

1. layout.cshtml - as usual

```html
@Scripts.Render("~/Scripts/bundles/jquery-3")

...

@MiniProfiler.RenderIncludes()
```

2. vue.js component, jquery-from-page.js:
```javascript
export default window.$
```

3. vue.js component who needs to make ajax call:
```javascript
import $ from './jquery-from-page'
$.ajax(...)
```

Is there a better way to do this? More importantly, how can I make mini-profiler to work with axios?

Thank you.

**Comment by NickCraver** [comment]
This is fixed in 938546ff4e4e8f31cefa983ddd0aebe1917580f5 - direct support for axios and xhr added. It'll land on MyGet shortly and I hope NuGet.org this week.
