### ISSUE TITLE
Difference between ProfiledDbConnection.InnerConnection and WrappedConnection?

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#262]
See [ProfiledDbConnection.cs](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/Data/ProfiledDbConnection.cs). `InnerConnection` and `WrappedConnection` appear to be the same. WrappedConnection has more usages, so I'd say remove InnerConnection in favor of WrappedConnection.

**Comment by NickCraver** [comment]
Fixed!
