### ISSUE TITLE
Publish new v3 packages to NuGet (including MiniProfiler.Raven)

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#263]
I'm using MiniProfiler v3 in a project and I'm having trouble getting RavenDB profiling to work. When I build StackExchange.Profiling.RavenDb.dll myself, it works fine. I have taken a look at the commit history and I saw there have been dozens of commits to the v3 branch since the last NuGet release, which was 3 years ago.

Will the newest commits on the v3 branch ever make it to a NuGet release? Or do I have to migrate to the v4 pre-release version?

**Comment by NickCraver** [comment]
Since MiniProfiler v4 is out and stable, going to close this out. We don't have build infrastructure for v3 (it was always ad-hoc) and without tests and such, I don't have confidence in any build that would be created.
