### ISSUE TITLE
tinyint is quoted in parameters list

### ISSUE THREAD

**Issue by robertmiles3** [MiniProfiler/dotnet#270]
Is there a legitimate reason that a tinyint parameter is quoted in the parameter list? For instance...

![image](https://user-images.githubusercontent.com/944302/38136928-a15968f8-33ef-11e8-99d1-cadf3684abf8.png)

I see in [SqlServerFormatter](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/SqlFormatters/SqlServerFormatter.cs#L37) that `Byte` is *not* included in the `DontQuote` list. If this is just an oversight, I don't mind adding a PR for it, but I just wanted to check first to see if it was on purpose.

**Comment by NickCraver** [comment]
@robertmiles3 almost certainly an oversight - fixed in the latest build headed to MyGet now. Thanks!
