### ISSUE TITLE
ASP.NET Core 2.1 support

### ISSUE THREAD

**Issue by sepehr1014** [MiniProfiler/dotnet#271]
This is a great library but it seems it doesn't properly work with ASP.NET Core 2.1 preview. Following the instructions, I get a 404 Not Found when opening the dashboard. The route is properly set though, since we have a catch-all rule to redirect to a SPA app ...
Are there any logs I can check to further investigate this issue?

**Comment by NickCraver** [comment]
Can you explain what you mean by "opening the dashboard"? I'm confused on whether you're referring to a single profiler result popup from the button or the overall results list.

I just installed 2.1 Preview 2 on the laptop here and upgraded the sample project without issues. If you're having trouble on latest, I need some more info to help figure this out. Let's start with your startup config if you are seeing this on the latest NuGet release :)

**Comment by NickCraver** [comment]
@sepehr1014 any update here?

**Comment by fbencosme** [comment]
@sepehr1014  I think what he meant is that when we hit for instance
http://localhost:5200/mini-profiler-resources we get a

>  Not Found:

 response, which I am also having it.

**Comment by NickCraver** [comment]
@fbencosme the root would be a 404 (we don't listen for *just* the root), does for instance `/mini-profiler-resources/results` 404?

**Comment by fbencosme** [comment]
@NickCraver Oh, I see. Now it works, thanks man!

**Comment by sepehr1014** [comment]
@NickCraver  Thanks for checking. We no longer have this issue.
