### ISSUE TITLE
Make MiniProfiler available to JavaScript code. 

### ISSUE THREAD

**Issue by Danielku15** [MiniProfiler/dotnet#272]
Sometimes you have some custom code in place on client side that you want to include in your profiling results. In our case we make custom AJAX calls to an API external to our MVC application. Currently it is not possible to easily add entries to the MiniProfiler widget manually as all functions for this are hidden. 

If would be great if the `buttonShow` function can be made public via the `MiniProfiler` JavaScript object. This way you can simply call something like the following code anywhere in your WebApp: 
```
MiniProfiler.buttonShow({
    // profile result structure
}); 
```

For now we made a small wrapper function which "copies" parts of the `buttonShow` code and workflows and it works fine. But a more official API for adding profiling results from JavaScript would be great.

**Comment by NickCraver** [comment]
@Danielku15 I've ported MiniProfiler to TypeScript so while I wouldn't treat this as a stable API (it should be tweaked a lot more), it is exposed now as a byproduct. There's a `window.MiniProfiler` you can...do things with :)

**Comment by NickCraver** [comment]
Closing this out, as it's now available :)
