### ISSUE TITLE
?popup=1 is being ignored

### ISSUE THREAD

**Issue by OskarKlintrot** [MiniProfiler/dotnet#274]
I have followed [this tutorial](http://www.lambdatwist.com/webapi-profiling-with-miniprofiler-swagger/) to get MiniProfiler up and running with Swashbuckle. It works with a [simple example project](https://github.com/OskarKlintrot/MiniProfiler-Examples/tree/master/src/MiniProfiler.Api) but not when I try to do the same on a "real" project. I have managed to pin point the issue and for some reason MiniProfiler ignores [`popup=1`](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler/MiniProfilerHandler.cs#L228-L229) if it's in the body. If I put it directly in the url (`/mini-profiler-resources/results?id=15617b40-b4f9-4fa5-b927-ef2ae38f56f7&popup=1`) it works just fine.

**Comment by NickCraver** [comment]
@OskarKlintrot can you try this with latest? It sounds like something in your pipeline is messing with the request...but I'm not sure how. Happy to help debug but I'm not sure how to without a repro here...I couldn't get this to misbehave locally (and it's been this way since pretty much the earliest days).

**Comment by NickCraver** [comment]
FWIW, I've gotten rid of the `popup` checks, as it should be using the `Accept` header and I just never cleaned it up. Done now. The others: yeah something is messing with either the form itself or the request coming in. I'd look at chrome tools and see if the form is being sent correctly in the request to `/results`...it's more likely something is happening client side than server. But both are possibilities.

**Comment by NickCraver** [comment]
Closing this out - can't do anything without more info, but recent changes here could only have helped.

**Comment by NickCraver** [comment]
@OskarKlintrot no problem! Thanks for the followup :)
