### ISSUE TITLE
"Uncaught ReferenceError: ClientTimings is not defined"

### ISSUE THREAD

**Issue by jdaigle** [MiniProfiler/dotnet#275]
Using the latest beta (MiniProfiler.Shared 4.0.0-beta.58), there is a client-side JavaScript error rendering the template if the JSON object doesn't define the `ClientTimings` property.

It looks like this is the change that broke it: https://github.com/MiniProfiler/dotnet/commit/d701ed9eb7b06222f77ec3c922e4d010061ce6b2#diff-618bcc7740b352d40061f841175227b2

I know that the client-side code is undergoing a major rewrite. Maybe it won't be an issue in then?

**Comment by NickCraver** [comment]
I just pushed the TypeScript refactor to master - build 4.0.0-beta.83 is on MyGet now, any chance you can give it a shot and confirm there's no issue?

**Comment by NickCraver** [comment]
Closing this out since NuGet has the fix :)
