### ISSUE TITLE
Publish the package to nuget

### ISSUE THREAD

**Issue by maliming** [MiniProfiler/dotnet#277]
I saw that MiniProfiler v4.0 has been released on myget. 
Microsoft has cdn acceleration for nuget, and our access to myget is very slow, which has an impact on continuous integration.
Why wasn't it posted to myget?

**Comment by NickCraver** [comment]
@maliming We test every package we release under Stack Oveflow load before pushing from MyGet to NuGet. That's happening today. It'll appear on NuGet later today :)

**Comment by NickCraver** [comment]
Pushed :)
