### ISSUE TITLE
Negative duration of step

### ISSUE THREAD

**Issue by kroleek** [MiniProfiler/dotnet#287]
Can you please help me figure out why I see this behavior (negative duration)? 
Is it somehow related to async loading done in step *CACHE: Load and set*?

![image](https://user-images.githubusercontent.com/1036504/40998925-993d9032-6909-11e8-9615-fd10bbb72991.png)

**Comment by adamjez** [comment]
I noticed this behavior when `Timing` parent was not properly determined. In my case It was due to `AsyncLocal<Timing> _head` and my bad use of `Current.Step`.

**Comment by NickCraver** [comment]
@kroleek Do you have a repro of this I can take a look at?

**Comment by NickCraver** [comment]
Going to close this out due to no repro and no more information.
