### ISSUE TITLE
utf-8 support please

### ISSUE THREAD

**Issue by codelishaohui** [MiniProfiler/dotnet#291]
url：/profiler/results-index , /profiler/results
response header:  Content-Type: text/html

if i use chinese, japanese in SQL, it can't display well. 
for example:

![tim 20180610150154](https://user-images.githubusercontent.com/2491201/41199126-4b320bd4-6cbf-11e8-8bdc-d41ea99ee762.png)

why not use  **Content-Type: text/html; charset=utf-8**  ??

**Comment by NickCraver** [comment]
Very reasonable indeed - this will happen in the next build :)

**Comment by NickCraver** [comment]
Heads up: this is now on NuGet as 4.0.119 :)

**Comment by codelishaohui** [comment]
thank you very much
