### ISSUE TITLE
Adding `show-trivial` or `show-time-with-children` breaks rendering

### ISSUE THREAD

**Issue by Buildstarted** [MiniProfiler/dotnet#292]
Version : 4.0.0 stable
.NET core SDK : 2.1.300

Adding either of the properties `show-trivial="true"` or `show-time-with-children="true"` results in a strange rendering and none of the popups show up.

![image](https://user-images.githubusercontent.com/743025/41258938-ceb0eb84-6d86-11e8-9987-edafe1750cbd.png)

Removing these properties everything works as expected. Every other property tested works fine. There are no errors in the console.

**Comment by NickCraver** [comment]
I'm missing a little context here - where are you adding these properties? My assumption was the `<mini-profiler>` tag helper in ASP.NET Core, but that's behaving fine here. Is it somewhere else?

**Comment by Buildstarted** [comment]
Sorry, yes. It's in the `_Layout.cshtml` at the bottom of the `body` tag `<mini-profiler show-time-with-children="true" show-trivial="true" />` either of those properties cause it to not render properly on the client.

**Comment by Buildstarted** [comment]
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMiniProfiler(options =>
            {
                options.IgnoredPaths.Add("scripts");
                options.IgnoredPaths.Add("css");
                options.IgnoredPaths.Add("images");
            });
        ...
        }

and 

        public async void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMiniProfiler();
        ...
        }

they're both the first calls in each section.

**Comment by NickCraver** [comment]
Hmmm, I can't repro this - in the sample projects I'm trying:
```html
<mini-profiler show-time-with-children="true" show-trivial="true" />
```
...but everything is working properly. Your setup seems fine, and the fact that it's rendering a box *at all* means you're getting the CSS/JS correctly. Is there a style conflict in the page with the `.mp-` prefix perhaps?

**Comment by Buildstarted** [comment]
ok i reproduced it in an empty project. Must be some weirdness with the latest version of asp.net core sdk? https://github.com/Buildstarted/mini-profiler-test

**Comment by NickCraver** [comment]
Excellent - pulling and testing, thanks!

**Comment by NickCraver** [comment]
Well no wonder I couldn't repro - latest doesn't have this problem, it was fixed in https://github.com/MiniProfiler/dotnet/pull/289. I want to fix a few more issues then push latest to NuGet, but builds are continuously pushed to MyGet here: https://www.myget.org/gallery/miniprofiler

**Comment by Buildstarted** [comment]
No problemo! Sorry about that. I looked at recent issues since I figured it must be new but didn't see anything that caught my eye as the problem. Thanks for your time!

**Comment by NickCraver** [comment]
I always prefer something reported twice than never at all - really appreciate the help here regardless of if it's a dupe or not :)

**Comment by NickCraver** [comment]
Heads up: this is now on NuGet as 4.0.119!

**Comment by Buildstarted** [comment]
Thanks! I noticed it earlier when I thought I would see if there was an update. :)
