### ISSUE TITLE
Parameter mapping showing wrong type for null value

### ISSUE THREAD

**Issue by StuffOfInterest** [MiniProfiler/dotnet#318]
Just updated to the 4.0.133 release via NuGet.  It appears that the parameter type display is mis-matching the type when there is a null value.  See the two screen shots below.  When the isAuthorized parameter is null the type is being set to 'nvarchar'.  When the value is 1 the type is set to 'bit' (which is correct).

Incorrect:

![image](https://user-images.githubusercontent.com/8578647/44096396-238c854c-9fa9-11e8-8d6e-4c8134bffd98.png)

Correct:

![image](https://user-images.githubusercontent.com/8578647/44096486-5db3e602-9fa9-11e8-9bfc-3bd65d3ae9f9.png)

Not sure when I'll get a chance to look into this one myself.

**Comment by NickCraver** [comment]
Hmm we don't have a test for this - taking a peek and adding one :)

**Comment by NickCraver** [comment]
I added a test for this in bee27404babe793ffc8bd6171dcec44aef65b496, but it seems to be behaving correctly, see if the latest release on MyGet fixes? Feed here: https://www.myget.org/gallery/miniprofiler

**Comment by NickCraver** [comment]
No updates here - going to close this one out as I believe it's working correctly now.
