### ISSUE TITLE
Miniprofiler.EF6 against Miniprofiler v2

### ISSUE THREAD

**Issue by agrath** [MiniProfiler/dotnet#320]
I am profiling an MVC application which uses Umbraco CMS as it's core
Umbraco (v7.*) is locked on Miniprofiler 2.1 until v8 as it has breaking changes
http://issues.umbraco.org/issue/U4-8213

The application in question also uses EF6 and I can't install Miniprofiler.EF6 because that has dependencies higher than the allowable installed dependencies of Umbraco

In dev, I have managed to make this work by:

- cloning Miniprofiler
- deleting everything from the solution except Miniprofiler.EF6
- uninstalling all nuget dependencies except EF
- installing miniprofiler 2.1 as a dependency of Miniprofiler.EF6
- *very badly* fixing some build errors

I am not comfortable with this as a solution but I can't find any other way of getting EF6 profiling working in miniprofiler2 without running two versions of miniprofiler side by side and all the hell that bindingredirects will bring me

Aside from a project rename (to differentiate between this fork and the upstream) here are the relevant actual code changes:
1) Remove DbProfilerFactory - ReplaceService - I can't satisfy the two parameters to this
2) Drop .WrappedDbProviderFactory on factory lookup
3) Drop .WrappedReader on GetDbSpatialDataReader

Here is a compare between my fork and master; 
https://github.com/MiniProfiler/dotnet/compare/master...agrath:master

Surprisingly, this actually seems to work and I have EF6 profiling running against miniprofiler 2.1 

_This is not an issue with Miniprofiler_ however as I have a need to profile EF6 and miniprofiler is already installed as part of Umbraco, It would be great if someone could review my fork and advise if the changes i've made are likely to horribly break things I don't understand ;)

**Comment by NickCraver** [comment]
I'm...a little surprised this works...

**Comment by agrath** [comment]
@NickCraver you and me both... 

That's the main reason I raised this issue because I didn't expect it to work and when it did I doubted my own sanity

**Comment by NickCraver** [comment]
Not sure there's much more info to gain here given no more interest. I'm going to close this on out to keep track of what's left TODO on MiniProfiler :)

**Comment by agrath** [comment]
@nickcraver yep all good, nothing to be gained by keeping this open
