### ISSUE TITLE
Get profiling details of nested functions without "step"

### ISSUE THREAD

**Issue by amirhmi** [MiniProfiler/dotnet#321]
Hi
 I'm using ASP Core 2.1
MiniProfiler needs some wrapping function to profile functions that are nested in another function(an action of a controller).
I wonder if it has some options to give me time of all function instead of using "step" ?

**Comment by NickCraver** [comment]
In short: nope. That's how MiniProfiler works, being as minimally invasive as possible (and zero overhead by default where you don't want it. If you want automatic profiling of all methods and such, you likely want something much heavier than MiniProfiler.
