### ISSUE TITLE
Profiling RavenDB with v4

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#324]
MiniProfiler v3 allowed us to profile RavenDB 3. However I noticed now MiniProfiler v4 doesn't mention RavenDB anymore. Was support for RavenDB dropped?

**Comment by NickCraver** [comment]
Correct - no one has shown much interest in this and I don't have the expertise to create it, but I would welcome PRs supporting it.

**Comment by RudeySH** [comment]
Alright, thanks for replying.
