### ISSUE TITLE
Unable to install MiniProfiler v4 (.net framework 4.7.2)

### ISSUE THREAD

**Issue by rubans** [MiniProfiler/dotnet#331]
I'm getting the following error when I try and install MiniProfiler to a Console App:
` ``` Install-Package : Could not install package 'Microsoft.Extensions.DependencyInjection.Abstractions 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. `
I have even tried installing .net standard 2.0 sdk but I have no idea what it's complaining about. Very frustrating, any ideas what the issue is?

**Comment by NickCraver** [comment]
I'm honestly not sure what you're hitting here...that definitely works here and should in general. Perhaps we're looking at an older NuGet client?

Which version of Visual Studio and NuGet are you using when getting that error?

**Comment by rubans** [comment]
Hi Nick,
Thanks for the reply.
I’m using VS2015 update 3 and nuget 3.4.4.1321

**Comment by NickCraver** [comment]
@rubans Can you give the latest NuGet client a try? There have been lots of fixes in this area - downloads for VS 2015 are here: https://www.nuget.org/downloads

**Comment by NickCraver** [comment]
This appears to be a general tooling issue - closing out based on current info.
