### ISSUE TITLE
CORS Issue with Angular app

### ISSUE THREAD

**Issue by sebfischer83** [MiniProfiler/dotnet#332]
Hi,

I try to get mini profiler running, it seems that everything works except I cant get the results from the server to my client (other domain) because I get `response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
How can I set the headers? Middleware and the normal CORS seems not to work here.

**Comment by NickCraver** [comment]
If more info is available, please ping me here and I'll re-open, since this is situational it's impossible to help without more to go on.

**Comment by hunterconcepts** [comment]
I'm having this same issue

**Comment by jimmyp** [comment]
I'm also having this issue.

I have an angular app running on http://localhost:4200 and loading the script from my .net core api running on http://localhost:15000

I've added the script tag to my angular app like this:

```
<script
      async="async"
      id="mini-profiler"
      src="http://localhost:15000/profiler/includes.min.js?v=4.2.1+b27bea37e9"
      data-version="4.2.1+b27bea37e9"
      data-path="http://localhost:15000/profiler/"
      data-current-id="c2a71c10-046b-49b7-9e3d-e04f779fe5e9"
      data-ids="c2a71c10-046b-49b7-9e3d-e04f779fe5e9"
      data-position="Left"
      data-scheme="Light"
      data-authorized="true"
      data-max-traces="15"
      data-toggle-shortcut="Alt+P"
      data-trivial-milliseconds="2.0"
      data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync"
    ></script>
```

But I get the following error in chrome dev tools console:
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:15000/profiler/results. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:15000/profiler/results. (Reason: CORS request did not succeed).```
