### ISSUE TITLE
The AspNetMvc5 sample (not .NET Core) is.... an AspNet Core proyect

### ISSUE THREAD

**Issue by christianarg** [MiniProfiler/dotnet#333]
Title. I've download the master, and the AspNetMvc5 sample is an AspNet Core proyect... I was expecting an Asp Net (not Core) proyect.

**Comment by NickCraver** [comment]
While it's using an SDK `.csproj` (as an experiment), it is an ASP.NET MVC 5 application...not .NET Core. What is it that you're looking for?

**Comment by NickCraver** [comment]
Hopefully the .NET team makes the SDK project work seamlessly here at some point. Glad you're up and running though :)
