### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by marcrib** [MiniProfiler/dotnet#336]
Hi, I use asp.net mvc 5 and install-packge show this error

> Install-Package : Could not install package 'MiniProfiler.Mvc5 4.0.138'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does 
> not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by NickCraver** [comment]
MiniProfiler v3 supports .NET 4.5.2, but MiniProfiler v4 does not (as it has much more improved `async` support). There are 2 options here:
1. Upgrade the target for your application to .NET 4.6.1 or higher.
2. Stick with the MiniProfiler v3 line.

While .NET 4.5.2 will be supported by Microsoft for some years to come, developing libraries on it is inherently limited as it lacks any new features. In that respect, the previous version functions as it always has, and the newest still will require a newer framework as it becomes less and less viable to support the latest features built on frameworks that don't have the things they're based on.

**Comment by NickCraver** [comment]
Closing this out since the options are above :)
