### ISSUE TITLE
Unable to get query trace for Console Application

### ISSUE THREAD

**Issue by manprit-sahota** [MiniProfiler/dotnet#340]
I have integrated Entity Framework and CodeFirstStoredProc library in my project. I want to log the queries executed by both the libraries. Previously I was using Database.Log delegate provided by EF but as I want to log query from other libraries also, I decided to integrated Miniprofiler for the same.

I used below code to get the query log in result variable:
```
MiniProfilerEF6.Initialize();
        MiniProfiler.StartNew("Test");
        using (MiniProfiler.Current.Step("Level 1"))
        {
            DbConnection spConnection = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
            ProfiledDbConnection profileSpConnection = new ProfiledDbConnection(spConnection, MiniProfiler.Current);
            using (EfDataContext db = new EfDataContext(profileSpConnection))
            {
                List<Domain.PersonEntity> data = db.Persons.ToList();
            }
            using (StoredProcedureContext db = new StoredProcedureContext(profileSpConnection))
            {
                List<GetPersonResult> data = db.GetPerson.CallStoredProc(new Domain.GetPersonParameter { IsActive = true }).ToList<GetPersonResult>();
            }
            string result = MiniProfiler.Current.RenderPlainText();
        }
        MiniProfiler.Current.Stop();
```
I expected the output query with all the details but unfortunately I am getting below result:

```
Manprit-PC at 11/15/2018 2:24:27 PM
 Test = ms
> Level 1 = ms (sql = 45ms in 12 cmds)

```
Am I missing something for the implementation?

**Comment by NickCraver** [comment]
Is `MiniProfilerEF6.Initialize();` being called before *any* EF6 usages? It must be called very early as it hooks up some bits to EF6 before usage and just happen before EF6 itself used. If that doesn't happen, you'll get the behavior you're seeing.

**Comment by NickCraver** [comment]
Closing out for cleanup - can't help without more info here.

**Comment by guillaumejay** [comment]
Hello,

I have the same issue (.net Framework 4.7), WPF Application.
     MiniProfilerEF6.Initialize is the first line in my main function.

And I'm getting that : (I'm creating/starting the profiler when the user clicks on a button)
AGP00038 at 20/11/2019 15:09:43
Activate all 328 794,3ms
>> Activation 328 770,8ms (sql = 34 525,9ms in 36824 cmds)
>> Counting 21,3ms (sql = 17,3ms in 3 cmds)

(you can see why i'm interested in getting query details...)
