### ISSUE TITLE
Document URLs?

### ISSUE THREAD

**Issue by ChristianSauer** [MiniProfiler/dotnet#342]
Hi, I spend an hour yesterday how to find the urls of Miniprofiler:
"/results-index"
"/results-list"
"/results"
Maybe you could add a quick explanation in the docs?
Or maybe add the urls under the root url (e.g. return a json element which contains these three urls in HATEOAS-style?)

**Comment by NickCraver** [comment]
These absolutely should be documented. I'll try and get to it soon or a PR would also be awesome if anyone gets to it before.

**Comment by KrisJohnstone** [comment]
@NickCraver this can be closed. I didn't reference the issue correctly in the PR to have it auto close. :(
