### ISSUE TITLE
Caller information

### ISSUE THREAD

**Issue by benjamin-hodgson** [MiniProfiler/dotnet#346]
I'd find it useful to see the `CallerLineNumber` and `CallerFilePath` in MiniProfiler traces. Has this been considered already? Would you accept a PR?

**Comment by NickCraver** [comment]
@benjamin-hodgson Any additional thoughts on the above? If not I'll close this out to cleanup, but curious what you think!

**Comment by benjamin-hodgson** [comment]
You could perhaps cache the resulting formatted strings in a `ConcurrentDictionary<(string memberName, string filePath, int lineNumber), string>` to save on allocations. There's a risk that the dictionary might get huge (although, probably not in real world conditions) so may need to do eviction.

Agree that this probably isn't the best candidate for inclusion in MiniProfiler itself. I'd expect the file path and line number to be displayed neatly in the tree, perhaps folded up by default, which obviously `StepHere` won't do since it's all just dumped into the step name. Sounds like adding them as structured data would be expensive though.
