### ISSUE TITLE
MiniProfiler no showing up in mvc5

### ISSUE THREAD

**Issue by dashenxian** [MiniProfiler/dotnet#350]
A few days ago I added Miniprofiler to the MVC5 project and worked well, but after a few days I found that it was not working, the page no longer showed Miniprofiler, I tried to create a new MVC5 project, and according to https:// Miniprofiler.com/dotnet/aspdotnet's guidance method adds Miniprofiler and sets the Global.asax, and adds "Miniprofiler.current?.Renderincludes ();" to the _layout.cshtml but without any effect

**Comment by NickCraver** [comment]
Can you show your Global setup and Razor code here?

**Comment by dashenxian** [comment]
`   
protected void Application_Start()
{
            ConfigMiniProfiler();
//....other code
}
 private static void ConfigMiniProfiler()
        {
            MiniProfiler.Configure(new MiniProfilerOptions
            {
                // Sets up the route to use for MiniProfiler resources:
                // Here, ~/profiler is used for things like /profiler/mini-profiler-includes.js
                RouteBasePath = "~/profiler",

                // Example of using SQLite storage instead
                //Storage = new SqliteMiniProfilerStorage(ConnectionString),

                // Different RDBMS have different ways of declaring sql parameters - SQLite can understand inline sql parameters just fine.
                // By default, sql parameters will be displayed.
                //SqlFormatter = new StackExchange.Profiling.SqlFormatters.InlineFormatter(),

                // These settings are optional and all have defaults, any matching setting specified in .RenderIncludes() will
                // override the application-wide defaults specified here, for example if you had both:
                //    PopupRenderPosition = RenderPosition.Right;
                //    and in the page:
                //    @MiniProfiler.Current.RenderIncludes(position: RenderPosition.Left)
                // ...then the position would be on the left on that page, and on the right (the application default) for anywhere that doesn't
                // specified position in the .RenderIncludes() call.
                PopupRenderPosition = RenderPosition.Right,  // defaults to left
                PopupMaxTracesToShow = 10,                   // defaults to 15

                // ResultsAuthorize (optional - open to all by default):
                // because profiler results can contain sensitive data (e.g. sql queries with parameter values displayed), we
                // can define a function that will authorize clients to see the JSON or full page results.
                // we use it on http://stackoverflow.com to check that the request cookies belong to a valid developer.
                ResultsAuthorize = request => request.IsLocal,

                // ResultsListAuthorize (optional - open to all by default)
                // the list of all sessions in the store is restricted by default, you must return true to allow it
                ResultsListAuthorize = request =>
                {
                    // you may implement this if you need to restrict visibility of profiling lists on a per request basis
                    return true; // all requests are legit in this example
                },

                // Stack trace settings
                StackMaxLength = 256, // default is 120 characters

                // (Optional) You can disable "Connection Open()", "Connection Close()" (and async variant) tracking.
                // (defaults to true, and connection opening/closing is tracked)
                TrackConnectionOpenClose = true
            }
   // Optional settings to control the stack trace output in the details pane, examples:
   .ExcludeType("SessionFactory")  // Ignore any class with the name of SessionFactory)
   .ExcludeAssembly("NHibernate")  // Ignore any assembly named NHibernate
   .ExcludeMethod("Flush")         // Ignore any method with the name of Flush
   .AddViewProfiling()              // Add MVC view profiling (you want this)
                                    // If using EntityFrameworkCore, here's where it'd go.
                                    // .AddEntityFramework()        // Extension method in the MiniProfiler.EntityFrameworkCore package
   );

            // If we're using EntityFramework 6, here's where it'd go.
            // This is in the MiniProfiler.EF6 NuGet package.
            MiniProfilerEF6.Initialize();
        }

        protected void Application_BeginRequest()
        {
            // You can decide whether to profile here, or it can be done in ActionFilters, etc.
            // We're doing it here so profiling happens ASAP to account for as much time as possible.
            if (Request.IsLocal) // Example of conditional profiling, you could just call MiniProfiler.StartNew();
            {
                MiniProfiler.StartNew();
            }
        }

        protected void Application_EndRequest()
        {
            MiniProfiler.Current?.Stop(); // Be sure to stop the profiler!
        }

page:
@using StackExchange.Profiling;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @MiniProfiler.Current.RenderIncludes()
</head>
<body>
</body>
</html>

`

**Comment by dashenxian** [comment]
```
        protected void Application_Start()
        {
            ConfigMiniProfiler();
//...other code
}
        private static void ConfigMiniProfiler()
        {
            MiniProfiler.Configure(new MiniProfilerOptions
            {
                RouteBasePath = "~/profiler",

                PopupRenderPosition = RenderPosition.Right, 
                PopupMaxTracesToShow = 10,                  
                ResultsAuthorize = request => request.IsLocal,
                
                ResultsListAuthorize = request =>
                {
                    return true; 
                },
                StackMaxLength = 256, 

                TrackConnectionOpenClose = true
            }
           .ExcludeType("SessionFactory")  
           .ExcludeAssembly("NHibernate")  
           .ExcludeMethod("Flush")        
           .AddViewProfiling()             

           );
            MiniProfilerEF6.Initialize();
        }

        protected void Application_BeginRequest()
        {
            if (Request.IsLocal) 
            {
                MiniProfiler.StartNew();
            }
        }

        protected void Application_EndRequest()
        {
            MiniProfiler.Current?.Stop(); 
        }
```

**Comment by dashenxian** [comment]
```
@using StackExchange.Profiling
@{
    Layout = null;
}
@using iLIS.WX.Infrastructure;

<!DOCTYPE html>
<html>
<head>
..other code
    @{
        MiniProfiler.Current?.RenderIncludes(); 
        }
</head>
<body>
</body>
</html>
```

**Comment by dashenxian** [comment]
web.config:
```
<handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
     <add name="MiniProfiler" path="profiler/*" verb="*" type="System.Web.Routing.UrlRoutingModule" resourceType="Unspecified" preCondition="integratedMode" />
    </handlers>
```

**Comment by dashenxian** [comment]
![image](https://user-images.githubusercontent.com/18696614/50463105-76083480-09c4-11e9-805f-08e3f9a2e0e3.png)
I created another MVC5 project to copy the configuration of the previous project to the newly created project, which will work correctly this time. I don't know what the problem is, chrome debug saw that the profiler folder and the corresponding JS file were not loaded

**Comment by NickCraver** [comment]
It took me a few reads here - the problem is in syntax for Razor.

This right here is throwing away the HTML it renders:
```
@{
    MiniProfiler.Current?.RenderIncludes();
}
```
Instead, you want to print that result, like this:
```
@(MiniProfiler.Current?.RenderIncludes())
```

**Comment by dashenxian** [comment]
Thanks a lot,I will try it,but why?

**Comment by NickCraver** [comment]
@dashenxian it's just Razor and how it works. For example:
```c#
@{ Html.Partial("MyView", MyModel); }
```
will execute the view and render the HTML, *but it won't do anything with it. Anything following the `@` is destined for output, where as `@{ }` is a C# code block. To render something, it's:
```c#
@Html.Partial("MyView", MyModel)
```

**Comment by dashenxian** [comment]
![rtx](https://user-images.githubusercontent.com/18696614/51809123-3e98ea80-22d8-11e9-8322-5997b6aa94bf.png)
It doesn't work.

**Comment by dashenxian** [comment]
I added that code deletion today, and it seems like it's okay again.
@(MiniProfiler.Current?.RenderIncludes())
Thanks a lot
