### ISSUE TITLE
SQL dump in Dapper console application demo

### ISSUE THREAD

**Issue by marcocastellani** [MiniProfiler/dotnet#353]
I'm trying to understand how is possibile to dump SQL statements produced by dapper in the console.
I take the the dotnet/samples/Samples.Console/ but I cannot understand how to do it.

**Comment by NickCraver** [comment]
This isn't a common thing I've seen asked for, but you can setup a `ProfiledDbConnection` and implement your own `IdbProfiler` passed into it...and this implementation can just `Console.Write...` whatever you want there. Does that make sense?
