### ISSUE TITLE
Cannot insert the value NULL into column 'RowId'

### ISSUE THREAD

**Issue by erangaapp** [MiniProfiler/dotnet#359]
**I have got this error when I enable the mini profiler for my web site. What should be the reason?**
```
Cannot insert the value NULL into column 'RowId', table 'dbo.MiniProfilers'; column does not allow nulls. INSERT fails. 
	 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) 
	   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) 
```

**Comment by NickCraver** [comment]
I haven't seen this reported before - can you post your configuration and details? ASP.NET, ASP.NET Core? Which version?

**Comment by NickCraver** [comment]
@erangaapp Any info you can provide here?

**Comment by erangaapp** [comment]
Hi @NickCraver ,

This is because of the invalid primary key option on our table structure for MiniProfilers. The thing needed to set RowId as a primary key and set auto increment true. That way this issue was fixed. :) 👍 Thank you.
