### ISSUE TITLE
An example of how to use MiniProfiler.Providers.Redis?

### ISSUE THREAD

**Issue by Levitikon217** [MiniProfiler/dotnet#375]
Is there any documentation for profiling Redis using MiniProfiler.Providers.Redis? Preferably for a dotnet core setup.

**Comment by NickCraver** [comment]
That provider doesn't profile Redis, but *stores MiniProfilers in Redis*. Which Redis provider are you using though? There may be an example for that specific provider I can show how to wire up, if I'm familiar with it.

**Comment by NickCraver** [comment]
@Levitikon217 any update here?
