### ISSUE TITLE
Database initializer GetPendingMigrations throws nullpointer.

### ISSUE THREAD

**Issue by Orion-TLN** [MiniProfiler/dotnet#380]
I have some code in my DatabaseContext that adds a filter to some columns:

    this.Filter(context => context.Pages, page => page.Children, page => page.DeletedDate == null);

When this code is hit the first time the miniprofiler throws an exception when it shouldn't in my opinion:

    public void InitializeDatabase(WebsiteContext context)
        {
            using (new TransactionScope(TransactionScopeOption.Suppress))
            {
                if (!context.Database.Exists())
                    throw new ConfigurationErrorsException("Database does not exist");
                if (!context.Database.CompatibleWithModel(true))
                    throw new InvalidOperationException("The database is not compatible with the entity model.");
            }

            var configuration = new Migrations.Configuration
            {
                TargetDatabase = new DbConnectionInfo("WebsiteDbConnectionString")
            };
            var migrator = new DbMigrator(configuration);
            try
            {
                var pendingMigrations = migrator.GetPendingMigrations();
                if (pendingMigrations?.Any() == true)
                {
                    throw new InvalidOperationException("There are pending migrations. Please run update-database manually.");
                }
            }
            catch (NullReferenceException)
            {
                // Exception thrown because mini profiler does not have a profiler yet.
            }
        }

Using a try and catch I can let my code continue running. However I want to fix this error. I tried moving my code to the PreApplicationStartMethod bit. But that has no effect either. How can I fix this issue?

The exception:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

The stacktrace:
   at StackExchange.Profiling.Data.ProfiledDbConnection.get_State()
   at System.Data.Entity.Internal.RepositoryBase.CreateConnection()
   at System.Data.Entity.Migrations.History.HistoryRepository.QueryExists(String contextKey)
   at System.Data.Entity.Migrations.History.HistoryRepository.Exists(String contextKey)
   at System.Data.Entity.Migrations.History.HistoryRepository.GetPendingMigrations(IEnumerable`1 localMigrations)
   at xxxx.ValidateDatabaseInitializer.InitializeDatabase(WebsiteContext context) in xxxx\DatabaseInitializers\ValidateDatabaseInitializer.cs:line 28
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)

I'm using .NET Framework and Entity Framework 6.2.

**Comment by NickCraver** [comment]
How are you creating the `ProfiledDbConnection`? A null ref there indicates the connection that was passed into the constructor of `ProfiledDbConnection(DbConnection connection, IDbProfiler profiler)` was null, and accessing the first thing on it is going boom.

This may just be another version of #243 though (see issue for details). It's ultimately a bug in EF 6.2 that won't be fixed until 6.3 is out later this year.

**Comment by Orion-TLN** [comment]
I did figure out it depends on the MiniProfiler version. Using:
<package id="MiniProfiler.EF6" version="3.0.11" targetFramework="net471" />
I do not get the error.

So when I use the following packages:

<package id="MiniProfiler" version="4.0.165" targetFramework="net471" />
<package id="MiniProfiler.EF6" version="3.0.11" targetFramework="net471" />
<package id="MiniProfiler.Mvc5" version="4.0.165" targetFramework="net471" />
<package id="MiniProfiler.Shared" version="4.0.165" targetFramework="net471" />

I do not get the error when launching my application.

**Comment by Orion-TLN** [comment]
I tried removing the code that threw the exception in my WebsiteContext but then it starts throwing NullPointers in other places in my code.

**Comment by NickCraver** [comment]
I'm not sure what to tell you on this one - Yes, EF 6.2 is broken. It's a known issue. It won't be fixed by the EF Core team until EF Core 6.3. Or, you can use EF Core...but yep: this is a bug in how they handle the lifetime of some objects, and it was broken in the 6.2 release.

**Comment by NickCraver** [comment]
I'm going to close this out since it's a framework issue, they'll need to fix in in 6.3.
