### ISSUE TITLE
How to save MiniProfiler data to Sql Database?

### ISSUE THREAD

**Issue by GamiDroid** [MiniProfiler/dotnet#381]
I'm using the NuGet Package 'MiniProfiler.AspNetCore.Mvc' on my ASP .Net Core 2.2. 
I want write the data from the MiniProfiler directly to my Sql database. 
In the example in the startup.cs is something writen about `options.Storage = new SqlServerStorage("");`
SqlServerStorage does not seem to be available. 

Is there another way to save the data to the database or do I need to include something else to get it to work?

**Comment by KrisJohnstone** [comment]
Double check that you've installed the required provider and that its referenced:

Link to package:
https://www.nuget.org/packages/MiniProfiler.Providers.SqlServer/

**Comment by GamiDroid** [comment]
Thank you @KrisJohnstone now I can use the SqlServerStorage. 
Now I'm getting een SqlException that my sql database tables are invalid. 

In the startup I'm using this option:
```C#
options.Storage = new SqlServerStorage("SqlConnectionString", "MiniProfilers", "MiniProfilerTimings", "MiniProfilerClientTimings");
```
This are my Sql database representations:

```C#
    public partial class MiniProfilerClientTimings
    {
        public int RowId { get; set; }
        public Guid Id { get; set; }
        public Guid MiniProfilerId { get; set; }
        public string Name { get; set; }
        public decimal Start { get; set; }
        public decimal Duration { get; set; }
    }

    public partial class MiniProfilers
    {
        public int RowId { get; set; }
        public Guid Id { get; set; }
        public Guid? RootTimingId { get; set; }
        public DateTime Started { get; set; }
        public decimal DurationMilliseconds { get; set; }
        public string User { get; set; }
        public bool HasUserViewed { get; set; }
        public string MachineName { get; set; }
        public string CustomLinksJson { get; set; }
        public int? ClientTimingsRedirectCount { get; set; }
    }

    public partial class MiniProfilerTimings
    {
        public int RowId { get; set; }
        public Guid Id { get; set; }
        public Guid MiniProfilerId { get; set; }
        public Guid? ParentTimingId { get; set; }
        public string Name { get; set; }
        public decimal DurationMilliseconds { get; set; }
        public decimal StartMilliseconds { get; set; }
        public bool IsRoot { get; set; }
        public short Depth { get; set; }
        public string CustomTimingsJson { get; set; }
    }
```

Is this correct or do I need to change something?

**Comment by KrisJohnstone** [comment]
You're missing one or two fields from your models. Having said that, you should be able to do something like the following, without needing to create models of the tables:

`var profiler = MiniProfiler.StartNew("Something");

using(profiler.Step("CheckCache"))
{
    //insert some code here
}

await MiniProfiler.Current.Storage.SaveAsync(profiler);`

I *think* the above is correct, I'm not at work at present so can't check.

**Comment by NickCraver** [comment]
Have you created the tables in SQL Server? MiniProfiler will use the tables, but not create them (since it'd require elevated permissions to do so).

If you are giving your app permissions to create the storage, you can do what the tests do (one time):
```c#
var storage = new SqlServerStorage("SqlConnectionString"); // your existing args are the default table names, so this is equivalent
storage.CreateSchema();
```
Or, you can generate the scripts it uses and spit them out to go run manually in whatever place you do database migrations. It's a `List<string>` of commands to run from:
```c#
foreach (var cs in storage.TableCreationScripts)
{
    Console.WriteLine(cs);
}
```

**Comment by NickCraver** [comment]
Any update here?

**Comment by zinov** [comment]
> ```cs
> CreateSchema
> ```

Is not longer a valid method, how should I proceed in case I want to use the fluent option?

**Comment by KrisJohnstone** [comment]
> ```cs
> ```cs
> CreateSchema
> ```
> 
> 
> 
> Is not longer a valid method, how should I proceed in case I want to use the fluent option?
> ```

What makes you think its no longer valid? Also this should probably be a new Issue.

https://github.com/MiniProfiler/dotnet/blob/master/tests/MiniProfiler.Tests/Storage/SqlServerStorageTests.cs

**Comment by zinov** [comment]
```

            services.AddMiniProfiler(options =>
            {
                options.UserIdProvider = (request) => request.HttpContext.User.Identity.Name;
                options.Storage = new SqlServerStorage(connectionMiniProfiler);
                **options.Storage.CreateSchema(); // this is not an available method**
            }).AddEntityFramework(); //to track all the sql access we do with EntityFrameworkCore

```

**Comment by dharmeshsharma** [comment]
Yes There is no "CreateSchema()" method as test case
