### ISSUE TITLE
IAsyncStorage implementation in .Net Core 3.0

### ISSUE THREAD

**Issue by satishviswanathan** [MiniProfiler/dotnet#383]
I have an implementation of IAsyncStorage  for my Miniprofiler and since the upgrade to .Net Core 3.0 I'm seeing that the Save() is getting invoked instead of SaveAsync(). 

Any help on this issue is appreciated

**Comment by NickCraver** [comment]
Can you share your setup/config? What doed your `Startup.cs` (or wherever your config is) look like?

**Comment by NickCraver** [comment]
I can't help here without more info, so going to close this out.
