### ISSUE TITLE
Does this work with an ASP.NET (not MVC) application using .NET framework 4.5.2?

### ISSUE THREAD

**Issue by awerber** [MiniProfiler/dotnet#384]
I'm trying to install the Nuget package and get the following error: Could not install package 'MiniProfiler 4.0.165'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

So, I assume I'm contacting the package author.

Thank you for any help with this,
Andy

**Comment by NickCraver** [comment]
The minimum supported version for MiniProfiler 4.x is .NET 4.6.1 - so you can either target a higher .NET Framework version, or use MiniProfiler v3 :)

**Comment by awerber** [comment]
Thank you Nick. I was able to use version 3. But, I have a new question. I read over the documentation. I don't see where the output of the profiler goes. I set up the Global.asax.cs with the minimal amount of code. I wrapped a using around some code in the same project as the Global.asax.cs file. I ran the method with the using and made sure the code was reached. But I don't see any output anywhere.

Thanks for any help with this.

**Comment by NickCraver** [comment]
@awerber Check out `MiniProfiler.RenderResults()`, you'll want to do call in your master view (or whichever place you wish).

**Comment by awerber** [comment]
Thank you again for responding. I don't see this method, maybe because I'm using version 3.2.0.157? I do see a method named RenderIncludes. I tried putting a call to this method in a page_load event, but nothing appeared to happen.

One new question, when I do get this to work, where do I find the results? Do they go into a file? I get the impression that the results will pop up in a browser window. Is that correct?

Thanks for any help.

**Comment by NickCraver** [comment]
@awerber Gotcha - you'll want to call `.RenderIncludes()` in your master view, probably just before `</body>`, it'll render the JavaScript tag that fetches your profiler results and shows them in the corner :)

**Comment by awerber** [comment]
Thank you again. I can see the JavaScript but not the results. I created a variable with a Get that calls .RenderIncludes, then I have this at the bottom of the ASPX page:

 </form>
	<p><%= ProfilerResult %></p>
</body>
</html>

When I use a debugger, I can see the script in the paragraph. What else do I need to do?

Thanks again.

**Comment by NickCraver** [comment]
Can you show me an example of the script output? Does it have any IDs in it?

**Comment by NickCraver** [comment]
Can't help without more info here - going to close this out but happy to help if there's more info to go on!
