### ISSUE TITLE
NullReferenceException in ExecuteNonQueryAsync

### ISSUE THREAD

**Issue by dbolin** [MiniProfiler/dotnet#385]
Nuget Package Version 4.0.165
.Net core version 3.0.100-preview5-011568
Running an asp.net core app with target framework netcoreapp3.0

Not sure if this is a supported use case, but what's happening is a profiled database connection is created during a request, and in some cases the connection is passed off to a hosted service which uses it to perform some additional work before closing it.  The request can finish before the hosted service closes the connection.

Top of the stack is MiniProfilerExtensions.cs:100
```
        public static CustomTiming CustomTimingIf(this MiniProfiler profiler, string category, string commandString, decimal minSaveMs, string executeType = null, bool includeStackTrace = true)
        {
            if (profiler == null || profiler.Head == null || !profiler.IsActive) return null;

            var result = new CustomTiming(profiler, commandString, minSaveMs, includeStackTrace: includeStackTrace)
            {
                ExecuteType = executeType,
                Category = category
            };

            // THREADING: revisit
            profiler.Head.AddCustomTiming(category, result);        <----- NRE here

            return result;
        }
```

**Comment by NickCraver** [comment]
Does this happen intermittently? We're checking if `profiler.Head` is present a few lines up...so the only thing I can imagine here is it's being dropped on the floor in this very narrow window. Is that the case, intermittent behavior? Or is it consistently throwing?

If it is intermittent, we could add another null guard there at the last second...but want to make sure we have the right problem first!

**Comment by dbolin** [comment]
Definitely intermittent, but happens surprisingly often (I saw it something like 30% of the time) given how close the line that throws is to the null checks.

**Comment by NickCraver** [comment]
This is fixed in https://github.com/MiniProfiler/dotnet/commit/6cdf1c79ae39989cdc5abe62518096cfdca80e61 (available [on MyGet](https://www.myget.org/gallery/miniprofiler now as 4.0.171). I'll poke around other issues and get it to NuGet after other current issues are resolved and in for a release.
