### ISSUE TITLE
ASP.Net Core results page - Only showing one result

### ISSUE THREAD

**Issue by worldspawn** [MiniProfiler/dotnet#387]
Hi, i'm using miniprofiler in aspnet core mvc and I'm noticing that the results page is only ever showing the result from the most recent request. Is this by design? Is there someway to stack results up (so i can compare them)?

**Comment by NickCraver** [comment]
Can you share your configuration and startup? It sounds like the cache mechanism is possibly off here. Knowing which store and config you're using would help.

**Comment by worldspawn** [comment]
Startup is:

``` csharp
public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
```

In ConfigureServices i have

``` csharp
services.AddMiniProfiler(o =>
                o.RouteBasePath = "/profiler");
```
Its the first service that is added.

In Configure I have
`app.UseMiniProfiler();` before `app.UseMvc()`

**Comment by worldspawn** [comment]
@NickCraver did you need anything else?

**Comment by leofmoura** [comment]
Hi, I'm facing same issue or something close to.

When I go to http://localhost:53013/profiler, I get a Not Found: 
If I go to http://localhost:53013/profiler/results I get only the latest.

Is there a way to get a list of profiling calls?

Thanks! =)

**Comment by NickCraver** [comment]
Sorry I missed earlier replies here - there is a list route, yes! It's `/profiler/results-index` in your case.

**Comment by NickCraver** [comment]
Tossing up some doc improvements in #474 so that these are in the docs as they really should have been :)
