### ISSUE TITLE
Changing the default settings for Newtonsoft.Json breaks MiniProfiler

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#390]
I just ran into an issue where I broke MiniProfiler by changing the default settings of Newtonsoft.Json. To be specific, I used the following configuration:

    JsonConvert.DefaultSettings = () => new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };

MiniProfiler's script expects properties to be serialized as PascalCase, so changing it to camelCase breaks it. The error I got in the console was:

    Uncaught TypeError: Cannot read property 'DurationMilliseconds' of undefined

To fix this issue, MiniProfiler should stop relying on the default settings of Newtonsoft.Json. Instead, use a local new instance of `JsonSerializerSettings`.

**Comment by NickCraver** [comment]
This should already be fixed in latest - what NuGet version are you using?

**Comment by RudeySH** [comment]
My bad, I wasn't on the latest version yet.
