### ISSUE TITLE
Initialization failure with IE8 compatibility on in browser

### ISSUE THREAD

**Issue by StuffOfInterest** [MiniProfiler/dotnet#391]
I’m updating an older ASP.NET MVC application from MiniProfiler 3 to MiniProfiler 4.  This app took advantage of some older behavior in Internet Explorer, and would be hard to change at this stage in its lifecycle.  Several years ago the application had to be locked to Internet Explorer 8 compatibility to operate.  This was done with a meta tag like this:

```<meta http-equiv=”X-UA-Compatible” content=”IE=EmulateIE8” />```

Unfortunately, with this meta tag in place, MiniProfiler always throws this error when a page loads:

```Error: Object doesn’t support property or method ‘addEventListener’```

The error traces back to a spot in ‘includes.min.js’ with this text:

```f.addEventListener(“DOMContentLoaded”,ni)```

This is a line in the jQuery that is embedded with the MiniProfiler initialization.  Unfortunately, the debugger in Internet Explorer won’t let me trace back to what called this.  Also, looking in the MiniProfiler source, it appears the custom code was all done in TypeScript.  I wasn’t able to find a clear place where the above was called.

MiniProfiler 3 worked fine with the older IE8 compatibility.  Would it be possible to change the MiniProfiler 4 initialization to detect older browsers and use an initialization that will work?

**Comment by ArtOfCode-** [comment]
IE8? Not IE latest at IE11, but IE*8*? It's now just over 10 years old - I'm surprised you've managed to keep things compatible for this long. Ultimately, if you must rely on an outdated browser, you will have to accept the compromise of likewise outdated packages to support it.

**Comment by NickCraver** [comment]
In short, we'd have to drop back to jQuery 1.x here instead of anything higher than 2.0 (where IE < 9 support was dropped). This just isn't reasonable to support anymore. IE8 is over a decade old and the operating systems with it aren't supported either.

If it was even remotely *reasonable* to fix I'd be amenable, but it's just not these days. However, MiniProfiler v3 will continue to work :)

**Comment by StuffOfInterest** [comment]
Understand.  This app is a special case.  It was written nine years ago.  It does some things that would not pass muster in a code review today.  

The good news is that the app is going into rewrite now and the old version will be retired next year.  The bad news is that I can't roll back to MiniProfiler 3 without doing the same to over three dozen apps that rely on the same set of common libraries and services.  Looks like that one app may just have to live without MiniProfiler for a time.
