### ISSUE TITLE
Profiling EF6 when MiniProfiler.Current is null (ConfigureAwait(continueOnCapturedContext: false))

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#392]
Consider the following code:

```C#
Debug.WriteLine(MiniProfiler.Current != null); // true, MiniProfiler.Current is NOT null

await Task.Delay(1000).ConfigureAwait(continueOnCapturedContext: false);

Debug.WriteLine(MiniProfiler.Current != null); // false, MiniProfiler.Current is null!
```

The continuation after `await` won't run in the original context, so `MiniProfiler.Current` is null. I can mostly work around this by using assigning the current instance to a field or variable before `await`, e.g. `var profiler = MiniProfiler.Current;`.

However, I don't know how to keep profiling EF6/SQL queries when MiniProfiler.Current is null. SQL timings are not showing up when I'm using `continueOnCapturedContext`, so I assume the implementation is attempting to use `MiniProfiler.Current` internally.

Is there a way I can instruct my `DbContext` to use a captured instance of MiniProfiler, instead of `MiniProfiler.Current`?

**Comment by NickCraver** [comment]
hmmm indeed this wouldn't work right - currently `EFProfiledDbProviderServices` creates commands via:
```c#
        protected override DbCommandDefinition CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree)
        {
            var cmdDef = _tail.CreateCommandDefinition(providerManifest, commandTree);
            var cmd = cmdDef.CreateCommand();
            return CreateCommandDefinition(new ProfiledDbCommand(cmd, cmd.Connection, MiniProfiler.Current));
        }
```
...instead of the profiler that was passed to the `ProfiledDbConnection`. I'll take a peek and see if we can reasonably using the existing reference here. e.g. something like this:
```c#
        protected override DbCommandDefinition CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree)
        {
            var cmdDef = _tail.CreateCommandDefinition(providerManifest, commandTree);
            var cmd = cmdDef.CreateCommand();
            var profiler = cmd.Connection is ProfiledDbConnection profiledConn ? profiledConn.Profiler : MiniProfiler.Current;
            return CreateCommandDefinition(new ProfiledDbCommand(cmd, cmd.Connection, profiler));
        }
```
...but there may be a better implementation, let me look.

**Comment by RudeySH** [comment]
That would do the job for me.

A different approach would be to allow different profiler providers in different scopes. I don't know the details of the current way profiler providers work, but to my understanding you can only configure one, globally. If I could set MiniProfiler to use a different profiler provider in certain contexts, I could solve my issue by implementing a custom profiler provider and use it when needed.

**Comment by NickCraver** [comment]
You can configure many, `Current` just determines what `MiniProfiler.Current` does...but you can pass one around anywhere. In the EF case, the one passed to `ProfiledConnection` when it's created *should* be the one used for everything on that path...but in this case it wasn't. It's now fixed up and on MyGet in 4.0.177 and later - feed link: https://www.myget.org/feed/Packages/miniprofiler - I'm going to look at a few more issues before a NuGet bump here, but it's available now if you want to give it a go!

**Comment by NickCraver** [comment]
@RudeySH any chance you were able to test the preview package and see if you're all set?

**Comment by NickCraver** [comment]
MiniProfiler 4.0.180 packages are up on NuGet now, so I'm going to close this out :)

**Comment by RudeySH** [comment]
After updating to v4.0.180 the issue does not appear to be fixed.

I put the following code in an MVC action:

```C#
var x = dbContext.Apps.Count();
await Task.Delay(100).ConfigureAwait(false);
var y = dbContext.Apps.Count();
```

Only the first query shows up in the results panel.

![image](https://user-images.githubusercontent.com/3918757/62955060-bd76f000-bdf0-11e9-9483-7441815dc595.png)

Everything after `await` is not being profiled.

Perhaps I'm missing something? Do I need to explicitly pass in a ProfiledDbConnection somewhere? All I'm currently doing is: `MiniProfilerEF6.Initialize();`.

**Comment by NickCraver** [comment]
@RudeySH The profiler looks correct to me - can you try any _other_ query after the await? Remember we're dealing with a data context here - it _shouldn't_ need to fetch that data twice one that instance of the context already has it loaded.

**Comment by RudeySH** [comment]
I have verified it isn't a caching issue. I just realized I'm having this issue because I'm explicitly passing in an `existingConnection` in my DbContext's constructor, like so:

```C#
public ApplicationDbContext() // constructor
    : base(existingConnection: new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString),
           contextOwnsConnection: false)
{
    ...
}
```

The issue disappears when I stop passing an existing SqlConnection. But, the reason I'm explicitly passing a SqlConnection here is because of #243 ... TL;DR: Entity Framework 6.2 has a bug and forces me pass an existing SqlConnection.

Could MiniProfiler fully support this scenario? Or is there something inherently wrong with passing a SqlConnection in the constructor?

For what it's worth, updating to EF6.3 allows me to stop passing an existing SqlConnection, thus allows me to work around the issue, but I'm not able to update to EF6.3 yet.

**Comment by RudeySH** [comment]
Years later, I ran into this issue again because I added `.ConfigureAwait(false)` to a bunch of awaits in my code. I just realized I was still passing the connection into the base constructor of my DbContext. For future readers: the base call in the constructor is no longer necessary, at least not when using the latest version of Entity Framework 6.
