### ISSUE TITLE
Any documentation on how to profile apps in Kubernetes?

### ISSUE THREAD

**Issue by egopher** [MiniProfiler/dotnet#398]
Hello! 

Running .net core app and sql server in Kubernetes, looking to find a way to collect performance data in production-like environment deployed in cloud. 

Any docs on how-to attach miniprofiler to the remote process or profile in Kubernetes? There is no docker image I am aware of. 

A warm thank you.

**Comment by NickCraver** [comment]
I'm a little confused by the request - MiniProfiler run inside the application, so it won't care what the container or platform is. If you're looking to have external visibility, it's not really made for that _but_ there are some things you can do. For example, by storing the MiniProfilers all to the same shared place (e.g. a SQL, Redis, or whatever server), you can view them all from any app configured to use that same source.

It _sounds_ like you may be after a general monitoring system though, if that's the case then per-request/per-op MiniProfiler is likely just not a good fit for what you're trying to accomplish.
