### ISSUE TITLE
just show the duration info without the sql detail link

### ISSUE THREAD

**Issue by GodkillOdd** [MiniProfiler/dotnet#402]
after i complete the confirguration for Miniporfiler, i just can see the duration, with children and from start info
![issue](https://user-images.githubusercontent.com/33819014/60878128-bb5dc680-a271-11e9-8243-345dfaf9399e.JPG)
. and i have add the code **services.AddMiniProfiler(o =>{o.RouteBasePath = "/profiler";}).AddEntityFramework();** in my starup.cs. do i miss some other confiruations? please give me some advices.

**Comment by NickCraver** [comment]
How are you connecting to SQL? The `ProfiledDbConnection` must be used in order to get timings attached to a profiler :)

**Comment by GodkillOdd** [comment]
@NickCraver thanks for your comments.  but what i am profiling is EF Core, and according to the documents [https://miniprofiler.com/dotnet/HowTo/ProfileEFCore](url) i just need to add this **AddEntityFramework()**. is this **ProfiledDbConnection** you mentioned necessary for EF Core?

**Comment by NickCraver** [comment]
Yep, sorry I missed the reply here - that will add it. Is it possible you're querying a data context already in memory and not actually hitting a database? I've seen this confusion a few times - first we need to verify you're _actually_ hitting a database server - if that's the case we've got something odd I haven't seen before here.

**Comment by NickCraver** [comment]
Closing out due to inactivity, but if the above is not the case please ping and I'll reopen!
