### ISSUE TITLE
Docs 404 on "the usual `using` wrap method for"

### ISSUE THREAD

**Issue by lol768** [MiniProfiler/dotnet#405]
https://miniprofiler.com/dotnet/AspDotNetCore

Links to https://miniprofiler.com/dotnet/TODO

**Comment by NickCraver** [comment]
And you almost got issue 404 too :) Thank you, all fixed up!

**Comment by lol768** [comment]
Hahaha, so close yet so far.

Thanks a bunch as always @NickCraver
