### ISSUE TITLE
MiniProfiler crashes the app when exception is thrown from a storage provider

### ISSUE THREAD

**Issue by mvacha** [MiniProfiler/dotnet#409]
### Issue
MiniProfiler does not catch exceptions thrown from a storage provider, so they end-up being propagated to the caller app and therefore can crash the app that uses MiniProfiler (or a request in a web api).

I've encountered the issue when using PostgreSqlStorage, but from looking at the source code of other storage providers I believe they are also affected.

### Workaround
I've created a `SanitizedDefaultProfilerProvider` that catches any exceptions thrown in the Save[Async] method and just writes it to the logger (which also makes the configuration a bit more ugly)
```
public SanitizedDefaultProfilerProvider(ILogger<SanitizedDefaultProfilerProvider> logger)
            => _logger = logger;
...
        protected async Task SaveAsync(MiniProfiler profiler)
        {
           ....
            try
            {
                await storage.SaveAsync(profiler).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unable to save trace from MiniProfiler.");
            }
        }
```
But I don't think that resolves the issues completely as any method in `IAsyncStorage` can throw an exception due to various issues with DB (server down/invalid credentials/nonexisting...) and therefore crash the app. Similar issue: #358.

**Comment by NickCraver** [comment]
I'm putting some guards against this in #486, with the ability to log the errors if desired :) Thanks for the report!
