### ISSUE TITLE
MiniProfileOptions.ResultsAuthorize cannot execute async code

### ISSUE THREAD

**Issue by ChristopherHaws** [MiniProfiler/dotnet#417]
This is related to #354, however I am not able to use synchronous code here without duplicating the logic for the authorization. Specifically we are using policy based authorization using `IAuthorizationService` which only provides an async method. We are having to force the execution to be synchronous (which is working fine because behind the scenes there really isnt anything that requires the call to be async).

```csharp
services
    .AddMiniProfiler(x =>
    {
        x.ResultsAuthorize = request => request.HttpContext.RequestServices.GetRequiredService<IAuthorizationService>().AuthorizeAsync(request.HttpContext.User, "CanProfile").Result.Succeeded;
    });
```

**Comment by NickCraver** [comment]
Please see #472 - it's merged and will be in the 4.2.x release :)
New equivalent APIs to support async goodness:
- `MiniProfilerOptions.ResultsAuthorizeAsync`
- `MiniProfilerOptions.ResultsListAuthorizeAsync`
