### ISSUE TITLE
MiniProfiler 3 breaks TransactionScope and SynchronizationContext flow

### ISSUE THREAD

**Issue by gaevoy** [MiniProfiler/dotnet#419]
`MiniProfiler` 3 affects on how `TransactionScope` and `SynchronizationContext` flow when `ProfiledDbConnection`, `AsyncPump`, `ConfigureAwait(false)` are used. I managed to reproduce the behavior difference in [MiniProfilerReproductionTests](https://github.com/gaevoy/Gaev.Blog.Examples/tree/2.6.0/Gaev.Blog.Examples.MiniProfiler3Bug/MiniProfilerReproductionTests.cs).

`MiniProfiler` 4 does not have such side effect and works as expected.

More details I tried to describe in [blog post](https://gaevoy.com/2019/09/09/miniprofiler-bug.html).

**Comment by NickCraver** [comment]
My suggestion would be to upgrade to MiniProfiler v4 for anyone doing async :) (or in generally really)

In short: v3 was not very `async` friendly, breaks or behaves oddly in a variety of ways around it (e.g. "what is the root timing?", and will not be getting any further updates. A lot of how it handled things necessitated a rewrite of the fundamentals to be async friendly, which happened in v4. If you're hitting this, please update!

**Comment by NickCraver** [comment]
I'm going to close this out since it's solved in v4, but if you're still hitting issues there please shout!
