### ISSUE TITLE
not showing results for Step()

### ISSUE THREAD

**Issue by yohsii** [MiniProfiler/dotnet#427]
hi Nick, i'm using miniprofiler in asp.net core 3.0 and i get profiling results for requests to various frontend assets but i never get the results of calls to `Step()` from my controller.

```
using (MiniProfiler.Current.Step("deserialize")){
//code omitted
}
```

my configure services is like this:
```
services.AddMiniProfiler(options =>{
                // (Optional) Control storage
                // (default is 30 minutes in MemoryCacheStorage)
                (options.Storage as MemoryCacheStorage).CacheDuration = TimeSpan.FromMinutes(60);

                // (Optional) Control which SQL formatter to use, InlineFormatter is the default
                options.SqlFormatter = new StackExchange.Profiling.SqlFormatters.InlineFormatter();

            });
```
and in configure i call `app.UseMiniProfiler();` early, before UseEndpoints

any idea why this might be happening?

thanks,
Simon

**Comment by NickCraver** [comment]
When you say "not showing" you mean MiniProfiler isn't appearing at all, or it's not showing _that step_ in the profile?

**Comment by yohsii** [comment]
miniprofiler is appearing and showing results for requests to various assets but it's **not** showing that particular step or any other steps from my controllers

thanks for the quick response.

**Comment by NickCraver** [comment]
@yohsii Sanity check: did you click "show trivial" at the bottom of the profiler? By default (but configurable), it hides steps under 0.2 ms in duration.

**Comment by yohsii** [comment]
hmm the steps are not in the trivial list either

**Comment by yohsii** [comment]
turns out miniprofiler doesn't play nicely with response caching middleware. fixed by disabling response caching in development environment

thanks

**Comment by NickCraver** [comment]
Thanks for the update @yohsii, that makes a lot of sense - hopefully this being here helps someone else in the future :)
