### ISSUE TITLE
我想把MiniProfiler中EF的分析存储到数据库中？

### ISSUE THREAD

**Issue by 1257960069** [MiniProfiler/dotnet#429]
![image](https://user-images.githubusercontent.com/31265244/65744011-8b63e800-e129-11e9-981a-35b9e59d5a2a.png)
![image](https://user-images.githubusercontent.com/31265244/65744038-ac2c3d80-e129-11e9-986b-acbc6257df3a.png)

**Comment by NickCraver** [comment]
How are you spinning up connections? I see you've configured the _storage_, but that's not _the profiling_, which is where you need to wrap connections to see. Here are [the docs on profiling SQL](https://miniprofiler.com/dotnet/HowTo/ProfileSql).

**Comment by 1257960069** [comment]
if i add "options.Storage = new StackExchange.Profiling.Storage.MySqlStorage(Configuration.GetConnectionString("MySqlConnection"));" to AddMiniProfiler.options,EntityFramework sql Analysis will disappear。just like that picture

**Comment by NickCraver** [comment]
I'm still trying to understand here - are you saying if you use the MySQL storage (instead of memory), the profiling for SQL queries isn't coming up? I can't repro that here - perhaps a schema issue on the MySQL side?
