### ISSUE TITLE
AspNetCore 3.0 Exception: "Cache entry must specify a value for Size when SizeLimit is set."

### ISSUE THREAD

**Issue by Cooksauce** [MiniProfiler/dotnet#433]
Is AspNetCore 3.0 supported? I'm getting this exception on page load. Is this a bug or config error? It worked previously.

### Packages:
MiniProfiler.AspNetCore.Mvc ------- 4.1.0
MiniProfiler.EntityFrameworkCore -- 4.1.0

### Services Call:
`services.AddMiniProfiler().AddEntityFramework();`

### Configure Call:
`app.UseMiniProfiler();`

### StackTrace:
System.InvalidOperationException: Cache entry must specify a value for Size when SizeLimit is set.
  Module "Microsoft.Extensions.Caching.Memory.MemoryCache", in SetEntry
  Module "Microsoft.Extensions.Caching.Memory.CacheEntry", in Dispose
  Module "Microsoft.Extensions.Caching.Memory.CacheExtensions", in Set
  File "C:\projects\dotnet\src\MiniProfiler.AspNetCore\Storage\MemoryCacheStorage.cs", line 160, col 13, in Save
  File "C:\projects\dotnet\src\MiniProfiler.AspNetCore\Storage\MemoryCacheStorage.cs", line 195, col 13, in SaveAsync
  File "C:\projects\dotnet\src\MiniProfiler.Shared\ProfileProviders\DefaultProfilerProvider.cs", line 112, col 13, in SaveAsync
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter", in GetResult
  File "C:\projects\dotnet\src\MiniProfiler.Shared\ProfileProviders\DefaultProfilerProvider.cs", line 78, col 13, in StoppedAsync
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter", in GetResult
  File "C:\projects\dotnet\src\MiniProfiler.Shared\MiniProfiler.cs", line 243, col 13, in StopAsync
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  File "C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs", line 112, col 17, in Invoke
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter", in GetResult

**Comment by NickCraver** [comment]
Yep! 3.0 should work just fine - can you show me your `Startup.cs` (or wherever your config is) for services and middleware? Seeing how you're adding the memory cache may help.

**Comment by Cooksauce** [comment]
@NickCraver The only cache we add is a distributed one
```
services.AddDistributedRedisCache(options =>
{
     options.InstanceName = "<string>";
     options.Configuration = Environment.GetEnvironmentVariable("<string>");
});
```

All we're doing for MiniProfiler is calling `services.AddMiniProfiler().AddEntityFramework();`
And then calling `app.UseMiniProfiler();`

**Comment by Cooksauce** [comment]
Similar issue: https://stackoverflow.com/questions/58406143/unexpected-cache-entry-must-specify-a-value-for-size-when-sizelimit-is-set-mes

**Comment by Cooksauce** [comment]
@NickCraver

Looks like EF Core is setting up the `SizeLimit` on line 258:
https://github.com/aspnet/EntityFrameworkCore/blob/release/3.0/src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs

`TryAdd<IMemoryCache>(p => new MemoryCache(new MemoryCacheOptions { SizeLimit = 10240 }));`



**Work-Around:**
I was able to get it working by setting up the `IMemoryCache` manually before the EF Core registration:

```
services.AddMemoryCache();

services
     .AddEntityFrameworkNpgsql()
     .AddDbContext<MyDbContext>(
          options => options
               .UseNpgsql(connectionString, o => o.SetPostgresVersion(9, 6))
               .UseLazyLoadingProxies(),
          ServiceLifetime.Transient,
          ServiceLifetime.Transient);

services.AddMiniProfiler().AddEntityFramework();
```

**Permanent Solution:**
Do you have any suggestions on getting MiniProfiler to play nice with a `MemoryCache` that has the `MemoryCache.SizeLimit` set?

**Comment by NickCraver** [comment]
Just getting back to things here - I don't have any specific suggestions past "yeah, set it up yourself". But I also don't think EF Core should be doing this either - I've [commented on the change that did this](https://github.com/aspnet/EntityFrameworkCore/issues/12905#issuecomment-557849055). I'm going to chase that down and look at registering the IMemoryCache when needed in MiniProfiler if possible as well.

**Comment by ajcvickers** [comment]
@NickCraver Why are you using AddEntityFramework here? That's certainly not recommended except in some special cases.

**Comment by ajcvickers** [comment]
Let me provide a few more details. EF creates an internal service provider which it uses...internally. This is different from any service provider that you may have set up. (Unless you explicitly tell EF to use a different internal service provider, but this is not recommended.) Calling `AddEntityFrameworkXxx` will add all the internal services that EF needs internally. Calling this to add services to your own service provider has no value. EF won't ever resolve the services from it, so it just registers a lot of services that don't ever get used.

**Comment by ajcvickers** [comment]
@Cooksauce Is the code you posted calling `AddEntityFrameworkNpgsql` your code? If so, then I guess my question should be addressed to you rather than @NickCraver. Why are you calling this?

**Comment by Cooksauce** [comment]
@ajcvickers That's correct. It appears this was due to a miss-understanding of what that method does. I will remove this and confirm it works.

The misunderstanding may have had something to do with the fact that the Npgsql documentation for this method is 2/5 on sentences completed.

And the 2 sentences that are complete are: "You use this method when using dependency injection in your application, such as with ASP.NET. For more information on setting up dependency injection, see http://go.microsoft.com/fwlink/?LinkId=526890."

[NpgsqlEntityFrameworkServicesBuilderExtensions](https://www.npgsql.org/efcore/api/Microsoft.Extensions.DependencyInjection.NpgsqlEntityFrameworkServicesBuilderExtensions.html)

**Comment by ajcvickers** [comment]
@roji Looks like Npgsql docs might need to be updated.

**Comment by roji** [comment]
@ajcvickers done, https://www.npgsql.org/efcore/api/Microsoft.Extensions.DependencyInjection.NpgsqlServiceCollectionExtensions.html.

**Comment by NickCraver** [comment]
I think we're good here with the follow-ups and doc tweaks - and I'm glad to have this issue if someone else hits it along the way. Thanks all!
