### ISSUE TITLE
When using AspNetCore 3.0.100 ,  services.AddMemoryCache() is must be added?

### ISSUE THREAD

**Issue by tanwenjie1118** [MiniProfiler/dotnet#437]
I am trying update aspnetcore 2.x to 3.x ,but I can't start my app when my config is same as samples.

the error is :
Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate...etc
Microsoft.Extensions.DependencyInjection.MiniProfiler Options Defaults' can be invoked....etc

So,I find this issue in stackoverflow which  has no relation with miniprofiler .[link](https://stackoverflow.com/questions/53624779/asp-net-core-2-1-error-implementing-memorycache)

But, It really works, if I add 
    ` services.AddMemoryCache();`
into function ConfigureServices , miniprofiler is working well.

I noticed IMemoryCache has been referenced in this statement  
`// Control storage - the default is 30 minutes
 (options.Storage as MemoryCacheStorage).CacheDuration = TimeSpan.FromMinutes(60);`

but I've commented out this line ,why it still need MemoryCache.
does it mean the samples is not updated to latest version?

**Comment by NickCraver** [comment]
If you aren't _already_ doing something that sets up an `IMemoryCache`, yep `services.AddMemoryCache();` is all you need. When back at a laptop, I'll add this to the AspNetCore3 sample as a comment (that sample has components doing it underneath, so it isn't required directly).

**Comment by tanwenjie1118** [comment]
> If you aren't _already_ doing something that sets up an `IMemoryCache`, yep `services.AddMemoryCache();` is all you need. When back at a laptop, I'll add this to the AspNetCore3 sample as a comment (that sample has components doing it underneath, so it isn't required directly).

hey man ,yep, I know what are you saying , but , I mean I created a new web app without any ref to IMemoryCache,  started failed due to lacking this MemoryCache, So .... is that mean we should not copy sample totally ,but understanding it and using it by ourselves.

**Comment by NickCraver** [comment]
I pushed some more docs to the examples to help out here in https://github.com/MiniProfiler/dotnet/commit/86a6e79a29caaf26ea550b5905be9abb8f853349 - thanks for the issue and feedback! Hopefully this helps out the next person to trip on it :)
