### ISSUE TITLE
Asp.net core 2.2 api not able to integrate miniprofiler, dapper and mySql to work

### ISSUE THREAD

**Issue by farhad-taran-cko** [MiniProfiler/dotnet#439]
I am trying to get miniprofiler and Dapper on MySql to work together to profile sql statements.

I have managed to get miniprofiler and swagger to work together but the sql generated and executed by dapper are not intercepted for some reason, I believe this is because Miniprofiler.Current always returns null for some reason.

I was wondering if anyone else can help.

sample project is attached.
run docker compose and run api manually.
![2](https://user-images.githubusercontent.com/50828745/69482142-8b255780-0e0f-11ea-9834-b08ef6664c8b.jpg)
![1](https://user-images.githubusercontent.com/50828745/69482148-8d87b180-0e0f-11ea-9d06-e6cc4515fd29.PNG)
[TestApi.zip](https://github.com/MiniProfiler/dotnet/files/3883700/TestApi.zip)

**Comment by NickCraver** [comment]
I see in your app you have:
```cs
            app.UseMvc();
            app.UseMiniProfiler();
```
This means MiniProfiler isn't starting to profile until after MVC has executed in the pipeline. It also means the fix is pretty easy, just reverse those lines :)

In short: `.UseMiniProfiler()` should come before the other things you want to profile since it "wraps" them the way middleware works.

**Comment by farhad-taran-cko** [comment]
> I see in your app you have:
> 
> ```cs
>             app.UseMvc();
>             app.UseMiniProfiler();
> ```
> 
> This means MiniProfiler isn't starting to profile until after MVC has executed in the pipeline. It also means the fix is pretty easy, just reverse those lines :)
> 
> In short: `.UseMiniProfiler()` should come before the other things you want to profile since it "wraps" them the way middleware works.

Hello,

I tried your suggestion, this does solve the issue of Miniprofiler.Current being null but it still does not show what sql statements have been executed.

**Comment by farhad-taran-cko** [comment]
@NickCraver 
managed to finally fix it.

1st issue was that `app.UseMiniprofiler()` needs to come before `app.UseMvc`

2nd issue was that the db connection factory must look like this:

     public IDbConnection Create()
            {
                return new StackExchange.Profiling.Data.ProfiledDbConnection(
                    new MySqlConnection(_storageSettings.ConnectionString),
                    MiniProfiler.Current
                );
            }
The packages that I use are as follows:

    <PackageReference Include="Dapper" Version="2.0.30" />
    <PackageReference Include="MySqlConnector" Version="0.61.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.1.0" />
