### ISSUE TITLE
How to use in the .net standard class library

### ISSUE THREAD

**Issue by tkggusraqk** [MiniProfiler/dotnet#446]
I just want to use it in the .net standard class library and I didn't find the appropriate way to use it

**Comment by NickCraver** [comment]
Do you have an example usage case with some more specifics? For example, you usually need to output profilers somewhere, so just having it in a library _by itself_ wouldn't usually make a lot of sense. If you could illustrate your use case a bit I can probably advise on options :)

**Comment by NickCraver** [comment]
Closing out to tidy - can't assist more without additional info here :)
