### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jjxtra** [MiniProfiler/dotnet#450]
I have ocular migraines and light sensitivity. Is there a simple way to change the css to use a dark mode? I have tried browser extensions but they run really slow on some of the result profiling pages.

**Comment by NickCraver** [comment]
This is interesting - no there's not a way to do this today, _but_ I've recently dropped IE 11 support in #442, which means CSS variables are on the table and a much easier way to theme. Let me play around with this and see what we can do :)

**Comment by jjxtra** [comment]
Thanks nick. I guess in middle age my brain and eyes are way more sensitive to light even with monitor brightness at 0. If you do end up doing this please don’t spend too much time on it. If you all have a tip jar of some kind I’m happy to donate.

**Comment by NickCraver** [comment]
I'm going to come back at this tomorrow, but seems very doable. I've got all the colors in variables and it just needs a lot of color love and rigging up (I'll see if I can get browser/OS preferences to work). PR in-progress at #451 :)

**Comment by jjxtra** [comment]
Thanks so much for taking the time. Will this be a new bool or enumerated config property?

**Comment by NickCraver** [comment]
Hey Jeff! I'm thinking a `.ColorScheme` on the options...playing with it now :) I'd like to offer Light and Dark, but also an "Auto" which uses the browser media selectors. This may take a bit of tweaking but it will be awesome, and in general: you can specify your own color schemes completely as a result anyway, think of the first few themes as just the built-in ones. CSS 3 variables are spectacular for theming.

**Comment by jjxtra** [comment]
Great! I have used .less in the past but knowing you can do vars in plain old .css is awesome! So if it is set to Auto (default?) will it pick up on the dark mode setting of the operating system?

**Comment by NickCraver** [comment]
`Light` will be the default (breaking change, and odd within a larger page that may not facilitate switching), but that's what `Auto` will do for all browsers that support it, yep!

**Comment by NickCraver** [comment]
Merged in with #451 - it'll be on MyGet shortly and in the next release soon :)

**Comment by jjxtra** [comment]
Amazing thanks so much!
