### ISSUE TITLE
Is there any built in way to not display parameter values (only names) in formatted sql timings?

### ISSUE THREAD

**Issue by stevebelskie** [MiniProfiler/dotnet#461]
It seems like most of the options center around if/where to show the parameter names, but it seems like for security/privacy reasons there should be an option to get the query text as written WITHOUT having the declare statements at the top. 
 Instead of 
```sql
DECLARE @userId int = 1;

select * from Users where UserId = @userId;
```
is there no built in way to get the following?
```sql
select * from Users where UserId = @userId;
```

Am I missing something? If not, it seems like avoiding unnecessarily logging personally identifiable information in places where it may not be needed should be an option.

**Comment by NickCraver** [comment]
Which formatter are you using? The formatter itself is pluggable (see `ISqlFormatter`), and set via `MiniProfilerOptions.SqlFormatter`, for example:
```cs
options.SqlFormatter = new StackExchange.Profiling.SqlFormatters.SqlServerFormatter();
```

Note that `SqlServerFormatter` has its primary members `virtual` as well, so you could for example extend it to exclude params like this:
```cs
public class SqlServerNoParamsFormatter : SqlServerFormatter
{
    private static readonly List<SqlTimingParameter> _nilParams = new List<SqlTimingParameter>();
    public override string FormatSql(string commandText, List<SqlTimingParameter> parameters) 
        =>  base.FormatSql(commandText, _nilParams);
    public override string FormatSql(string commandText, List<SqlTimingParameter> parameters, IDbCommand command) 
        => base.FormatSql(commandText, _nilParams, command);
}
```

**Comment by stevebelskie** [comment]
Thanks! I missed the virtual members, but otherwise came up with essentially the same solution just to get something working. 
```cs
        public class CustomSqlFormatter : ISqlFormatter
        {
            private ISqlFormatter _sqlFormatter = new SqlServerFormatter();

            public string FormatSql(string commandText, List<SqlTimingParameter> parameters)
            {
                return _sqlFormatter.FormatSql(commandText, new List<SqlTimingParameter>());
            }
        }
```
It just took a little time to realize that an empty parameter list would in face get me what I wanted. Still seems this would ideally be an configurable option, but since other "options" are implemented as different classes, I'm guessing that's easier said than done.

**Comment by NickCraver** [comment]
@stevebelskie Could you please take a look at #463? I added a `IncludeParameterValues` boolean to `SqlServerFormatter`. Usage would look like this:
```cs
options.SqlFormatter = new SqlServerFormatter() { IncludeParameterValues = false };
```
It'll still print parameters up top, but without values. Some tests are included in that PR to illustrate what it'd render.
