### ISSUE TITLE
Client Timings

### ISSUE THREAD

**Issue by stefannikolei** [MiniProfiler/dotnet#466]
Is there a way to add the start time of the request from the client?

While using an SPA (angular) it would be neat to have a way to set the request start time. Perhaps ther is already a header for this?

**Comment by NickCraver** [comment]
Apologies here - I'm not sure I follow the request, the start time for _what_, and what would it mean?

**Comment by reaction1989** [comment]
Ok i should have written that in a different way :) I saw that you show client timings in Miniprofil while using MVC or Razor Pages.

Do you see an way to add something that correlates to client timings in an SPA environment?

**Comment by NickCraver** [comment]
Gotcha - so you're looking to profile the AJAX requests basically?

**Comment by reaction1989** [comment]
Sean That Would be Really nice.
