### ISSUE TITLE
UI have some problem with js.

### ISSUE THREAD

**Issue by hemiaoio** [MiniProfiler/dotnet#468]
Version: 4.2.0-preview.3
Framework: Asp.Net Core 3.1

The ts code:
https://github.com/MiniProfiler/dotnet/blob/b5313cc965e151a4ec04486c19f38a06c63a9703/src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts#L1178-L1205

``` javascript
this.initControls = function(t) {
                    var i, r;
                    n.options.showControls ? (t.insertAdjacentHTML("beforeend", '<div class="mp-controls"><span class="mp-min-max">m<\/span><span class="mp-clear">c<\/span><\/div>'),
                    n.controls = t.querySelector("mp-controls"),
                    i = t.querySelector(".mp-controls .mp-min-max")[0],
                    i.addEventListener("click", function() {
                        t.classList.toggle("mp-min")
                    }),
                    t.addEventListener("mouseover", function() {
                        this.classList.contains("mp-min") && (i.style.display = "block")
                    }),
                    t.addEventListener("mouseout", function() {
                        this.classList.contains("mp-min") && (i.style.display = "none")
                    }),
                    r = t.querySelector(".mp-result")[0],
                    r.addEventListener("click", function() {
                        r.parentNode.removeChild(r)
                    })) : t.classList.add("mp-no-controls")
                }
                ;
```
```js
i = t.querySelector(".mp-controls .mp-min-max")[0],
                    i.addEventListener("click", function() {
                        t.classList.toggle("mp-min")
                    }), 
```
has exception:
```
TypeError: Cannot read property 'addEventListener' of undefined
```

**Comment by NickCraver** [comment]
Curious - which browser are you seeing this in?

**Comment by hemiaoio** [comment]
<img width="231" alt="微信截图_20200416214909" src="https://user-images.githubusercontent.com/5441896/79464044-2b348500-802c-11ea-8ca3-be6597239e0f.png">
I debug it ,the querySelector function return result is an element object ,not an array.

**Comment by NickCraver** [comment]
In your network panel, is it fetching a profiler and getting a 404 or something? I'm trying to understand why it'd be empty :)

**Comment by hemiaoio** [comment]
No, I didn't receive a 404 error because I used the Vue component to use the miniprofiler panel, 
[https://github.com/andresrsanchez/vue-miniprofiler/blob/master/vue-miniprofiler/src/components/MiniProfiler.vue](url)
When I debug to ```i = t.querySelector(".mp-controls .mp-min-max")[0],```  the variable ```i``` is undefined, then t.querySelector(".mp-controls .mp-min-max") is an span element object.
<img width="1136" alt="微信截图_20200416224722" src="https://user-images.githubusercontent.com/5441896/79471033-ab5ee880-8034-11ea-841f-cc1bdb3d3b48.png">

**Comment by NickCraver** [comment]
@hemiaoio Ah I see, so the issue is in that module breaking a lot of assumptions - I could fix this one...but there'll probably be another issue following it immediately, so we may be chasing this a bit and I'm not sure what the goal is when we're trying to hook up all the bits to a thing that doesn't exist, ya know?

**Comment by hemiaoio** [comment]
Yes, as you said, I try to override the function use the element object directly instead of getting the array. I still can't find the `.mp-result` component in element `t`. So it can't attach events on that. Maybe I override it no effect after get the miniprofiler data result ?

**Comment by NickCraver** [comment]
Got some time to look at this, I'm really not sure why there was an array accessor on that - it'd make sense for a `.querySelectorAll()` call, but not `.querySelector()`. I'm...not sure why it works sometimes at all really.

Any chance you can give the `4.2.0-preview.7` package up on MyGet a try? Packages linked off the README: https://github.com/MiniProfiler/dotnet/blob/master/Readme.md

I hope that fixes your issue :)

**Comment by hemiaoio** [comment]
https://github.com/MiniProfiler/dotnet/blob/016d2fbca62d3706ab0da529c2c7f98013bf92f6/src/MiniProfiler.Shared/ui/lib/MiniProfiler.ts#L1198  same too.

**Comment by NickCraver** [comment]
Okay...that's a fail. I did a full pass now, see how `4.2.0-preview.9` treats you?
