### ISSUE TITLE
How to Stop MiniProfiler on App stop

### ISSUE THREAD

**Issue by weedkiller** [MiniProfiler/dotnet#478]
Hello how to `Stop `the MiniProfiler in ASP MVC, after my update to latest nuget its broken, and I dont see a replacedment method for stop    

_Error: Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0120	An object reference is required for the non-static field, method, or property 'MiniProfiler.Stop(bool)'	TestProj	C:\Web\Global.asax.cs_	

```
 protected void Application_EndRequest(object sender, EventArgs e)
        {
            //bool tempStop = false;
            MiniProfiler.Stop();
        }
```

**Comment by NickCraver** [comment]
I'm a little puzzled here, are you profiling _everything in the application_? I'd like to understand more there, but in any case you are looking for `MiniProfiler.Current?.Stop();` there. I'll add this to the upgrade notes at: https://miniprofiler.com/dotnet/HowTo/UpgradeFromV3

**Comment by weedkiller** [comment]
Maybe you're right an I am not using it correctly. Where should it go.

well the problem is that MVC apps targeting 4.8 which ship with the default compiler in VS 2019 dont accept this syntax its only after C# 7, i got around it by breaking the code down in 4 steps

**Comment by NickCraver** [comment]
@weedkiller gotcha - glad it works! I've added this note to the upgrade docs and just noting that there are sample apps which may be of help in seeing usage patterns over in: https://github.com/MiniProfiler/dotnet/tree/master/samples
