### ISSUE TITLE
Using our own CDN for the miniprofiler assets

### ISSUE THREAD

**Issue by ganchito55** [MiniProfiler/dotnet#479]
Hi, first of all thanks for that amazing library, I've been using it in local for two months, however I have a problem using it in our production environment.

Our production environment needs that all assets have to been served by our own CDN, due to we have a proxy that redirects all request to static files to that CDN. Therefore, I need to get both includes.min.css and includes.js from that CDN.

I have been thinking about how to do it and I think that I can create both files using webpack and upload them to our CDN manually. However, I think that I can't change the url of the request of both files because it's relative to my website.

To do this change, I propose to change [this line](https://github.com/MiniProfiler/dotnet/blob/79e9120ac8d778df33f363539874023221f1f7fd/src/MiniProfiler/MiniProfilerWebExtensions.cs#L39) and the ``RouteBasePath`` option allowing absolute paths

I hope you can help me,

P.S: I can also do a PR with this change.

Related to #32

**Comment by NickCraver** [comment]
We'd need to make changes to both ASP.NET and ASP.NET Core providers here, but my main concern is one level up: how do you handle versioning from that CDN? The contents of those files changes between releases and all of that is handled today in the library. For a CDN deploy, you'd need to put a new version of each and change settings to point at that version every time you updated. In short, there's a lot to go wrong here - what would be the plan for handling it?

**Comment by ganchito55** [comment]
In our case, we have an integration and deployment pipeline that:

1. Compile the code
2. Generate all assets via webpack
3. Deploy assets to private CDN (Amazon CloudFront)
4. Deploy code

We also have a proxy (that we cannot change) that redirects all request to static files to the CDN and the others to our Windows Servers.

My first approach is opening a bit the ``RouteBasePath`` option, to allow custom settings. However each dev should be responsible of manage how to put the statics in the place that he wants.

In our case, we have to add the JS and CSS files from this repo to our static repo and create a webpack bundle for our pipeline. Yes, it isn't the best approach because we have to do this work manually and update the library isn't automatically. In this case, we don't need versioning because we have only a single release in production with the same statics.

Other approach could be using a public CDN, like [CDNjs](https://github.com/cdnjs/cdnjs/commits/master) and getting both assets from that place. I think this approach is better, however it increases the work that the mainteners have to do. But we have versioning.

Anyway I prefer not forcing to use a CDN or local delivery and "open" the ``RouteBasePath`` option to both approach allowing relative by default and absolute (if it's needed) paths.

Thanks for your time.

**Comment by NickCraver** [comment]
Given that the setting we're talking about here is shared for both the assets _and_ all other dynamic routes, to support this would add a split and complication to all users (and the JavaScript/client bits). I think I understand the use case, but can't reasonably add the complication to support it. I'd advise revisiting your security team's stance here - having every component change their delivery model for assets just isn't a reasonable approach in the overall ecosystem.

I'm sorry you're in this position, but for the sake over the big picture - I don't see adding this case to MiniProfiler itself.

**Comment by ganchito55** [comment]
Thanks for your time NickCraver, I hope we can change our policy to allow using miniprofiler in production environment. Otherwise we keep using it for local debugging
