### ISSUE TITLE
MiniProfiler.Current.Ignore does not work

### ISSUE THREAD

**Issue by kinhoon** [MiniProfiler/dotnet#480]
I am using dotnet core 2.2.
I have a controller method that I want to exclude from profiling. According to docs, wrapping the code with `using (MiniProfiler.Current.Ignore()) {}` should exclude it, but it is not the case with me.

```
[HttpGet("Jobs/List")]
public JsonResult GetBackendJobs()
{
	using (MiniProfiler.Current.Ignore()) {
		List<RecurringJobDto> jobs = Hangfire.JobStorage.Current.GetConnection().GetRecurringJobs();
		if (null != jobs && jobs.Any()) {
			var data = jobs.ToList();
			var summary = new {
				NextExecution = data.Min(x => x.NextExecution),
				LastExecution = data.Max(x => x.LastExecution)
			};
			return Json(new {
				success = true,
				data = data,
				summary = summary
			});
		}
	}
	return Json(new {
		success = false
	});
}
```

I call this method from JavaScript as follow:
```
$.get('/api/common/jobs/list', function (ret) {
	// process return here
});
```

I expect it won't show in profile list, but it still. Where goes wrong in my code?
![image](https://user-images.githubusercontent.com/46112444/81087751-ab178600-8f2c-11ea-9d81-27d6f462dbdc.png)

Thanks.

**Comment by NickCraver** [comment]
I see your confusion here, the `.Ignore()` API is for suppressing _the code inside it_, not the overall. If you want to stop and throw away the profiler, your options are:
```cs
MiniProfiler.Current.Stop(discardResults: true);
```
(right where you are - top of the method)

Or you can use the `MiniProfilerOptions` to exclude that path (by URL) instead. For example [the sample app excludes `/lib*` requests here](https://github.com/MiniProfiler/dotnet/blob/ce69a34380d7426d6b271d78de6d0bb85f38111a/samples/Samples.AspNetCore3/Startup.cs#L86). You'd do something like this:
```cs
            services.AddMiniProfiler(options =>
            {
                // other config...
                options.IgnoredPaths.Add("/api/common/jobs/list");
            });
```
Note: that's a start-with path, so you could do something like `options.IgnoredPaths.Add("/api/common");` to ignore everything in the area, etc.

**Comment by kinhoon** [comment]
Thank you very much!!!
