### ISSUE TITLE
Couldn't install v4.1 onto .net 462 project

### ISSUE THREAD

**Issue by juanonsoftware** [MiniProfiler/dotnet#484]
Hello,

I couldn't install this package on .net 462, so it only support .netstandard 2 now, right?

Install-Package : Could not install package 'Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thank you,

**Comment by NickCraver** [comment]
This should work, MiniProfiler supports `net461`  at this point in time. Which version of NuGet/Visual Studio are you using? Some of the older versions don't get the `netstandard` mappings quite right and an update will likely fix you up.

**Comment by NickCraver** [comment]
Without more info - I can't help here. It's very likely you would be all set with a newer NuGet client based on the info thus far though!
