### ISSUE TITLE
Problems opening code in Visual Studio

### ISSUE THREAD

**Issue by chris10801080** [MiniProfiler/dotnet#489]
I don't know what's going on. I just downloaded and opened the code in Visual Studio, and I'm getting all kinds of like dependency missing exclamation points, & projects that just are not loading. This is Visual Studio 2017 15.9.19. And I do have .NET Core 2.1 installed.

But all I really want to do is run the MVC5 example web app.

![image](https://user-images.githubusercontent.com/17071679/83197973-41396900-a0f3-11ea-827d-95fbb7b1cb17.png)

**Comment by chris10801080** [comment]
FYI, when I try to reload the MVC5 project, I get:
"Project file is incomplete. Expected imports are missing."

**Comment by NickCraver** [comment]
I'm not sure if VS 2017 is supported at this point (I'm on 2019 and have been for some time), but it's possible you're just missing some ASP.NET Workloads in your install. We cold fix that with a `.vsconfig` in the root telling it what's needed...just hasn't come up before! See if you have APS.NET MVC bits installed for your VS?

**Comment by chris10801080** [comment]
Okay. Yeah, it works with VS 2019.

**Comment by NickCraver** [comment]
Closing this out since we specify VS 2019 16.3+ in the README already.
