### ISSUE TITLE
asp.net core 3 sample link is broken

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [MiniProfiler/dotnet#492]
The sample link for asp.net core 404's right now

**Comment by NickCraver** [comment]
Which link, from where?

**Comment by WhatFreshHellIsThis** [comment]
https://github.com/MiniProfiler/dotnet  -> "handy links" -> "Samples" -> "ASP.NET Core Sample App" -> 404

**Comment by NickCraver** [comment]
Fixed! Thank you for the report and additional info :)
