### ISSUE TITLE
MiniProfiler 4.2.1 does not support Internet Explorer 11

### ISSUE THREAD

**Issue by StuffOfInterest** [MiniProfiler/dotnet#500]
I just tried to update an ASP.NET Core 3.1 application from MiniProfiler version 4.1.0 to version 4.2.1.  When I start the application on Internet Explorer 11 I get the following JavaScript error:

```
Unhandled exception at line 3, column 22053 in http://localhost:10555/mini-profiler-resources/includes.min.js?v=4.2.1+b27bea37e9
0x800a138f - JavaScript runtime error: Unable to set property 'highlight' of undefined or null reference occurred
```

No errors happen when I use the latest version of Chrome.

Unfortunately, I'm working with a customer who is still using Internet Explorer on a closed network and isn't able to change yet, although they will have too before too much longer.  Not sure if support for older browsers can be maintained in MiniProfiler or if it is worth doing so but thought I'd bring it up here.

**Comment by NickCraver** [comment]
What you are seeing is expected, MiniProfiler 4.2.x indeed drops support for IE 11 (and is much, much smaller as a result). The release notes are here: https://miniprofiler.com/dotnet/Releases

If you require IE 11 support for a specific all, then it will require using an older version of MiniProfiler going forward.
