### ISSUE TITLE
MiniProfiler silently fails when MemoryCache is used with a SizeLimit

### ISSUE THREAD

**Issue by amoerie** [MiniProfiler/dotnet#501]
In a new .NET Core 3.1 web project, I had the following code in my dependency injection setup:

```csharp
services.AddMemoryCache(options => {
  options.SizeLimit = 1024;
});

services.AddMiniProfiler(options =>
{
    // Path to use for profiler URLs, default is /mini-profiler-resources
    options.RouteBasePath = "/mini-profiler";
});
```

The rest of the setup was as described in the documentation.

This causes all calls to miniprofiler to fail:

![image](https://user-images.githubusercontent.com/2063584/86245040-2e5dfc80-bba9-11ea-9b3a-aeca5a4ebfd7.png)

I traced the issue back to MemoryCacheStorage#158, which always fails to store the current MiniProfiler instance. Any subsequent calls that need to fetch it from the storage fail.

![image](https://user-images.githubusercontent.com/2063584/86245300-901e6680-bba9-11ea-8752-03a285df16ab.png)

Unfortunately the exception was swallowed somewhere and I couldn't see the exception details, but I can make an educated guess: cache entries must have sizes set when memory cache is configured with a size limit. 

Removing the SizeLimit option on my MemoryCache resolved the problem. I have not found a workaround yet that let me keep the SizeLimit. 

Most likely, this issue is very much related: #433 

Is this a known limitation, or am I doing something wrong? For now, I'll disable the size limit.

Thanks!

**Comment by NickCraver** [comment]
The swallowing is intentional (as to not cause inadvertent problems simply due to profiling), but you can see these exceptions!

If you're on 4.2.x, there's a new options property: `OnInternalError`, for example:
```cs
services.AddMiniProfiler(options =>
{
    // Other config....
    options.OnInternalError = e => MyExceptionLogger(e);
});
```

For example, if you wanted the operation to actually eat it, you could do:
```cs
options.OnInternalError = e => throw e;
```

Hope this helps :)

**Comment by amoerie** [comment]
Ah that helps indeed! Now I can verify that the exception originates from the setting of MiniProfiler in the MemoryCache:

```
2020-07-02 14:50:06.294 [EROR]  #007 (CONN:0HM0UGPG15RSM+REQ:00000003) An unhandled exception was thrown by the application.
System.InvalidOperationException: Cache entry must specify a value for Size when SizeLimit is set.
   at SampleProgram.Program.<>c.<Configure>b__0_6(Exception e) in C:\git\SampleProgram\Program.cs:line 114
   at StackExchange.Profiling.MiniProfiler.StopAsync(Boolean discardResults) in C:\projects\dotnet\src\MiniProfiler.Shared\MiniProfiler.cs:line 257
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 110
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by NickCraver** [comment]
@amoerie Nice! All good to close this out? :)

**Comment by amoerie** [comment]
Well, if not being able to set a size limit on memory cache is a known limitation of Mini profiler, then this issue can be closed indeed. 😉

**Comment by NickCraver** [comment]
It's really _any_ consumer of `MemoryCache`, so I'm not sure what we _could_ do here. Ultimately, I don't really agree with how `MemoryCache` exposed this..it should be a `LimitedMemoryCache` or something. The way it's done, an object must specify a size, in an overall attempt to limit memory. But in an OO language you don't know how big your size it.

We could loop through and make a "best guess" I guess (eating some CPU to do that), basically taking the size of a timing, custom timing, commands, all strings, etc. down the ref chain. And we'd have to maintain that. While .NET has the ability to do this by crawling the pointer tree (see ClrMd as an example), it's not done _because it's expensive_.

The memory size limit on `MemoryCache` is fundamentally flawed in that it's a cap based on a size given by the inserter, but that's a) whatever they say it is, and b) not guaranteed to change. For example I can add an object, null out it's ref tree, and the cache remains "full" because of a number we gave it. It's a good thought, but the practical reality of the limit I've never seen in use past a fairly simple application (without many pieces using it).

**Comment by NickCraver** [comment]
The good news is I forgot to document the error handler, this reminded me to do it in a721d43fd00daa299a5dac2f63478a435b0171f7 :) Closing out to cleanup, but if this come up again, let's revisit.

**Comment by amoerie** [comment]
@NickCraver 

> It's really any consumer of MemoryCache, so I'm not sure what we could do here

Hey, I'm not blaming you. This is a nasty error. I guess a best effort could include catching the specific exception MemoryCache throws when a sizelimit is set, and rethrowing that as an UnsupportedOperationException saying "MiniProfiler does not work when you use SizeLimit on MemoryCache!". But that would require people to enable the internal logging to see it. 

Alternatively, you could mention somewhere in the docs that MiniProfiler breaks if you set a SizeLimit on MemoryCache, although people can also easily find this Github issue too if they googled it. 

> We could loop through and make a "best guess" I guess (eating some CPU to do that), basically taking the size of a timing, custom timing, commands, all strings, etc. down the ref chain. And we'd have to maintain that. While .NET has the ability to do this by crawling the pointer tree (see ClrMd as an example), it's not done because it's expensive.
> 
> The memory size limit on MemoryCache is fundamentally flawed in that it's a cap based on a size given by the inserter, but that's a) whatever they say it is, and b) not guaranteed to change. For example I can add an object, null out it's ref tree, and the cache remains "full" because of a number we gave it. It's a good thought, but the practical reality of the limit I've never seen in use past a fairly simple application (without many pieces using it).

I agree with everything you said, and we're switching off the SizeLimit. The only reason we even started doing so is because it is somewhat recommend by the official Microsoft docs [here](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1#cache-guidelines)

Perhaps it's time to call that into question?

**Comment by NickCraver** [comment]
No blame assumed at all, just always thinking out loud in case it spurs more ideas! I agree at least mentioning this in the docs is a good idea 9512d29588ebc7f1c6a61c38540ddeff452f23ad adds a note and a link to this issue in the config section (best place I can think of), but if you've got other ideas for improvements there I'm all ears!

**Comment by amoerie** [comment]
That's already more than can be reasonably expected of a library that shares none of the blame for this problem, adding it in the config docs is absolutely perfect and I don't have any better ideas. 👍 

Thanks for making miniprofiler!
