### ISSUE TITLE
js error - Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by zhengfan0829** [MiniProfiler/dotnet#511]
my English is not good
Env: 
aspnetcore3.1 
miniprofiler 4.2.1
windows 10
chrome83 & Edge85

Create default aspnetcore3.1 webApp
install nuget packages
Swashbuckle.AspNetCore 5.5.1
MiniProfiler.AspNetCore 4.2.1
MiniProfiler.EntityFrameworkCore 4.2.1

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddSwaggerGen(opt=> {
                opt.SwaggerDoc("v1", new OpenApiInfo { Title = $" API", Version = "v1" });
                opt.DocInclusionPredicate((docName, description) => true);
                opt.AddSecurityRequirement(new OpenApiSecurityRequirement() {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
                        },
                        new[] { "readAccess", "writeAccess" }
                    }
                });
            });
            services.AddMiniProfiler(opt=> {
                opt.RouteBasePath = "/profiler";
            });
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseMiniProfiler();
            app.UseSwagger();
            app.UseSwaggerUI(opt=> {
                var endPoint = $"/swagger/v1/swagger.json";
                opt.SwaggerEndpoint(endPoint, $" API V1");
                opt.IndexStream = () => Assembly.GetExecutingAssembly().GetManifestResourceStream("WebApplication3.index.html");
            });

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }

in Swagger.index.html 
    <script async="async" id="mini-profiler" src="/profiler/includes.min.js?v=4.0.138+gcc91adf599"
            data-version="4.0.138+gcc91adf599" data-path="/profiler/"
            data-current-id="4ec7c742-49d4-4eaf-8281-3c1e0efa748a" data-ids="" data-position="Left"
            data-authorized="true" data-max-traces="15" data-toggle-shortcut="Alt+P"
            data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync">
    </script>
![1](https://user-images.githubusercontent.com/29992178/88145958-cf325b80-cc2d-11ea-8c1d-c7fff92ec614.png)
![2](https://user-images.githubusercontent.com/29992178/88145977-d5283c80-cc2d-11ea-97f0-7644151333fc.png)

colorScheme is undefined
search manymany documents..so found the property data-scheme
it works until I add property data-scheme="Auto" in script

![image](https://user-images.githubusercontent.com/29992178/88146470-7e6f3280-cc2e-11ea-8ba9-5e61b2bf11e4.png)

**Comment by NickCraver** [comment]
The problem I see here is you're using MiniProfiler 4.2.1 JS, which expect 4.2.x markup...but your script tag has `4.0.138`, which doesn't have all the properties. Do you have a custom script tag or something? MiniProfiler generating it should be on the same version in both cases.

**Comment by zhengfan0829** [comment]
Thank you for your reply！
Oh,I see!
How can I use correct script version in swagger static file without worrying about MiniProfiler version upgrade?

**Comment by zhengfan0829** [comment]
> The problem I see here is you're using MiniProfiler 4.2.1 JS, which expect 4.2.x markup...but your script tag has `4.0.138`, which doesn't have all the properties. Do you have a custom script tag or something? MiniProfiler generating it should be on the same version in both cases.

Thank you for your reply！
Oh,I see!
How can I use correct script version in swagger static file without worrying about MiniProfiler version upgrade?

**Comment by NickCraver** [comment]
@zhengfan0829 There's the assumption that they match (otherwise we'd have to have infinite version compatibility). How is it getting into your Swagger files?

**Comment by zhengfan0829** [comment]
@NickCraver Thank you for your reply.
I use hard code int swagger.index.html file. It's like this.

<script async="async" id="mini-profiler" src="/profiler/includes.min.js?v=4.0.138+gcc91adf599" data-version="4.0.138+gcc91adf599" data-path="/profiler/" data-current-id="4ec7c742-49d4-4eaf-8281-3c1e0efa748a" data-ids="" data-position="Left" data-authorized="true" data-max-traces="15" data-toggle-shortcut="Alt+P" data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync">

By the way.Is this better to do like this ?
Request -> /profiler/includes.min.js
ReadProductVersion => Redirect => /profiler/includes.min.js?v={version}

**Comment by yamac-kurtulus** [comment]
You can have razor generate the tag as instructed [in the tag helpers section on this page](https://miniprofiler.com/dotnet/AspDotNetCore). For 4.2.1, it gave me the following tag which I copied and pasted into Swagger Json:

`<script async="" id="mini-profiler" src="/profiler/includes.min.js?v=4.2.1+b27bea37e9" data-version="4.2.1+b27bea37e9" data-path="/profiler/" data-current-id="d91c292a-0c26-479e-b9fd-1f32af7a96fc" data-ids="d91c292a-0c26-479e-b9fd-1f32af7a96fc" data-position="Left" "="" data-scheme="Light" data-authorized="true" data-max-traces="15" data-toggle-shortcut="Alt+P" data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync"></script>`

I am curious though. What are the relevant fields for which markup to use? are the following properties  enough: `src="/profiler/includes.min.js?v=4.2.1+b27bea37e9" data-version="4.2.1+b27bea37e9" ` 

Or do we also need these: 
`data-current-id="d91c292a-0c26-479e-b9fd-1f32af7a96fc" data-ids="d91c292a-0c26-479e-b9fd-1f32af7a96fc" `

The former can be generated (assuming `b27bea37e9` is the commit id) but the latter is probably arbitrary.

In any case, best would be to be able to generate that thing in the recommended way. Is there a way to generate the Tag without helpers or razor?

**Comment by NickCraver** [comment]
The fields needed may change each version, they're not meant to be independent here. I honestly don't have a good solution here.

What kind of render _would_ be pluggable into the doc generator, so that when the library is updated the docs are as well?

**Comment by ranouf** [comment]
Hi,

I have the same error, colorscheme is undefined.

I use:
		<PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.1.0" />
		<PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.2.22" />
	
I added this to my swagger.html	
<script async="async" id="mini-profiler" src="/profiler/includes.min.js?v=4.2.22"
		data-version="4.2.22" data-path="/profiler/"
		data-current-id="4ec7c742-49d4-4eaf-8281-3c1e0efa748a" data-ids="" data-position="Left"
		data-authorized="true" data-max-traces="15" data-toggle-shortcut="Alt+P"
		data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync">
</script>

I'm not sure to understand this part:

> You can have razor generate the tag as instructed in the tag helpers section on this page. For 4.2.1, it gave me the following tag which I copied and pasted into my custom swagger index:

I went to the github page (https://miniprofiler.com/dotnet/AspDotNetCore), but I didnt find the online generator. 

How did you do to be able to see the mini profiler in swagger?

**Comment by NickCraver** [comment]
Without more info, unable to help here...but also I'm not sure we can reasonably support this in any case (taking a snapshot of code and hoping it works). If a build code gen or something would be of use...maybe? Would need contributor help there. For now, closing this out to tidy up since it hasn't come up in a long time.
