### ISSUE TITLE
Ormlite Async methods throw Unable to cast object of type 'StackExchange.Profiling.Data.ProfiledDbCommand' to type 'System.Data.SqlClient.SqlCommand" with Miniprofiler 4.2.1

### ISSUE THREAD

**Issue by hoppities** [MiniProfiler/dotnet#519]
Hello,

When using async ormlite methods (like below), Ormlite throws the following error.
`Unable to cast object of type 'StackExchange.Profiling.Data.ProfiledDbCommand' to type 'System.Data.SqlClient.SqlCommand"`

```
            using (IDbConnection db = await this.Conn.OpenAsync())
            {
                return await db.SelectAsync(where);
            }
```

This error only happens if we register ormlite with miniprofiler.

```
            container.Register<IDbConnectionFactory>(() =>
                new OrmLiteConnectionFactory(CONNECTION_STRING_GOES_HERE, DIALECT_PROVIDER_HERE)
                {
                    ConnectionFilter = f => new ProfiledDbConnection((DbConnection)f, MiniProfiler.Current)
                },
                ScopedLifestyle.Scoped
            );
```

**Comment by NickCraver** [comment]
Indeed that would fail - it looks like they're making assumptions that the `DbCommand` is in fact a `SqlDbCommand` (or any other type) - that's simply not a safe assumption in all of ADO.NET. It's an interface that could be any type.

I recommend filing an issue on their side as to why they're making this invalid assumption and what it's trying to do with that command (likely attempting to do something SQL Server specific).

**Comment by NickCraver** [comment]
Closing this out to cleanup, please see above advice!
