### ISSUE TITLE
Disabling MiniProfiler header for specific endpoints

### ISSUE THREAD

**Issue by Turnerj** [MiniProfiler/dotnet#520]
This might be a weird scenario - I use MiniProfiler in my application for the user part and a separate API part. I'm completely happy with how the user portion is working however the API portion, while I am tracking the profiling information I want on the server, it is sending through the headers for client side performance tracking.

Is there a way to disable the `X-MiniProfiler-Ids` header for a specific path?

I tried `options.IgnoredPaths.Add("/api/");` however that disabled profiling entirely. I know there is the `MaxUnviewedProfiles` setting and I _could_ tweak that lower to avoid as many headers being sent though that seems more like a last-ditch effort rather than a solution.

If this doesn't sound too weird and the functionality doesn't exist, I'm happy to propose a PR adding something like this - probably similar to how the `ShouldProfile` option works by passing a `Func<HttpRequest, bool>`.

**Comment by NickCraver** [comment]
I'm not totally sure I'm understanding the ask here. On these routes: do you want to profile _and just not see it_? Or not profile at all? You could deny authorization for the former via `ResultsAuthorize` - if a user is not authorized, we won't print out the `<script>` tag in RenderIncludes. Does that fit your case?

**Comment by Turnerj** [comment]
So on my site, I have MiniProfiler where I use it normally for the most part. I also have a HTTP API for that isn't for browsers. I use MiniProfiler in the back part of the API but as browsers don't consume it, the client side profiling is irrelevant so as far as I know, the headers are irrelevant.

The thing is, the API and the main site are the same app so I can't run a config to entirely remove client side profiling so I'd like a switch to disable the MiniProfiler headers for a particular path.

Does that help explain the issue?

**Comment by Turnerj** [comment]
I did realise one interesting thing I could do is have my `HttpClient` in my API client library return profiling information to the server as if it was a browser. That said it is somewhat out-of-scope from my own project. It isn't like the `X-MiniProfiler-Ids` headers are a huge problem, I'm just thinking they aren't needed to be sent on my `/api/` routes as there is no browser on the other side.

If it helps, here is what my MiniProfiler configuration looks like:

```csharp
services.AddMiniProfiler(options =>
{
	options.RouteBasePath = "/profiler";
	options.ResultsAuthorize = request =>
	{
		if (Environment.IsDevelopment())
		{
			return true;
		}

		if (request.HttpContext.User.IsInRole(ApplicationRole.Developer))
		{
			return true;
		}

		return false;
	};
	options.UserIdProvider = request =>
	{
		return request.HttpContext.User.Identity.Name;
	};
});
```

**Comment by NickCraver** [comment]
@Turnerj I'm confused by this request still, is your config _not_ working as intended and not rendering the headers? (even in non-dev? given that's always true). Anything not authorized should not render the headers: https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs#L191

**Comment by Turnerj** [comment]
Ohhhhh I get the issue now, it makes sense now! I was in "Development" mode for the site I was testing on when I wrote this issue. My MiniProfiler configuration had the `ResultsAuthorize` handler like so:

```csharp
if (Environment.IsDevelopment())
{
	return true;
}
```

Forcing it to return `false` instead matches what you described and linked to. Totally didn't click to me that I was directly causing the issue I didn't want. 🤦‍♂️

Sorry for wasting your time mate!

**Comment by NickCraver** [comment]
No worries at all just thought I was crazy :) Glad you got it sorted! If that doesn't do what you need in the end, please shout.
