### ISSUE TITLE
How to profile EF6 when using AspNetRequestProvider and HttpContext.Current is null?

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#529]
From what I understand, EF6 queries will be profiled using the profiler that was passed into the `ProfiledDbConnection` that the DB context uses.

However, when profiling EF6, there doesn't actually seem to be a way to pass a `ProfiledDbConnection` myself. Instead, `EFProfiledDbConnectionFactory` creates the `ProfiledDbConnection` using `MiniProfiler.Current` (See [line 33 of `EFProfiledDbConnectionFactory`](https://github.com/MiniProfiler/dotnet/blob/276252f68d2b94b05a41e22b13ffeeeef6efa180/src/MiniProfiler.EF6/EFProfiledDbConnectionFactory.cs#L33)).

In turn, `MiniProfiler.Current` uses `MiniProfiler.DefaultOptions.ProfilerProvider`, which in my case is the `AspNetRequestProvider`. This provider returns a `null` profiler when `HttpContext.Current` is null.

I'm running background jobs in my ASP.NET application. There is no `HttpContext.Current` in these background jobs, which makes it seemingly impossible to profile EF6 queries inside background jobs.

Is there a way to use a different profiler provider inside specific parts of my application? I tried changing the profiler provider inside my background jobs, but that just leads to issues because my application stops using `AspNetRequestProvider` altogether.

If there is not a way to use a different profiler provider inside background jobs, is there a different solution? Is there another way to pass a profiler or connection to my DB context instead?

**Comment by RudeySH** [comment]
I ended up explicitly passing a ProfiledDbConnection into the DbContext constructor. This way, I can specify my own profiler in background jobs.

```C#
public MyDbContext(MiniProfiler profiler) : base(new ProfiledDbConnection(
    new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString),
    profiler
), true) { }
```

Alternatively, it's probably also possible to implement my own RequestProvider that checks if the current thread is associated with a background job, and if not, falls back to `AspNetRequestProvider`.

**Comment by NickCraver** [comment]
This is a good way to do it, or using the default provider you can just start and stop a profiler per-job. IMO, best to be explicit about the unit you want to track through...so I'd be passing it in as you've done :)

**Comment by NickCraver** [comment]
Closing out to cleanup!
