### ISSUE TITLE
Spaces inserted after commas in command text

### ISSUE THREAD

**Issue by mcNux** [MiniProfiler/dotnet#539]
Found that (even without a SqlFormatter configured) the SQL as it appears in MiniProfiler differs from the original command text; extra spaces are found after commas. The spaces are inserted [here](https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.Shared/Internal/IDbCommandExtensions.cs#L41).

This is a problem for our team as we use MiniProfiler's output to diagnose poorly performing queries, and need to ensure same query plan is used (and thus exact same SQL) when we execute in SSMS.

As a workaround we're running the same regex on the SQL before it is executed.

**Comment by Turnerj** [comment]
While I do see that code that adds the comma, just curious, do you set any SQL formatter yourself on the options or just use the default (which seems to be the [`InlineFormatter`](https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.Shared/SqlFormatters/InlineFormatter.cs))?

Digging through how the code works and what it calls, it looks like it _should_ allow overriding of that via setting your own SQL formatter however that code, [as seen here](https://github.com/MiniProfiler/dotnet/blob/726f534ab597227f780c14744b7189fce2e61dea/src/MiniProfiler.Shared/SqlFormatters/SqlFormatterExtensions.cs#L36), also calls `GetReadableCommand` creating those spaces again.

What I'm thinking is removing the call to `GetReadableCommand` for the SQL formatters and make it an option in their constructors instead. That way you can control whether you want that additional spacing or not.

**Comment by mcNux** [comment]
Yes, we do use own SQL formatter.

I think it would be ideal if no extra formatting (I'm considering adding spaces as formatting) occurred if custom formatter is applied but yeah making it configurable sounds good.

I shouldn't concern yourself too much though; probably not a problem for anyone else :).

**Comment by Turnerj** [comment]
Nah, I get what you mean - having the exact same query would be ideal even if the differences are only spaces. There is actually another issue just recently which has a problem with `null` values in queries appearing as empty strings instead - while still a valid query, it isn't the same query.
