### ISSUE TITLE
MiniProfiler in ASP.NET Web Forms

### ISSUE THREAD

**Issue by mokarchi** [MiniProfiler/dotnet#553]
my project is legacy and use web form technology.There is no way for use MiniProfiler in ASP.NET Web Forms?

**Comment by Turnerj** [comment]
You could probably hack something together using [the information described in the docs for MVC](https://miniprofiler.com/dotnet/AspDotNet) which involves a change in your `Global.asax` file. Getting the client side script into the page though is likely to be harder, needing to involve some version of calling `MiniProfiler.Current.RenderIncludes()` (like [seen here](https://github.com/MiniProfiler/dotnet/blob/f4c0dc11e23c4811de2abc470dd613b99a38c4c5/samples/Samples.Mvc5/Views/Shared/_Layout.cshtml#L63) for the MVC sample project) in your master page.

I imagine though the quality of life working with MiniProfiler in this manner won't be great and there will likely be a bunch of other issues along the way. Unless someone has already worked out the specifics for how to get it working, I don't think there is much more help that anyone can provide.

**Comment by mokarchi** [comment]
Thanks for sharing your opinion @Turnerj , and I’m glad you were so forthright about it!

**Comment by NickCraver** [comment]
Which version of .NET are you on? If you're using WebForms, it's likely you want to be aiming for MiniProfiler v3. Just for this set of cases, I have tags for (but do no maintenance on, being up front) the previous version that should work just fine.

Here's the v3.2.0 tag and you can browse around (or pull and run) the webforms sample: https://github.com/MiniProfiler/dotnet/tree/v3.2.0/Sample.WebForms

**Comment by mokarchi** [comment]
@NickCraver Thanks for your solution! That's a really nice option
