### ISSUE TITLE
'nonce' attribute of <mini-profiler /> taghelper does not work for stylesheet include

### ISSUE THREAD

**Issue by d-gibbs** [MiniProfiler/dotnet#560]
I'm using MiniProfiler.AspNetCore.Mvc v4.2.1 and attempting to set a nonce on the tag helper like so:

`<mini-profiler nonce="@Html.CspScriptNonce()" />`

I'm finding that the nonce is correctly being set on the `<script />` includes file (trimmed):

`<script async id="mini-profiler" src="/mini-profiler-resources/includes.min.js?v=4.2.1+b27bea37e9" data-version="4.2.1+b27bea37e9" data-path="/mini-profiler-resources/" data-authorized="true" nonce="YkvcvTp1dLG5AR1UaZvrOO0c"></script>`

But not for the stylesheet:

`<link rel="stylesheet" type="text/css" href="/mini-profiler-resources/includes.min.css?v=4.2.1+b27bea37e9">`

Which then results in a bunch of CSP violations:

![image](https://user-images.githubusercontent.com/59481722/118624542-2909a080-b7c1-11eb-82a5-f2605f3aeae7.png)

![image](https://user-images.githubusercontent.com/59481722/118625522-00ce7180-b7c2-11eb-91f1-dad519072007.png)

Is there a way that we can ensure the nonce gets applied to the MiniProfiler stylesheet include?  At the moment it seems like the only option is to enable unsafe-inline for style-src which is not desireable.

**Comment by NickCraver** [comment]
Just pushed a fix for this - it'll be on the CI feed in a few minutes (see README), and likely on NuGet next week :)

**Comment by PhenX** [comment]
Any plan to release a new nuget package ? This is still not released apparently https://miniprofiler.com/dotnet/Releases
