### ISSUE TITLE
Problems when targeting .net standard 2.0

### ISSUE THREAD

**Issue by santo998** [MiniProfiler/dotnet#562]
When i reference the MiniProfiler nuget package from my library (targeting .net standard 2.0) i receive the following warning:

Warning NU1701 Package 'MiniProfiler 4.2.22' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

That warning doesnt allow me to even compile my library due unknown types.

**Comment by stevebelskie** [comment]
@santo998 According to the [docs ](https://miniprofiler.com/dotnet/NuGet) describing the Nuget packages, the MiniProfiler nuget package is the core functionality for full framework applications. For .NET Standard 2.0+ [MiniProfiler.AspNetCore](https://www.nuget.org/packages/MiniProfiler.AspNetCore/) serves that purpose. Both reference the shared core functionality provided by [MiniProfiler.Shared](https://www.nuget.org/packages/MiniProfiler.Shared/).

**Comment by NickCraver** [comment]
Steve's right - please use the `MiniProfiler.AspNetCore` package here for .NET Core applications :)
