### ISSUE TITLE
/mini-profiler-resources/results-index page gives error in other environment but works in local environment

### ISSUE THREAD

**Issue by Deepa-Puranik** [MiniProfiler/dotnet#563]
We are planning to have miniprofiler running on production environment with restriction set to only developers and admins can have access to it.

But /mini-profiler-resources/results-index page gives "The page cannot be displayed because an internal server error has occurred." error in other environment and works in local environment. It just says MiniProfilerHandler/ProcessRequest is failed but no more details on that.

Are there any specific configuration we need to set for page to work in other environments?
Please help.

**Comment by NickCraver** [comment]
I'd look into the error logs here - do you have error logging for the application, or barring that, the Windows event logs? Need some hint as to what's happening here - turning on errors would be another way to go about it.

**Comment by NickCraver** [comment]
Happy to help if there's more info here, closing out to tidy up until then :)
