### ISSUE TITLE
can't find：includes.min.js

### ISSUE THREAD

**Issue by MyTkme** [MiniProfiler/dotnet#564]
Include.min.js source code, where can I get the uncompressed include.js
![image](https://user-images.githubusercontent.com/33886182/123903717-cef42180-d9a1-11eb-8db3-5b721d1fdc1a.png)

**Comment by NickCraver** [comment]
This is a generated file - you'll need to build to see it, e.g. `dotnet build Build.csproj` in the repo root directory :)
