### ISSUE TITLE
Miniprofiler manager

### ISSUE THREAD

**Issue by grounzero** [MiniProfiler/dotnet#566]
I am new to miniprofiler, just got it running this week and have added it to several dotnet services.

Is there such a thing as a manager ui?  Like an index page for different /results-index endpoints?

**Comment by NickCraver** [comment]
Missed this originally - nope this isn't a feature of MiniProfiler itself, and not a game I'd like to get in to with the core library but anyone could build this on top of this library using a common storage for example or...whatever pattern they wanted. If someone dives into this, please link it here for others to find!
