### ISSUE TITLE
MiniProfiler, .NET 5, & ProfilingViewComponentInvokerFactory

### ISSUE THREAD

**Issue by nickalbrecht** [MiniProfiler/dotnet#571]
I'm not sure if I'm crazy, or what the deal is here. Does MiniProfiler support AspNetCore on `NET5`? I don't see a pre-release version and I'm getting some weird behaviors where it doesn't seem like it's loading the correct dll.

I was curious to lookup profiling for ViewComponents in MiniProfiler and stumbled across #286. Which seems to be exactly what I was looking for, but it doesn't seem to be working. I tried to wire it up myself via a call to 
```
services.AddSingleton<Microsoft.AspNetCore.Mvc.ViewComponents.IViewComponentInvokerFactory, 
StackExchange.Profiling.Internal.ProfilingViewComponentInvokerFactory>();
```
But I get an error on being unable to resolve `ProfilingViewComponentInvokerFactory`.
I tried navigating to the source of `AddMiniProfiler` and got redirected to the decompiled source for `\.nuget\packages\miniprofiler.aspnetcore.mvc\4.2.22\lib\netcoreapp3.0\MiniProfiler.AspNetCore.Mvc.dll`. Which seemed odd, cause I'm not on `netcoreapp3.0`, I'm on `net5`, but so be it. I checked the source in github [`MiniProfiler.AspNetCore.Mvc/MvcExtensions.cs`](https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.AspNetCore.Mvc/MvcExtensions.cs), and even that matches what my decompiled source gives, if `NETCOREAPP3_0` resolved to `true`. However if I actually use `#if NETCOREAPP3_0` in my own code, it's greyed out and doesn't run.

Is there a compatibility issue with the MiniProfiler Nuget package, and NET5? And if not, how do you get support for ViewComponent profiling (and out of curiosity, shouldn't `ProfilingViewComponentInvokerFactory` be registered as a singleton like [`DefaultViewComponentInvokerFactory` is by default](https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Mvc/Mvc.ViewFeatures/src/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs#L221)?)

**Comment by nickalbrecht** [comment]
This is going to be a bit of an investigative dump of information.

I went digging into the code for MiniProfiler (and the code for aspnetcore) trying to understand this further, andsee if I could make the changes to get this to work with .Net5, or netcoreapp3.x.  it looks like in `aspnetcore2.x` was the last version where `DefaultViewComponentInvokerFactory` and `DefaultViewComponentInvoker` were pubternal (used public keyword, but only intended to be used internally). Once aspnetcore3.1 hit, they made it ACTUALLY internal, which explains why the source for MiniProfiler has statements to only include certain code when it's not NETCOREAPP3_0 (implying 2.x only), the classes used aren't available on 3.x and up.

The actual implementation of the underlying interfaces are pretty straight forward (the files aren't large), but there are implementation differences between the various version of AspNetCore (and some more in 6.0). But, they are still internal, so the only way I can think of to use the same Default implementations they use for view components, is to copy the needed files from their source in `/src/Mvc/Mvc.ViewFeatures/src/ViewComponents/*` and make the necessary changes to inject the few lines needed to wire up the profiling, as well as the appropriate preprocessor directive(s).
The problem is, this snowballs fast to other dependencies that are also internal. First to `ViewComponentInvokerCache`, then things like `ObjectMethodExecutor`, which is in `Microsoft.Extensions.Internal`, and it just builds rapidly from there.
I'm sad that they internalized this as much as they did, yeah the underlying interfaces are public, and I could dig through the source to find all this out, but the implementations are non-trivial to pickup and run with.

**Comment by NickCraver** [comment]
Sorry I'm so behind here - new job and other things. Your info helps! Indeed these things all moved but the way we observe this is different now. It's all via Diagnostic listener bits. An example of where [it's kicked off is here](https://github.com/dotnet/aspnetcore/blob/a5a1e9a9d8631caf39366c11511c0cd126a02b34/src/Mvc/Mvc.ViewFeatures/src/ViewComponents/DefaultViewComponentInvoker.cs#L116), and then we listen for that event/data and do something with it. I upgraded the .NET samples to include a .NET 5 version to demo this but didn't get to the view components. Indeed today we are not listening for that event - [here's all the stuff we're listening for today](https://github.com/MiniProfiler/dotnet/blob/b38f3ab35f6772e55814162f279396e7d55bd432/src/MiniProfiler.AspNetCore.Mvc/MvcDiagnosticListener.cs#L143).

Overall: we need to add a view component to the samples to have something to play with, and add listening for it in the handler, then it'll be good to go.

**Comment by NickCraver** [comment]
@nickalbrecht thanks for the dig here - getting this remedied in #583 and will have a build up on MyGet shortly. These were already in the samples project, so you can see it working in the "Massive View Nesting" example there:

![image](https://user-images.githubusercontent.com/454813/140649253-8bc271f4-8998-4c9c-b13d-5d206dc468bf.png)
(ignore all the timings being ~15ms, that's just the minimum sleep delay on a typical Windows system under normal circumstances)

**Comment by nickalbrecht** [comment]
Awesome! Glad to see that this is something that can be tracked. I remember coming across the calls to `BeforeViewComponent` in the component invoker, but didn't have experience/understanding with diagnostic listeners to understand how they were used, or that MiniProfiler used them underneath. Super slick, I'll have to read up on how they work.
Excited to see this added to MiniProfiler. Always appreciate your time on this stuff!

No worries, and congrats on the job! I'm not at all surprised to see Microsoft eventually snag you up with your skills and talents. Looking forward to seeing what sort of stuff you end up working on, both with regards to Azure and other OSS contributions!

**Comment by nickalbrecht** [comment]
Just grabbed `4.2.49` off of MyGet to give it a shot, and it seems to work great for me. Components show in the list of events exactly where I'd expect. Any ideas as to when the next publish to Nuget is planned?
