### ISSUE TITLE
MiniProfiler to text file

### ISSUE THREAD

**Issue by BiswasParama** [MiniProfiler/dotnet#573]
I want to write all the Sql queries generated by dapper in a log file. I am using asp.net core and serilog and I have added MiniProfiler.AspNetCore.Mvc and also added  services.AddMiniProfiler(); and app.UseMiniProfiler(); then what should I do? Please help. Its urgent.

**Comment by NickCraver** [comment]
Hey there - this isn't a built-in thing (it'd be pretty messy format-wise), but you can loop over a profile and export as needed. Check out #343 for examples :)

**Comment by BiswasParama** [comment]
Thanks for your reply I understood that I need to loop through profile but I want all the sql queries from the whole application so where should I add this loop and all the examples you mentioned is about timming not sql queries how to get that. I am using Miniprofiler for the first time so I am confused how to it. Please help.

**Comment by BiswasParama** [comment]
It can be done with dapper.logging so my problem is solved. Thanks.
