### ISSUE TITLE
Object reference not set to an instance of an object at `StackExchange.Profiling.Data.ProfiledDbConnection.get_ConnectionString()`

### ISSUE THREAD

**Issue by dehghani-mehdi** [MiniProfiler/dotnet#591]
- DotNet Version: `6.0`
- MiniProfiler Version: `4.2.22`

Code:
```cs
public static void AddDbConnection(this IServiceCollection services, string connectionString, bool isDevelopment)
{
    var dbConnection = new SqlConnection(connectionString);

    if (isDevelopment)
    {
        var profiledDbConn = new ProfiledDbConnection(dbConnection, MiniProfiler.Current);

        services.TryAddTransient<IDbConnection>(_ => profiledDbConn);
    }
    else
    {
        services.TryAddTransient<IDbConnection>(_ => dbConnection);
    }
}
```

Error:
> Object reference not set to an instance of an object.
at StackExchange.Profiling.Data.ProfiledDbConnection.get_ConnectionString() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbConnection.cs:line 52

**Comment by NickCraver** [comment]
The way this code is creating a connection it's creating _one_ connection when you're registering services, and that one is going to get disposed after the first use (e.g. request) by being transient. What you probably want is to spin up a connection _per use_ in the transient as a lambda in your DI, e.g. 
```cs
services.TryAddTransient<IDbConnection>(() => new ProfiledDbConnection(new SqlConnection(connectionString), MiniProfiler.Current));
```
