### ISSUE TITLE
Issues Running MiniProfiler with YARP reverse proxy

### ISSUE THREAD

**Issue by MartyBJones** [MiniProfiler/dotnet#595]
I have two applications, Application-A which is a .Net 6 web application and Application-B which is a .Net Framework web application.  Both of these applications are running MiniProfiler with a distributed storage provider.

The problem I am seeing happens when Application-A forwards a request to Application-B and Application-B invokes an Ajax request which is then forwarded from Application-A back to Application-B.   I see the following error in the web tools console:

`Uncaught SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 158 of the JSON data
`.
The error occurs within the miniprofiler js file "includes.min.js:1:27121".

What is the best way to capture the json to see what content is causing the  issue?  I don't see the requests within the browser tools console.

**Comment by MartyBJones** [comment]
Good news!  I was able to determine the endpoint by moving the call "app.UseMiniProfiler();" to after the call to  "app.UseRouting();".  Once I did this then I can see the "Endpoint" being used for the request and return false if the endpoint is the YARP endpoint.

Is there any downside to having the "app.UseMiniProfiler();" call after "app.UseRouting();"?

**Comment by NickCraver** [comment]
@MartyBJones the downside would be: you're not profiling _that_ part of the pipeline. If you're cool with that: no problems, you're just profiling the bits that come _after_ where we wrap it in profiling.

**Comment by NickCraver** [comment]
Closing this out to tidy up :)
