### ISSUE TITLE
Why does ProfiledDbCommand have InternalCommand and not WrappedCommand?

### ISSUE THREAD

**Issue by kendallb** [MiniProfiler/dotnet#599]
We are working with a third party PHP compiler for .NET (PeachPie) which is how we build and maintain some of our legacy PHP code as we port it all to C#. Anyway, long story short they use MySqlConnector directly and it all fails when we wrap the SQL connection stuff with MiniProfiler. I am working to fix this by unwrapping it using reflection at runtime as needed when it needs MySQL specific stuff for the MySQL implementation. So far it's pretty easy was everything is using WrappedBlah, but I noticed ProfiledDbCommand uses InternalCommand rather than WrappedCommand.

I am going to write code to handle that, but I was wondering if there is a reason it cannot be changed to use the same naming? The primary reason is that I am writing this code in the hope that other libraries that might want to wrap connections etc would also use a similar naming connection and would just work. I doubt anyone would choose InternalCommand?

Of course in case someone is using it (it's public after all), it might need to have both, but I would prefer WrappedCommand for the future.

**Comment by kendallb** [comment]
For reference:

https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.Shared/Data/ProfiledDbCommand.cs#L430

**Comment by NickCraver** [comment]
@kendallb Indeed we could add a prop and deprecate the other pointing to a standard Wrapped - no issues there to lien it up having 2 until the next major release.

What I wonder though is the reflection at runtime - that's generally a poor performing result, so I'm curious what you're doing - do you have a set of example code? I wonder if we could provide a generic extension for example or a few of them to save a lot of boilerplate for anyone in the same situation.

**Comment by kendallb** [comment]
Yes reflection sucks but we cache the function once we have found if so we don’t need to keep looking it up. And we early out if it’s not wrapped.

I have been meaning to check but we also use DataDog for production APM monitoring and it captures SQL statements and profiles them also. But they must do it in a way that somehow does not wrap the MySQL connection but not sure how it works. It’s open source also so I need to run it in the debugger to see if I can figure out how it does it. 

~~~C#
        /// <summary>
        /// Gets the underlying MySql connection from the connection. We specifically support the case where
        /// the connection is a wrapped connection such as we get from MiniProfiler, and we look for WrappedConnection to
        /// find the native MySqlConnection when we need it.
        /// </summary>
        internal MySqlConnection MySqlConnection
        {
            get
            {
                if (_mySqlConnection != null) return _mySqlConnection;
                _mySqlConnection = _connection as MySqlConnection;
                if (_mySqlConnection != null) return _mySqlConnection;
                if (_innerConnectionMethod == null)
                    _innerConnectionMethod = _connection.GetType().GetMethod("get_WrappedConnection", BindingFlags.Instance | BindingFlags.Public);
                _mySqlConnection = _innerConnectionMethod?.Invoke(_connection, null) as MySqlConnection;
                if (_mySqlConnection == null) throw new NullReferenceException("Could not get MySqlConnection for wrapped connection!");
                return _mySqlConnection;
            }
        }
        private MySqlConnection _mySqlConnection;
        private static MethodInfo _innerConnectionMethod;
~~~

**Comment by kendallb** [comment]
Here is one of the file for reference.

https://github.com/kendallb/peachpie/blob/f10613755d95759bc3e50d4f8251f2279b92b8c7/src/Peachpie.Library.MySql/MySqlConnectionResource.cs#L86

**Comment by NickCraver** [comment]
This will be in the next release :) https://github.com/MiniProfiler/dotnet/commit/2c7b0a2cbb9e5e3595e2d4fd4c6240e51c3c8828
