### ISSUE TITLE
https://miniprofiler.com/dotnet/Releases does not track the latest released 4.2.22 and this release is not tagged in the repo either

### ISSUE THREAD

**Issue by IanKemp** [MiniProfiler/dotnet#604]
This makes it impossible for someone trying to investigate an issue in this version to get the correct source code.

**Comment by NickCraver** [comment]
4.2.22 was a fix to the versioning only - nothing noteworthy included. For what it's worth, every assembly produced is stamped with an exact git hash so you can always get the exact code! Tag and release note calling out the build fixes are pushed up though, so closing this out :)
