### ISSUE TITLE
Storage providers should support (but not require) a record auto-expiration mechanism

### ISSUE THREAD

**Issue by IanKemp** [MiniProfiler/dotnet#608]
For example, `MiniProfiler.Providers.MongoDB` could use Mongo's innate [TTL](https://www.mongodb.com/docs/manual/tutorial/expire-data/) feature to automatically delete records older than N minutes or M days.

**Comment by IanKemp** [comment]
Implemented in #613 for MongoDB.

**Comment by IanKemp** [comment]
@NickCraver I appreciate this project isn't really your priority any more, but please could you take a look at this? Thanks!

**Comment by NickCraver** [comment]
Forgot to close this out with #613, thanks for the changes!
