### ISSUE TITLE
What is the "gap" meaning?

### ISSUE THREAD

**Issue by ztzsws1** [MiniProfiler/dotnet#625]
Hello,

I have a question about miniprofiler, when I use miniprofiler to find the performance root cause, I find an action used lots of times, but I don't the reason.
<img width="477" alt="miniprofiler gap" src="https://user-images.githubusercontent.com/5999059/196386805-70c3c732-88d2-400a-967f-1b6f3e5f9ccf.png">
There will be a SQL and SQL cost time normally, but there is no detail in the action. So I guess the action is waiting for CPU?

**Comment by NickCraver** [comment]
In that view, gap means a gap between 2 queries: so yeah your app is doing something in there. I'd suggest adding more timings between to see in the main view what's going on. Also expanding the columns on the main popup to see start times can help navigate you here.

**Comment by NickCraver** [comment]
Closing out to tidy up!
