### ISSUE TITLE
Serialize MiniProfiler\Timing class with System.Text.Json

### ISSUE THREAD

**Issue by KLuuKer** [MiniProfiler/dotnet#630]
I currently json serialize the MiniProfiler instance with Newtonsoft Json.
So i can transport the profiling data to some other service layer (yes bad design i need shared storage i know).

But i would like to completely switch to System.Text.Json instead,
and also use it's source generator to remove reflection where possible
[https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/]()

but it doesn't support data contract attributes....
could you add attributes that are supported by system.text.json?
[https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/ignore-properties]()

**Comment by NickCraver** [comment]
To do that, we'd have to take a dependency on System.Text.Json for everyone, which is not something I want to do (referencing 2 serializers). The way to do this currently is by implementing a resolver as I understand it - examples here: https://github.com/dotnet/runtime/issues/63686. I'm not an expert on the state though, the decision to leave this out-of-box is something I disagree with as do many in the community - IMO, this should be far easier.

**Comment by KLuuKer** [comment]
maybe it could be "solved" by resolving a `IMiniProfilerSerializer` with 2 implementations in different packages
would have some configuration issues, and most likely be a breaking change

or maybe a IFDEF version with a MiniProfiler.Shared-TextJson package.....
but that would most likely end up needing more `-TextJson` suffix version for a bunch of other packages

**Comment by NickCraver** [comment]
@KLuuKer I think the only path here I can imagine (for compatibility) is to see if we can make System.Text.Json compatible 1:1 with the Newtonsoft output (so that it could read existing stored profiles). _If_ we can do that, potentially a net6.0+ build wouldn't have any dependencies on Newtonsoft.

**Comment by NickCraver** [comment]
A `net6.0` build without a `Newtonsoft.Json` dependency will be in the next version, via #641 :)

**Comment by Atulin** [comment]
Has this change been released on the MyGet feed at least? I'd very much like to switch to STJ myself wherever possible.

**Comment by NickCraver** [comment]
@Atulin Yep, on nuget.org now :)
