### ISSUE TITLE
Outdated documentation. MiniProfiler.current doesn't exist.

### ISSUE THREAD

**Issue by LeonardoDaLuz** [MiniProfiler/dotnet#647]
In this tutorial, the object MiniProfiler.Current doesnt exists.

https://miniprofiler.com/dotnet/HowTo/ProfileSql

![image](https://user-images.githubusercontent.com/80224694/228983370-ef2def75-7875-4a58-a637-70653c1cf1a6.png)

**Comment by NickCraver** [comment]
MiniProfiler isn't a namespace in the package, so my guess is you've either created or imported something with that namespace that's interfering. `MiniProfiler` is a _type_ in `StackExchange.Profiling` :)

**Comment by LeonardoDaLuz** [comment]
Yes... the lib MiniProfiler.Integrations was misleading me.
Ridiculous Lib, trap.
