### ISSUE TITLE
Timing.cs does not implement IDisposable by the pattern

### ISSUE THREAD

**Issue by AssassinLV** [MiniProfiler/dotnet#649]
By the pattern:
https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose
It is required to have two Dispose methods: Public and Private or Protected.
This is required because other projects might also use this class for IDisposable objects, but then there is compiler error CA2213. By making at least that single Dispose method (even if not yet abiding by the good practice pattern) would remove the need to suppress CA2213 which requires to call Dispose method for Timing object.

For example
``` cs
public class Potato : IDisposable
{
  // definition

  public void Dispose()
  {
    // Dispose of unmanaged resources.
    Dispose(true);
    // Suppress finalization.
    GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing)
  {
    if (_disposed)
    {
        return;
    }

    if (disposing)
    {
       _timer.Stop(); // This makes error CA2213, because Dispose() method is expected, but it can't be used because it's private
    }

    // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
    // TODO: set large fields to null.

    _disposed = true;
  }

// More code
}
```

**Comment by NickCraver** [comment]
This is intentionally omitted because that's another virtual method call (which has expense) and a principal goal of timers is to have as little overhead as possible.

Closing this out to tidy up - structure is by-design :)
