### ISSUE TITLE
google浏览器source不显示index-mini-profiler.html

### ISSUE THREAD

**Issue by xiaomazz** [MiniProfiler/dotnet#651]
servers.AddMiniProfiler(options =>
            {
                // Reduce non-Swagger page request monitoring problems
                options.ShouldProfile = (req) => req.Headers.ContainsKey("request-from");

                // Set the routing base address of the access analysis result URL
                options.RouteBasePath = "/index-mini-profiler";

                options.TrackConnectionOpenClose = true;
                options.ColorScheme = ColorScheme.Auto;
                options.PopupRenderPosition = RenderPosition.Left;
                options.PopupShowTimeWithChildren = true;
                options.PopupShowTrivial = true;
                options.SqlFormatter = new StackExchange.Profiling.SqlFormatters.InlineFormatter();
                options.EnableMvcFilterProfiling = true;
                options.EnableMvcViewProfiling = true;
                // options.IgnoredPaths.Add("/swagger/");
            })
                .AddRelationalDiagnosticListener()
                .AddEntityFramework(); //Display SQL statements and time-consuming (MiniProfiler.EntityFrameworkCore)
                
                
                
                app.UseMiniProfiler();
                
                
                
![f94e6ea9-d45e-46d1-ba07-3447650f9cf1](https://github.com/MiniProfiler/dotnet/assets/52307384/e6886193-997d-49ba-bfc8-cb865e275e93)

**Comment by NickCraver** [comment]
Consolidating into #326.
