### ISSUE TITLE
Profiling EF Core broken by ConfigureAwait(false)

### ISSUE THREAD

**Issue by RichardD2** [MiniProfiler/dotnet#654]
Same issue as #392, but this time for EF Core. _(v3.1.x in an MVC5 / .NET Framework 4.8 application)_

Any use of `.ConfigureAwait(false)` in the application causes subsequent queries to be missed by the EF Core profiler.

Looking at [the `RelationalDiagnosticListener` class](https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.EntityFrameworkCore/RelationalDiagnosticListener.cs), it makes extensive use of `MiniProfiler.Current`, which will be `null` after an `await`ed call continues without the captured context.

Is there any way to avoid this without dropping every use of `.ConfigureAwait(false)` from the codebase?

**Comment by NickCraver** [comment]
@RichardD2 you'll want to use v4+ which has solutions for many of these issues (using AsyncLocal<T> for storage in this case).

**Comment by RichardD2** [comment]
@NickCraver I'm using MiniProfiler v4.2.22. 

Unfortunately, since we rely on SSRS, we're stuck on .NET Framework, so we can't use any version of EF Core later than v3.1.32.

**Comment by RichardD2** [comment]
@NickCraver I see what you mean - the [DefaultProfileProvider](https://github.com/MiniProfiler/dotnet/blob/a009d55a19050c8b88a3ea0c357d54ad192763b5/src/MiniProfiler.Shared/ProfileProviders/DefaultProfilerProvider.cs) uses an `AsyncLocal`, so it should persist across `await` calls regardless of the `ConfigureAwait` status.

Perhaps I'm hitting a slightly different problem, but I'm definitely seeing queries missing from the MiniProfiler output when I use `ConfigureAwait(false)`, and included when I remove that.

Maybe it's related to #173?

> So far, some of my research as lead me to believe that setting something via `AsyncLocal` or logical `CallContext` is *not safe* from `Application_BeginRequest()` or any of the ASP.NET pipeline events because the `ExecutionContext` doesn't flow between the worker threads executing these events. Small/short requests may execute the handler from the same thread that executed `Application_BeginRequest()`, but larger/long requests may not.

**Comment by NickCraver** [comment]
@RichardD2 I can't speak to older EF Core issues there - the profiler handles it but EF Core context we have no control over :(
