### ISSUE TITLE
ClockOverride

### ISSUE THREAD

**Issue by anxinpid** [MiniProfiler/dotnet#657]
Please provide  support   “options.ClockOverride”

![image](https://github.com/MiniProfiler/dotnet/assets/27767289/8190fa5a-9110-4bb9-8119-4de3a76f117e)

**Comment by NickCraver** [comment]
What is the ask here? Please be specific.

The reason we render in Zulu time is that most server logs are in UTC and that's what people are comparing to. A specific timezone besides that doesn't make sense for an application going to more than 1 place, and the only alternative to that is rendering in the user's local timezone which can be confusing comparing to server time.

**Comment by NickCraver** [comment]
Closing this out to tidy up - happy to discuss with more info.
