### ISSUE TITLE
mongodb storage error

### ISSUE THREAD

**Issue by herme063** [MiniProfiler/dotnet#661]
I am getting a NotSupportedException thrown from MongoDbStorage on multiple functions. 

This occurs where the code compares Id with a guid; The exception message was like: `Expression not supported: (p.Id == <Guid>).`
This happens on all the code that use equality filter on the profiler Id property.

I am using c# driver 2.21.0.

**Comment by NickCraver** [comment]
Let's fold this into #673 - tl;dr: we need a MongoDB expert to come in and contribute here if we want to continue any enhancements or current support for it.
