### ISSUE TITLE
Null reference with parallel queries

### ISSUE THREAD

**Issue by sirphilliptubell** [MiniProfiler/dotnet#662]
We're using MiniProfiler.AspNetCore.Mvc 4.2.22 and occassionally we're getting this NullReferenceException:

I suspect this happens when we're running Dapper queries in parallel (separate connections, not MARS) but haven't been able to pinpoint any particular scenario.

```
Message: Object reference not set to an instance of an object.
StackTrace: 
StackExchange.Profiling.MiniProfiler.StackExchange.Profiling.Data.IDbProfiler.ExecuteFinish():77 
at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReaderAsync():271
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():0
at Dapper.SqlMapper+<QueryAsync>d__33`1.MoveNext():418
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():0
at ...
```

**Comment by sirphilliptubell** [comment]
Nevermind, I see this [was fixed](https://github.com/MiniProfiler/dotnet/blob/1d93eab15f8d7d7a0173bf501c8f0ad82173bab7/src/MiniProfiler.Shared/MiniProfiler.IDbProfiler.cs#L29C13-L29C13) in the latest release.

**Comment by NickCraver** [comment]
ACK - closing out to tidy up!
