### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [MiniProfiler/dotnet#664]
Maybe You will be interested in hosting API Explorer online:
https://www.robiniadocs.com/d/miniprofiler/api/StackExchange.Profiling.html

This is ready-to-go, so above link can be added to README.md for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Docs-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/miniprofiler/api/StackExchange.Profiling.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Docs-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/miniprofiler/api/StackExchange.Profiling.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Regards
NeuroXiq

**Comment by NickCraver** [comment]
It looks like the TLS cert for this site isn't valid, so assuming this isn't maintained - closing out to tidy up.
