### ISSUE TITLE
Planned release of nuget package with (#641), version 4.3.13?

### ISSUE THREAD

**Issue by cklutz** [MiniProfiler/dotnet#672]
Hi,

I'd like to check the status of possible new release of MiniProfiler (MiniProfiler.AspNetCore, to be specific) to nuget.org.

I've been reading issues here and saw that the dependency on Newtonsoft.Json (in favour of System.Text.Json)
has been removed with #641. This is exactly what I would need, as we are currently dropping all support of Newtonsoft.Json to streamline dependendencies in our core software.

AFAICT, until now, there is no release of this version (4.3.13?) on nuget.org (newest there is 4.3.8), but only on [myget](https://www.myget.org/feed/miniprofiler/package/nuget/MiniProfiler.AspNetCore/4.3.13).

Do you have any plans (and time ;-)) to push this to nuget.org or are there other open issues, that you know of, that prevent this?

I'd be also happy to use the myget-version for the time being, but first wanted to check, if a release to nuget.org is imminent anyway or if you know of any showstoppers in the myget/4.3.13 version.

Thanks for your great work!

Cheers,
Christian

**Comment by NickCraver** [comment]
This will be in a 4.5.x release shortly - taking the few days off here to catch up on a few projects that are loooong overdue.
