### ISSUE TITLE
 Fixing invalid X-MiniProfiler-Ids responses

### ISSUE THREAD

**Issue by jcoutch** [MiniProfiler/dotnet#74]
Moved bug from: https://github.com/MiniProfiler/ui/pull/5

Sometimes the X-MiniProfiler-Ids response contains a double-array instead of a single.
With this change, we take the first one and discard the rest.

A normal response looks like that:

```
["94A4A68F-C2C5-4A66-8369-CC5DAAEF3640"]
```

Sometimes I get this response:

```
["94A4A68F-C2C5-4A66-8369-CC5DAAEF3640"], ["94A4A68F-C2C5-4A66-8369-CC5DAAEF3640"]
```

I do not know why, but this is a fix/workaround for that.

Edit:
I forgot to mention that all the id-parsings now also bundled in one method.

---

Code examples are located at the link referenced above.  This is still an issue for us on our ASP.NET MVC 4 project.

**Comment by marcusgraham** [comment]
I was having similar problems with the array in array header. The problem appeared to be the script blocker (ScriptSafe) extension I had enabled in Chrome. Disabling this resolved the issue.

**Comment by NickCraver** [comment]
Closing this since it appears to not be a MiniProfiler issue, or something we can do much about.
