### ISSUE TITLE
ProfilingViewEngine cannot be added to ViewEngines.Engines with MVC 5.2

### ISSUE THREAD

**Issue by jpsullivan** [MiniProfiler/dotnet#78]
Very strange, but Visual Studio seems to complain about how the ProfilingViewEngine cannot be added to ViewEngines.Engines when using ASP.NET MVC 5.2, as seen below:

![VS Error](http://i.imgur.com/w8Tn2bQ.png)

However, this does not prevent from performing a successful build, which I found to be odd.

![MP Working?](http://i.imgur.com/KoymWH1.png)

FWIW, I restarted Visual Studio and that didn't seem to do the trick.  Cleaned the Solution and that didn't do a thing either.  I am running Resharper with Solution Analysis enabled, but disabling it didn't seem to help either.

I'm not sure if this is something to even be worried about, but I wanted to bring it up anyways in case you guys had any ideas.  I'm open to doing a pull request if we decide that this is an actual issue.

**Comment by NickCraver** [comment]
@jpsullivan I'm going to close this out because I don't think it's a current issue - likely a one off config problem. If you are still seeing this somewhere, let me know please?

**Comment by jpsullivan** [comment]
Sounds great, @NickCraver. Yeah the problem has since vanished and sadly I have no idea why. Sorry I didn't update this thread though. Totally slipped my mind.
