### ISSUE TITLE
Update Documentation and Nuget package to restrict access to ~/mini-profiler-resources/results

### ISSUE THREAD

**Issue by russcam** [MiniProfiler/dotnet#79]
The current documentation on http://miniprofiler.com/ for .NET is out of date and raises a potential security issue in that by default, it allows anonymous users to be able to access mini profiler results at `~/mini-profiler-resources/results`, showing the results of the last profiled request; these results may contain executed SQL, Mongo calls and other configured profile steps.

In addition, the current nuget package does not secure access to `~/mini-profiler-resources/results` by default.

I propose updating the documentation and nuget package to add templated code into global.asax when installing the package. The templated code should be similar to that on [Sam's blog post (see section "UI less profiling")](http://samsaffron.com/archive/2012/02/22/miniprofiler-2-0-almost-out-of-the-gate)

```
// Tell MiniProfiler if the current request can see the UI. 
void Application_Start(object sender, EventArgs e) 
{
   MiniProfiler.Settings.Results_Authorize = httpRequest => IsUserAllowedToSeeMiniProfilerUI(httpRequest);
}

private bool IsUserAllowedToSeeMiniProfilerUI(HttpRequest httpRequest)
{
    // TODO: Implement this to indicate who can access ~/mini-profiler-resources/results
 }
```

**Comment by NickCraver** [comment]
Fixed via https://github.com/MiniProfiler/miniprofiler.github.com/commit/4e6861a7dd3d5bfa74123aaef1fabe157e766f9f, closing this out to cleanup :)
