### ISSUE TITLE
Miniprofiler in OWIN CookieAuthentication's OnValidateIdentity task

### ISSUE THREAD

**Issue by AkosLukacs** [MiniProfiler/dotnet#86]
Hi!

Found a strange issue: Miniprofiler doesn't register steps when the step is executed in OWIN's CookieAuthentication's OnValidateIdentity Task.

Created an example, the actual StepStatic call is here: https://github.com/AkosLukacs/Autofac-OWIN-MVC/blob/master/AutofacOwinMvc/Startup.ConfigureAuth.cs#L28
Debug messages are written to Trace.

To see what's happening, run the project, just go to `/`, execution time should be 42+something milliseconds (`ExampleMiddleware` is waiting for 42ms).
Then go to `/home/signin`, that should 'sign you in', and redirect you to `/home/auth`. After that, you should see `@OnValidateIdentity` messages in Trace, and page execution time should be 42+42+something milliseconds. 42ms from the middleware, and 42ms from the `Task.Delay` in the OnValidateIdentity Task.

To 'log off', go to `/Home/SignOut`. 

The total execution time is indeed increased, but the 'Step' itself does not show up in Miniprofiler.

Any idea? Am I doing something wrong? Some strange behavior/bug because of async tasks, or owin?

Side note: Actually this started from not seeing SQL calls executed in the OnValidateIdentity task. 
My first guess was Autofac is somehow mis-configured. That was true, but Autofac's config is fixed now, but step (and sql calls) still doesn't show up in Miniprofiler results. You can mostly ignore `ExampleService` and `ExampleMiddleware`, left there for to see that it's working.

**Comment by NickCraver** [comment]
This is an async issue in general (aiming to fix these in v4), see #127 for tracking there. Merging this into #127, so we can track in one spot :)
