### ISSUE TITLE
EF6 :: MiniProfiler will no longer work with EF 6.1.2 - throws "Unable to cast object of type 'StackExchange.Profiling.Data.ProfiledDbCommand' to type 'System.Data.SqlClient.SqlCommand"

### ISSUE THREAD

**Issue by maumar** [MiniProfiler/dotnet#94]
EF6.1.2 introduced SqlProviderServices.CloneDbCommand method to fix one of the issues. Internally this method performs a cast to SqlCommand, and it fails with MiniProfiler (which uses StackExchange.Profiling.Data.ProfiledDbCommand). Method is virtual, and should be overriden by providers.

For more information see: https://entityframework.codeplex.com/workitem/2390

**Comment by NickCraver** [comment]
It looks like this was fixed in https://entityframework.codeplex.com/SourceControl/changeset/2c22b55d2081b55132e9ca98ed1d787f786687c5 can anyone provide more insight?
