### ISSUE TITLE
ProfiledMongoCollection.FindAndRemove() yields "need remove or update" error in MiniProfiler.MongoDb 3.0.11

### ISSUE THREAD

**Issue by robhruska** [MiniProfiler/dotnet#95]
_Understandable if this can't be fixed since MiniProfiler.MongoDb 3.0.11 is a bit older, though I thought I'd put it out there in case it can be (since 3.0.11 feels like a "supported version" for slightly older mongocsharpdriver versions, it being listed on the README and all). I'm mainly not sure what the version implications of a fix would be since 3.0.12 is already out. I also figured it'd be good to have this here for the Googles to pick up if anyone else runs into this and goes searching._

---

When using [`ProfiledMongoCollection.FindAndRemove()`](https://github.com/MiniProfiler/dotnet/blob/c46374dd069fbf4efb17f956ae29ddc6d3f530e7/StackExchange.Profiling.MongoDB/ProfiledMongoCollection.cs#L154) from MiniProfiler.MongoDb 3.0.11 along with mongocsharpdriver 1.8.3, mongo returns this error:

> Command 'findAndModify' failed: need remove or update (response: { "ok" : 0.0, "errmsg" : "need remove or update" })

`ProfiledMongoCollection.FindAndRemove()` calls a private `FindAndModifyImpl()`, and passes a `remove` flag, but it doesn't get used by the driver's `FindAndModify()` call that it makes.

``` csharp
        public override FindAndModifyResult FindAndRemove(IMongoQuery query, IMongoSortBy sortBy)
        {
            return FindAndModifyImpl(query, sortBy, true, null, false, null, false);
        }

        private FindAndModifyResult FindAndModifyImpl(IMongoQuery query, IMongoSortBy sortBy, bool remove, IMongoUpdate update, bool returnNew, IMongoFields fields, bool upsert)
        {
            var sw = new Stopwatch();

            sw.Start();
            var result = base.FindAndModify(query, sortBy, update, fields, returnNew, upsert);
            sw.Stop();
            ...
```

According to the mongocsharpdriver 1.8.3 docs, it doesn't even look like you can pass a `remove` flag to its `FindAndModify()`, so there's probably a slight incompatibility between 3.0.11 and the driver. The fix probably involves calling the driver's `FindAndDelete()` directly (like is [currently happening in master](https://github.com/MiniProfiler/dotnet/blob/master/StackExchange.Profiling.MongoDB/ProfiledMongoCollection.cs#L224)).

Again, not a huge deal, so if it can't be fixed, meh. We're probably going to update our driver sometime soon, anyway, at which point we can upgrade MiniProfiler to the latest and everything will be amazing and glorious. Just wanted this out there 'cause I didn't find it until it hit production for us, since we've only got a single, tucked away place in the code that calls `FindAndRemove()`, and it didn't get exercised by any of our tests.

**Comment by NickCraver** [comment]
I apologize this wasn't gotten to in forever, no one has given the MongoDB driver much love it seems. I'm working on that now with the vNext release for all libraries, including a MongoDB release supporting the 2.x version of the driver.

So this isn't a great response - but I think it's proper to close this out, and point people to that line of progress, in #125. Let me know if you see any reason to go back to the 1.x driver line and figure out support at all. In my view (not being an expert) it seems that most people have moved (or don't care about being on latest), and it's *so* different that it's impractical to support both at once.

That being said, I intend to branch vCurrent off where we *could* do more bugfix releases on vCurrent libraries without much trouble. If someone wants to fix things like this, I'm all for it.

**Comment by robhruska** [comment]
Closing it out is cool with me, thanks for the update. It's not been a blocker for us.
